'\" te
.\" Copyright (c) 2015, Oracle and/or its affiliates. All rights reserved.
.TH go 1 "25 Nov 2015" "SunOS 5.11" "User Commands"
.SH NAME
go \- a tool for managing Go source code

.SH SYNOPSIS


.LP
.nf
/usr/bin/go subcommand [arguments]
.fi


.LP
.nf
/usr/bin/go doc
.fi


.LP
.nf
/usr/bin/go doc <pkg>
.fi


.LP
.nf
/usr/bin/go doc <sym>[\&.<method>]
.fi


.LP
.nf
/usr/bin/go doc [<pkg>]\&.<sym>[\&.<method>]
.fi


.LP
.nf
/usr/bin/go doc <pkg> <sym>[\&.<method>]
.fi


.LP
.nf
/usr/bin/go help
.fi


.LP
.nf
/usr/bin/go help [subcommand]
.fi


.LP
.nf
/usr/bin/go help [topic]
.fi


.LP
.nf
/usr/bin/go version
.fi

.SH DESCRIPTION

.sp
.LP
\fBgo\fR is a tool for managing Go source code\&.  The \fBgo doc\fR subcommand gives you access to all of the documentation that comes with Go\&.  You can get more documentation, tutorials and community support online at <https://golang\&.org/>\&.

.SH SUB-COMMANDS

.sp
.LP
Only a few subcommands are documented here; refer to \fBgo help\fR for a complete list of subcommands and topics, and refer to \fBgo doc go\fR for complete documentation:

.sp
.ne 2
.mk
.na
\fB\fBgo help\fR \fI[subcommand|topic]\fR\fR
.ad
.br
.sp .6
.RS 4n
Without any arguments, displays a list of subcommands and available topics\&.  Use \fBgo help \fIsubcommand\fR\fR for more information about a subcommand\&.
.RE

.sp
.ne 2
.mk
.na
\fB\fBgo doc\fR \fI[pkg|sym]\fR\fR
.ad
.br
.sp .6
.RS 4n
Show documentation for package or symbol, or source in current directory if none specified\&.
.RE

.sp
.ne 2
.mk
.na
\fB\fBgo version\fR\fR
.ad
.br
.sp .6
.RS 4n
print Go version\&.
.RE
