'\" t
.TH  BeanShell 2.0b4 "3 Jun 2009"
.SH NAME
beansh | beanshell \- BeanShell, a small and embeddable Java source interpreter
.SH SYNOPSIS
beansh | beanshell [-g] [\fIBeanShell Script\fR]
.SH DESCRIPTION
BeanShell is a small, free, embeddable Java source interpreter with object scripting language features, written in Java. BeanShell dynamically executes standard Java syntax and extends it with common scripting conveniences such as loose types, commands, and method closures like those in Perl and JavaScript.

You can use BeanShell interactively for Java experimentation and debugging as well as to extend your applications in new ways. Scripting Java lends itself to a wide variety of applications including rapid prototyping, user scripting extension, rules engines, configuration, testing, dynamic deployment, embedded systems, and even Java education.

BeanShell is small and embeddable, so you can call BeanShell from your Java applications to execute Java code dynamically at run-time or to provide extensibility in your applications. Alternatively, you can use standalone BeanShell scripts to manipulate Java applications; working with Java objects and APIs dynamically. Since BeanShell is written in Java and runs in the same VM as your application, you can freely pass references to "live" objects into scripts and return them as results.

In short, BeanShell is dynamically interpreted Java, plus a scripting language and flexible environment all rolled into one clean package.

For additional information on using BeanShell, browse the complete documentation at:

file:/usr/share/lib/java/javadoc/beanshell/index.html

.SH OPTIONS
.sp
.ne 2
.mk
-g
.in +24n
.rt
Start in graphics mode. Command-line mode by default.
.sp
.sp 1
.in -24n
.sp
.ne 1
.mk
\fIBeanShell Script\fR.
.in +24n
.rt
Use pre-written BeanShell script.
.sp
.sp1
.in -24n
.SH LICENSE
Sun Public License 1.0
.SH FILES
/usr/bin/beansh
/usr/bin/beanshell
.IP
Command to start BeanShell.
.LP
/usr/share/lib/java/javadoc/beanshell/index.html
.IP
API documentation generated with javadoc.
.LP
/usr/share/doc/beanshell/bshcommands-bshdoc.xml
.IP
Auto-generated command documentation.
.LP
/usr/share/lib/java/bsh-2.0b4.jar
.IP
BeanShell 2.0b4 jar file. This jar contains all of the other jar files listed below.
.LP
/usr/share/lib/java/bsh-core-2.0b4.jar
.IP
Core interpreter only - The minimal footprint, interpreter only.
.LP
/usr/share/lib/java/bsh-classgen-2.0b4.jar
.IP
BeanShell class generation - Adds the ability for BeanShell to script full Java classes and interpret standard Java code.
.LP
/usr/share/lib/java/bsh-commands-2.0b4.jar
.IP
Shell commands - adds useful beanshell shell commands to the core package.
.LP
/usr/share/lib/java/bsh-util-2.0b4.jar
.IP
BeanShell utilities - Adds misc. utilities used by other packages and commands.
.LP
/usr/share/lib/java/bsh-classpath-2.0b4.jar
.IP
BeanShell classpath management - Adds class reloading and classpath capabilities to the core package. Requires Java 1.2 or greater to activate.
.LP
/usr/share/lib/java/bsh-reflect-2.0b4.jar
.IP
BeanShell reflective accessibility - Adds the ability for BeanShell to access private/protected fields, methods, and non-public classes (subject to any Java runtime security). Requires Java 1.2 or greater to activate.
.LP
/usr/share/lib/java/bsh-bsf-2.0b4.jar
.IP
Apache/IBM Bean Scripting Framework (BSF) Adapter for BeanShell - This is the necessary adapter for BeanShell to be used with BSF.
.LP
/usr/demo/bsh/webapps/bshservlet.war
/usr/demo/bsh/webapps/bshservlet-wbsh.war
.IP
A small test servlet and webapp example for BeanShell. Here are two versions - one that comes with the BeanShell JAR included in the WAR file and one that expects the BeanShell JAR to be in the app server's classpath.
.LP

.PD
