'\" te
.TH libgnutls 3 "31 Jul 2008" "SunOS 5.11" "C Library Functions"
.SH "NAME"
libgnutls \-  a TLS library
.SH "DESCRIPTION"
.PP
GnuTLS is a modern C library that implements the standard network
security protocol Transport Layer Security (TLS), for use by network
applications\&.

It provides a secure layer, over a reliable transport layer\&. 
Currently the GnuTLS library implements the proposed standards by the 
IETF\&'s TLS working group\&.

A number of projects in Solaris Desktop such as Evolution, Pidgin,
Ekiga and Vino depend on it\&. 
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(5)
for descriptions of the following attributes:
.sp
.TS
tab() allbox;
cw(2.750000i)| cw(2.750000i)
lw(2.750000i)| lw(2.750000i).
ATTRIBUTE TYPEATTRIBUTE VALUE
Availabilitylibrary/gnutls
Interface stabilityVolatile
.TE
.sp
.SH "SEE ALSO"
.PP
\fBlibgnutls-config\fR(1),
\fBlibgnutlsxx\fR(3),
\fBlibtasn1\fR(3),
\fBattributes\fR(5),
\fBgnome-interfaces\fR(5)
.sp
.ne 2
.mk
\fB\fBhttp://www\&.gnu\&.org/software/gnutls/manual/gnutls\&.html\fR\fR
.SH "NOTES"
.PP
Sun does not guarantee the stability of these interfaces and does not recommend their use\&.  API documentation for these interfaces is provided by the GNU community for those who wish to develop using these interfaces\&. 
.PP
Written by Jeff Cai, Sun Microsystems Inc\&., 2008\&.
...\" created by instant / solbook-to-man, Tue 27 Jan 2015, 17:22
...\" LSARC 2008/341 GnuTLS
