'\" te
.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\"
.\" Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
.\"
.TH pylint-gui 1 "8 Jun 2009" "SunOS 5.11"
.SH NAME
pylint-gui \- simple gui interface to pylint using tkinter

.SH SYNOPSIS
/usr/bin/pylint-gui &

.SH DESCRIPTION
pylint-gui is a graphical front end to pylint using tkinter

.SH FILES
/usr/lib/python2.6/vendor-packages/pylint

.SH SUPPORT
python-projects@logilab.org

.SH SEE ALSO
.IR pylint (1),
.IR logilab-common (3),
.IR logilab-astng (3)
