.\" Copyright (c) 1991, 2001, Oracle and/or its affiliates. All rights reserved.
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a
.\" copy of this software and associated documentation files (the "Software"),
.\" to deal in the Software without restriction, including without limitation
.\" the rights to use, copy, modify, merge, publish, distribute, sublicense,
.\" and/or sell copies of the Software, and to permit persons to whom the
.\" Software is furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice (including the next
.\" paragraph) shall be included in all copies or substantial portions of the
.\" Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
.\" THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
.\" FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
.\" DEALINGS IN THE SOFTWARE.
.TH xcolor 1 "24 July 2001"
.IX "xcolor" "" "\f3xcolor\f1(1) \(em display current colors"
.IX "color" "display" "color" "display current colors \(em \f3xcolor\f1(1)" ""
.SH NAME
xcolor \- displays 256 colors in an X window.
.SH SYNOPSIS
.B xcolor
[
.BI \-display " display"
] [
.BI \-geometry " geometry"
] [
.B \-dump
] [
.B \-nobw
] [
.B \-half
] [
.B \-noinst
] [
.B \-iconwin
]
.SH DESCRIPTION
.B xcolor
displays all 256 colors in a window.  When you move the pointer into the
window, installs a colormap containing a hue ramp with constant saturation
and constant brightness, while preserving black and white.
.SH OPTIONS
.TP 5
.BI \-display " connection"
Connect to X server display,
.IR connection.
.TP 5
.BI \-geometry " geomspec"
Set window size and placement to the standard X11 geometry specification,
.IR geomspec.
.TP 5
.B \-dump
Dumps the RGB values of the default colormap to stdout.
.TP 5
.B \-nobw
Don't preserve black and white in the hue ramp.
.TP 5
.B \-half
Create the hue ramp using only the upper half of the colormap.
.TP 5
.B \-noinst
Don't install the hue ramp.
.TP 5
.B \-iconwin
Use as miniature version of the main window as the icon.
.SH AUTHOR
 Patrick J. Naughton (naughton@wind.sun.com)
