'\" te
.TH libgtkspell 3 "7 Nov 2016" "SunOS 5.12" "User Commands"
.SH "NAME"
libgtkspell \- a GtkTextView spell checker library
.SH "DESCRIPTION"
.PP
\fBlibgtkspell\fR provides word-processor-style highlighting and
replacement of misspelled words in a GtkTextView\&. Right-clicking a misspelled
word pops up a menu of suggested replacements\&.
.PP
To access the API documentation, you must install the developer version of the
package\&.
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
\fB\fB/usr/lib/libgtkspell\&.so\fR\fR
.sp .6
.in +4
GtkTextView spell checker shared library
.sp
.sp 1
.in -4
.sp
.ne 2
.mk
\fB\fB/usr/share/gtk-doc/html/gtkspell \fR\fR
.sp .6
.in +4
 Location of developer documentation
.sp
.sp 1
.in -4
.SH "SEE ALSO"
.PP
\fBenchant\fR(1),
\fBattributes\fR(7),
\fBgnome-interfaces\fR(7)
.SH "NOTES"
.PP
Written by Jim Li, Sun Microsystems Inc\&., 2008\&.
...\" created by instant / solbook-to-man, Tue 27 Jan 2015, 17:22
...\" LSARC 2008/445 GtkSpell - a GtkTextView spell checker library
