#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2022 Marcel Telka
#

%patch% 01-tox-cov-proto.patch
%patch% 02-pip.patch
%patch% 03-tox-indirectly.patch
%patch% 04-sunos-isa.patch

%hook-begin%
# This is the latest version we can test with Python 3.9
VERSION=20.39.0

%include-2%
# tox >= 4.34.1 is needed to test virtualenv >= 20.39.1, but
# Python 3.9 is not supported by tox >= 4.31.0
PYTHON_VERSIONS = 3.9
%include-3%
# This test tries to install setuptools using pip and it fails
PYTEST_ADDOPTS += --deselect tests/unit/create/via_global_ref/test_build_c_ext.py::test_can_build_c_extensions

# Random directory name
COMPONENT_TEST_TRANSFORMS += "-e 's|/tmp/.*/garbage[^/]*|\$$(TMPDIR)|'"
%hook-manifest%
# We need versioned package only, so we cannot have PYVER in the p5m file name
mv "$DISTRIBUTION-PYVER.p5m" "$DISTRIBUTION-39.p5m"
sed -i -e 's/\$(PYVER)/3.9/g' -e 's/\$(PYV)/39/g' "$DISTRIBUTION-39.p5m"
MANIFEST="$DISTRIBUTION-39.p5m"
