.\" tab2space man page for the Tidy Sourceforge project
.TH tab2space 1 "1 Feb 2007" "HTML Tidy 1.0.0" "User commands"

.SH NAME
\fBtab2space\fR - Utility to expand tabs and ensure consistent line endings
.br
.SH SYNOPSIS
\fBtab2space\fR [option ...] [[infile] [outfile]] ...
.SH DESCRIPTION
tab2space is a command-line utility which performs tab expansion and
ensures consistent and appropriate line ending termination characters.
tab2space is distributed as part of the tidy(1) package.
.SH OPTIONS
.TP
\fB-help\fR, \fB-h\fR
display detailed help message
.TP
\fB-dos\fR, \fB-crlf\fR
set line ends to CRLF
(\fIPC-DOS/Windows - default\fR)
.TP
\fB-mac\fR, \fB-cr\fR
set line ends to CR
(\fIclassic Mac OS\fR)
.TP
\fB-unix\fR, \fB-lf\fR
set line ends to LF
(\fIUnix\fR)
.TP
\fB-tabs\fR
preserve tabs, e.g. for Makefile
.TP
\fB-t<n>\fR
set tabs to <n> (default is 4) spaces
.SH USAGE
.LP
Use \fB--\fR\fIhelp\fR or \fB-\fR\fIh\fR for detailed configuration options.
.LP
Input/Output default to stdin/stdout respectively.
.LP
For further info on HTML see \fIhttp://www.w3.org/MarkUp\fR.
.LP
For more information about HTML Tidy, visit the project home page at \fIhttp://tidy.sourceforge.net\fR.  Here, you will find links to documentation, mailing lists (with searchable archives) and links to report bugs.
.SH "EXIT STATUS"
.IP 0
All input files were processed successfully.
.IP 1
There were warnings.
.IP 2
There were errors.
.SH "SEE ALSO"
HTML Tidy Project Page at \fIhttp://tidy.sourceforge.net\fR
.SH AUTHOR
\fBTidy\fR was written by Dave Raggett <\fIdsr@w3.org\fR>, and is now maintained and developed by the Tidy team at \fIhttp://tidy.sourceforge.net/\fR.  It is released under the \fIMIT Licence\fR.
.LP
Generated automatically with HTML Tidy released on 1 September 2005.
