foldersTree = gFld("<b>HTML Tidy</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("buffio.h", "", "buffio_8h.html"))
       insDoc(aux1, gLnk("fileio.h", "", "fileio_8h.html"))
       insDoc(aux1, gLnk("tidy.h", "", "tidy_8h.html"))
       insDoc(aux1, gLnk("tidyenum.h", "", "tidyenum_8h.html"))
aux1 = insFld(foldersTree, gFld("Data Structures", "", "annotated.html"))
       insDoc(aux1, gLnk("_TidyBuffer", "", "struct__TidyBuffer.html"))
       insDoc(aux1, gLnk("_TidyInputSource", "", "struct__TidyInputSource.html"))
       insDoc(aux1, gLnk("_TidyOutputSink", "", "struct__TidyOutputSink.html"))
       insDoc(aux1, gLnk("TidyAttr", "", "structTidyAttr.html"))
       insDoc(aux1, gLnk("TidyDoc", "", "structTidyDoc.html"))
       insDoc(aux1, gLnk("TidyNode", "", "structTidyNode.html"))
       insDoc(aux1, gLnk("TidyOption", "", "structTidyOption.html"))
     insDoc(foldersTree, gLnk("Data Fields", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Modules", "", "modules.html"))
       insDoc(aux1, gLnk("Opaque Types", "", "group__Opaque.html"))
       insDoc(aux1, gLnk("Basic Operations", "", "group__Basic.html"))
       insDoc(aux1, gLnk("Configuration Options", "", "group__Configuration.html"))
       insDoc(aux1, gLnk("I/O and Messages", "", "group__IO.html"))
       insDoc(aux1, gLnk("Memory Allocation", "", "group__Memory.html"))
       insDoc(aux1, gLnk("Document Parse", "", "group__Parse.html"))
       insDoc(aux1, gLnk("Diagnostics and Repair", "", "group__Clean.html"))
       insDoc(aux1, gLnk("Document Save Functions", "", "group__Save.html"))
       insDoc(aux1, gLnk("Document Tree", "", "group__Tree.html"))
       insDoc(aux1, gLnk("Node Interrogation", "", "group__NodeAsk.html"))
       insDoc(aux1, gLnk("Attribute Interrogation", "", "group__Attribute.html"))
       insDoc(aux1, gLnk("Attribute Retrieval", "", "group__AttrGet.html"))
     insDoc(foldersTree, gLnk("Globals", "", "globals.html"))
