'\" te
.TH thunderbird 1 "8 Jun 2006" "SunOS 5.12" "User Commands"
.SH "NAME"
thunderbird \- Thunderbird for 
Oracle Solaris Desktop
.SH "SYNOPSIS"
.PP
\fBthunderbird\fR [\fBoptions \&.\&.\&. \fR] [\fBurl\fR]
.SH "DESCRIPTION"
.PP
Thunderbird is a free, open-source mail client based on the Mozilla codebase\&.
It is a robust and easy to use client,similar to competing products like other mail
client, but with some major advantages such as junk mail classification\&.
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fBheight \fIvalue\fR\fR\fR
.in +24n
.rt
Set the height of startup window to \fIvalue\fR\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBh \fRor -\fBhelp \fR\fR
.in +24n
.rt
Display the help message\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBwidth \fIvalue\fR\fR\fR
.in +24n
.rt
Set the width of startup window to \fIvalue\fR\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBv \fRor -\fBversion \fR\fR
.in +24n
.rt
Display the version message\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBP \fIprofile\fR\fR\fR
.in +24n
.rt
Start with the profile named: \fIprofile\fR\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBProfileManager \fR\fR
.in +24n
.rt
Start with profile manager\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBUILocale \fIlocale\fR\fR\fR
.in +24n
.rt
Start with the UI Locale listed: \fIlocale\fR\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBcontentLocale \fIlocale\fR\fR\fR
.in +24n
.rt
Start with the content Locale listed: \fIlocale\fR\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBjsconsole \fR\fR
.in +24n
.rt
Open the JavaScript console\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBaddressbook \fR\fR
.in +24n
.rt
Open the address book at startup\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBcompose \fR\fR
.in +24n
.rt
Compose a mail or news message\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBmail \fR\fR
.in +24n
.rt
Open the mail folder view\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBoptions \fR\fR
.in +24n
.rt
Open the options dialog\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBnews \fR\fR
.in +24n
.rt
Open the news client\&.
.sp
.sp 1
.in -24n
.SH "EXAMPLES"
.PP
\fBExample 1: Launching Thunderbird\fR
.PP
.PP
.nf
example% \fBthunderbird \fR
.PP
When logged via 'ssh -X', dbus-launch is advised to use:
.PP
example% \fBdbus-launch thunderbird \fR
.fi
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.sp
.ne 2
.mk
\fB\fB0\fR\fR
.in +9n
.rt
Application
exited successfully
.sp
.sp 1
.in -9n
.sp
.ne 2
.mk
\fB\fB1\fR\fR
.in +9n
.rt
Application
exited with failure
.sp
.sp 1
.in -9n
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
\fB\fB/usr/bin/thunderbird\fR \fR
.in +32n
.rt
Executable for Thunderbird application
.sp
.sp 1
.in -32n
.sp
.ne 2
.mk
\fB\fB$HOME/\&.mozilla/thunderbird\fR \fR
.in +32n
.rt
User configuration files for Thunderbird
.sp
.sp 1
.in -32n
.SH "SEE ALSO"
.PP
For more information about thunderbird, please refer to
\fBhttp://www\&.mozilla\&.org/thunderbird\fR
.PP
Refer to Help -> Help Contents for more information\&.
.SH "NOTES"
.PP
Updated by Leon Sha, Sun Microsystems Inc\&., 2006\&. 
...\" created by instant / solbook-to-man, Tue 27 Jan 2015, 17:23
...\" LSARC 2006/237 Thunderbird 1.5
...\" LSARC 2006/693 Thunderbird 2 for Solaris Nevada and Solaris10 Update
...\" LSARC 2009/085 Thunderbird 3.0.x
