.TH gnome-system-monitor 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
gnome-system-monitor \- view system processes and monitor system usage
.SH "SYNOPSIS"
.PP
\fBgnome-system-monitor\fR [\fB\fIgnome-std-options\fR\fR]
.SH "DESCRIPTION"
.PP
The System Monitor application displays a list of system processes,
and monitors system usage\&. System Monitor shows which processes are running
and how the processes are related\&.
.PP
System Monitor also provides detailed information about individual processes,
and enables the user to control which processes are running\&. System Monitor
displays how much processor (CPU) capacity the system is using, and how much
disk space the system is using on each device\&.
.PP
System Monitor displays this information in a graphical interface so
that users can see what the system is doing\&. Users can then use the same
graphical interface to modify the behavior of the system\&.
.SH "OPTIONS"
.PP
The following options are supported:
.TP 24
.I gnome-std-options
Standard options available for use with most GNOME applications\&.
See \fBgnome-std-options\fR(7) for more information\&.
.SH "ENVIRONMENT VARIABLES"
.PP
See \fBenviron\fR(7) for descriptions of the following environment
variables that affect the execution of \fBgnome-system-monitor\fR: NLSPATH\&.
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.TP 9
.B 0
Application
exited successfully
.TP 9
.B >0
Application
exited with failure
.SH "SEE ALSO"
.PP
\fISystem Monitor Manual\fR
.PP
Latest version of the \fIGNOME Desktop User Guide\fR
for your platform\&.
.PP
.BR top (1),
.BR prstat (8),
.BR attributes (7),
.BR environ (7),
.BR gnome-std-options (7)
.SH "NOTES"
.PP
Written by Niall Power, Sun Microsystems Inc\&., 2003\&.
Updated by Henry Zhang, Sun Microsystems Inc\&., 2006\&.
