.\" This manual page is derived from documentation obtained from
.\" http://manpages.ubuntu.com/manpages/precise/en/man1/pep8.1.html
.TH PEP8 "1" "March 2013" "pep8 XXX" "User Commands"
.SH NAME
pep8 \- A tool to check your Python code against some of the style conventions in PEP 8.
.SH SYNOPSIS
.B pep8
[\fIoptions\fR] \fIinput \fR...
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
print status messages, or debug with \fB\-vv\fR
.TP
\fB\-q\fR, \fB\-\-quiet\fR
report only file names, or nothing with \fB\-qq\fR
.TP
\fB\-\-exclude\fR=\fIpatterns\fR
skip matches (default .svn,CVS,*.pyc,*.pyo)
.TP
\fB\-\-filename\fR=\fIpatterns\fR
only check matching files (e.g. *.py)
.TP
\fB\-\-ignore\fR=\fIerrors\fR
skip errors and warnings (e.g. E4,W)
.TP
\fB\-\-repeat\fR
show all occurrences of the same error
.TP
\fB\-\-show\-source\fR
show source code for each error
.TP
\fB\-\-show\-pep8\fR
show text of PEP 8 for each error
.TP
\fB\-\-statistics\fR
count errors and warnings
.TP
\fB\-\-benchmark\fR
measure processing speed
.TP
\fB\-\-testsuite\fR=\fIdir\fR
run regression tests from dir
.TP
\fB\-\-doctest\fR
run doctest on myself
.SH AUTHOR
This manual page was written by David Watson <david@bashton.com>.
