#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2025 Marcel Telka
#

%patch% 01-wmi.patch
%patch% 02-test-extras.patch

%include-3%
# We have no MongoDB packaged
PYTEST_ADDOPTS += --deselect tests/test_compat.py::test_save_no_id
PYTEST_ADDOPTS += --deselect tests/test_compat.py::test_save_new_with_id
PYTEST_ADDOPTS += --deselect tests/test_compat.py::test_save_replace_by_id
PYTEST_ADDOPTS += --deselect tests/test_compat.py::test_save_no_id_extant_docs
PYTEST_ADDOPTS += --deselect tests/test_compat.py::test_save_adds_id
PYTEST_ADDOPTS += --deselect tests/test_fields.py::test_insert_with_dots
PYTEST_ADDOPTS += --deselect tests/test_insert_doc.py::test_insert_doc_command
PYTEST_ADDOPTS += --deselect tests/test_manage.py::test_purge_all_databases
PYTEST_ADDOPTS += --deselect tests/test_service.py::test_fixture
PYTEST_ADDOPTS += --deselect tests/test_sessions.py::TestSessions::test_session_persists
PYTEST_ADDOPTS += --deselect tests/test_sessions.py::TestSessions::test_locked_session
PYTEST_ADDOPTS += --deselect tests/test_testing.py::test_assert_covered_passes
PYTEST_ADDOPTS += --deselect tests/test_testing.py::test_assert_covered_empty
PYTEST_ADDOPTS += --deselect tests/test_testing.py::test_assert_covered_null
PYTEST_ADDOPTS += --deselect tests/test_testing.py::test_assert_index_used_passes
PYTEST_ADDOPTS += --deselect tests/test_testing.py::test_assert_index_used_fails
PYTEST_ADDOPTS += --deselect jaraco/mongodb/helper.py::jaraco.mongodb.helper.server_version
PYTEST_ADDOPTS += --deselect jaraco/mongodb/query.py::jaraco.mongodb.query.upsert_and_fetch
PYTEST_ADDOPTS += --deselect jaraco/mongodb/sampling.py::jaraco.mongodb.sampling.estimate
