#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2023 Marcel Telka
#

%patch% 01-no-pytest-instafail.patch
%patch% 02-users.patch
%patch% 03-sunos.patch
%patch% 04-test_cpu_times_comparison.patch
%patch% 05-test_count.patch

%include-3%
# This project does not support tox so we need to provide test requirements
# manually.
TEST_REQUIREMENTS_EXTRAS += test

# We need to run tests in proto area to get access to compiled modules
COMPONENT_TEST_DIR = $(PROTO_DIR)/$(PYTHON_LIB)
# ... and so we need to point back to build dir for scripts subdirectory
COMPONENT_TEST_ENV += PSUTIL_ROOT_DIR=$(@D)
# https://github.com/giampaolo/psutil/issues/2686
COMPONENT_TEST_ENV += PSUTIL_DEBUG=0

# fails on zfs
PYTEST_ADDOPTS += --deselect psutil/tests/test_posix.py::TestSystemAPIs::test_disk_usage
# process priority and nice does not match
PYTEST_ADDOPTS += --deselect psutil/tests/test_process.py::TestProcess::test_nice
# https://github.com/giampaolo/psutil/issues/2358
PYTEST_ADDOPTS += --deselect psutil/tests/test_process_all.py::TestFetchAllProcesses::test_all
# these tests are unable to find setup.py because we run tests from non-default directory
PYTEST_ADDOPTS += --deselect psutil/tests/test_scripts.py::TestSetupScript::test_invocation
PYTEST_ADDOPTS += --deselect psutil/tests/test_scripts.py::TestSetupScript::test_python2
# we have no pyperf packaged yet
PYTEST_ADDOPTS += --deselect psutil/tests/test_scripts.py::TestInternalScripts::test_import_all
# The test_memory_maps fails on Python 3.9 due to the not so robust realpath implementation
PYTEST_ADDOPTS += --deselect psutil/tests/test_unicode.py::TestFSAPIs::test_memory_maps
PYTEST_ADDOPTS += --deselect psutil/tests/test_unicode.py::TestFSAPIsWithInvalidPath::test_memory_maps
