'\" te
.\" Copyright (C) 2010 Internet Systems Consortium, Inc. ("ISC")
.\" Permission to use, copy, modify, and/or distribute this software for any purpose  with or without fee is hereby granted, provided that the above copyright notice  and this permission notice appear in all copies.  THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL,  DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING  FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE  USE OR PERFORMANCE OF THIS SOFTWARE.
.\" Portions Copyright (c) 2010, Sun Microsystems, Inc. All Rights Reserved.
.TH dig 8 "2010 年 1 月 11 日" "SunOS 5.12" "システム管理コマンド"
.SH 名前
dig \- DNS 検索ユーティリティー
.SH 形式
.LP
.nf
\fBdig\fR [@server] [\fB-b\fR \fIaddress\fR] [\fB-c\fR \fIclass\fR] [\fB-f\fR \fIfilename\fR] 
     [\fB-k\fR \fIfilename\fR] [\fB-m\fR] [\fB-p\fR \fIport#\fR] [\fB-q\fR \fIname\fR] [\fB-t\fR \fItype\fR] [\fB-x\fR \fIaddr\fR] 
     [\fB-y\fR [\fIhmac\fR:]\fIname:key\fR] [\fB-4\fR] [\fB-6\fR] [\fIname\fR] [\fItype\fR] [\fIclass\fR] [\fIqueryopt\fR]...
.fi

.LP
.nf
\fBdig\fR [\fB-h\fR]
.fi

.LP
.nf
\fBdig\fR [\fIglobal-queryopt\fR...] [\fIquery\fR...]
.fi

.SH 機能説明
.sp
.LP
\fBdig\fR (Domain Information Groper) ユーティリティーは、DNS ネームサーバーに問い合わせるための柔軟性に優れたツールです。dig ユーティリティーは、DNS 検索を実行し、照会したネームサーバーから返された回答を表示します。\fBdig\fR ユーティリティーは、柔軟性に優れ、使いやすく、出力が明確であるため、ほとんどの DNS 管理者がこのユーティリティーを使用して DNS の問題をトラブルシューティングします。ほかの検索ツールは、多くの場合で \fBdig\fR ほど機能性に優れていません。
.sp
.LP
通常、\fBdig\fR は、コマンド行引数とともに使用されますが、ファイルから検索要求を読み取るバッチモード操作にも対応します。\fB-h\fR オプションを指定すると、そのコマンド行引数とオプションの簡単なサマリーが出力されます。以前のバージョンとは異なり、BIND 9 における \fBdig\fR の実装では、コマンド行から複数の検索を発行できます。
.sp
.LP
特定のネームサーバーに照会するよう指示されていないかぎり、\fBdig\fR は、\fB/etc/resolv.conf\fR に記載されている各サーバーに照会します。
.sp
.LP
コマンド行引数またはオプションを指定しない場合、\fBdig\fR は、「.」(ルート) に対して NS クエリーを実行します。
.sp
.LP
\fB${HOME}/.digrc\fR を使用すると、\fBdig\fR のユーザーごとのデフォルトを設定できます。コマンド行引数の前に、このファイルが読み取られ、含まれているオプションが適用されます。
.sp
.LP
クラス名 \fBIN\fR および \fBCH\fR は、トップレベルドメイン名 \fBIN\fR および \fBCH\fR と一致します。これらのトップレベルドメインを検索するときは、\fB-t\fR オプションおよび \fB-c\fR オプションを使用してタイプとクラスを指定するか、\fB"IN."\fR および \fB "CH."\fR を使用します。
.SS "簡単な使用法"
.sp
.LP
一般的な \fBdig\fR の呼び出しを次に示します。
.sp
.in +2
.nf
dig @server name type 
.fi
.in -2
.sp

.sp
.LP
各表記の意味は次のとおりです。
.sp
.ne 2
.mk
.na
\fB\fIserver\fR\fR
.ad
.sp .6
.RS 4n
照会するネームサーバーの名前または IP アドレス。ドット区切り 10 進表記の IPv4 アドレスか、コロン区切り表記の IPv6 アドレスを指定できます。指定された \fIserver\fR 引数がホスト名の場合、\fBdig\fR は、その名前を解決してから、そのネームサーバーに照会します。\fIserver\fR 引数を指定しない場合、\fBdig\fR は \fB/etc/resolv.conf\fR を参照し、そのファイルに記載されているネームサーバーに照会します。応答したネームサーバーからの応答が表示されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fIname\fR\fR
.ad
.sp .6
.RS 4n
検索するリソースレコードの名前。
.RE

.sp
.ne 2
.mk
.na
\fB\fItype\fR\fR
.ad
.sp .6
.RS 4n
どのタイプのクエリーが必要かを示します (ANY、A、MX、SIG など)。\fItype\fR には、任意の有効なクエリータイプを指定できます。\fItype\fR 引数を指定しない場合、\fBdig\fR は、A レコードの検索を実行します。
.RE

.SH オプション
.sp
.LP
サポートしているオプションは、次のとおりです。
.sp
.ne 2
.mk
.na
\fB\fB-4\fR\fR
.ad
.sp .6
.RS 4n
IPv4 トランスポートのみを使用します。デフォルトでは、IPv4 トランスポートと IPv6 トランスポートの両方を使用できます。オプション \fB-4\fR とオプション \fB-6\fR は相互に排他的です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-6\fR\fR
.ad
.sp .6
.RS 4n
IPv6 トランスポートのみを使用します。デフォルトでは、IPv4 トランスポートと IPv6 トランスポートの両方を使用できます。オプション \fB-4\fR とオプション \fB-6\fR は相互に排他的です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-b\fR \fIaddress\fR\fR
.ad
.sp .6
.RS 4n
クエリーのソース IP アドレスを \fIaddress\fR に設定します。これは、ホストのいずれかのネットワークインタフェース上の有効なアドレスか、\fB0.0.0.0\fR または \fB::\fR である必要があります。\fB#\fR\fI<port> \fR を追加して、オプションのポートを指定できます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-c\fR \fIclass\fR\fR
.ad
.sp .6
.RS 4n
デフォルトのクエリークラス (インターネットを表す IN) をオーバーライドします。\fIclass\fR 引数は、HS (Hesiod レコード) や CH (CHAOSNET レコード) などの有効な任意のクラスです。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-f\fR \fIfilename\fR\fR
.ad
.sp .6
.RS 4n
ファイル \fIfilename\fR から、処理対象の検索要求のリストを読み取って、バッチモードで動作します。ファイルには、1 行に 1 つずつ、複数のクエリーが含まれています。ファイル内の各エントリは、コマンド行インタフェースを使用して \fBdig\fR で発行するクエリーを指定する場合と同じように構成するようにしてください。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-h\fR\fR
.ad
.sp .6
.RS 4n
コマンド行引数およびオプションの簡単なサマリーを出力します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-k\fR \fIfilename\fR\fR
.ad
.sp .6
.RS 4n
\fBdig\fR によって送信される DNS クエリーとその応答に、トランザクション署名 (Transaction Signature、TSIG) を使用して署名するための TSIG 鍵ファイルを指定します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-m\fR\fR
.ad
.sp .6
.RS 4n
メモリー使用量のデバッグを有効にします。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-p\fR \fIport#\fR\fR
.ad
.sp .6
.RS 4n
標準以外のポート番号を照会します。\fIport#\fR 引数は、\fBdig\fR が標準の DNS ポート番号 53 の代わりにクエリーを送信するポート番号です。このオプションを使用すると、標準以外のポート番号でクエリーを待機するように構成されているネームサーバーをテストできます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-q\fR \fIname\fR\fR
.ad
.sp .6
.RS 4n
クエリー名を \fIname\fR に設定します。これは、クエリー名をほかの引数と容易に区別できるという点で便利です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR \fItype\fR\fR
.ad
.sp .6
.RS 4n
クエリータイプを \fItype\fR に設定します。これには、BIND9 でサポートされている有効なクエリータイプを指定できます。逆検索を示す \fB-x\fR オプションが指定されていないかぎり、デフォルトのクエリータイプは「A」です。タイプ AXFR を指定することによって、ゾーン転送を要求できます。増分ゾーン転送 (Incremental Zone Transfer、IXFR) が必要な場合は、\fItype\fR を \fBixfr\fR=\fIN\fR に設定します。増分ゾーン転送には、ゾーンの SOA レコードのシリアル番号が \fIN\fR であった時点以降にゾーンに加えられた変更が含まれます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-x\fR \fIaddr\fR\fR
.ad
.sp .6
.RS 4n
逆検索を簡略化します (アドレスを名前にマッピングします)。\fIaddr\fR 引数は、ドット区切り 10 進表記の IPv4 アドレスか、コロン区切りの IPv6 アドレスです。このオプションを使用する場合は、\fIname\fR、\fIclass\fR、および \fItype\fR の各引数を指定する必要はありません。\fBdig\fR ユーティリティーは、自動的に \fB11.12.13.10.in-addr.arpa\fR などの名前の検索を実行し、クエリーのタイプとクラスをそれぞれ PTR と IN に設定します。デフォルトでは、IPv6 アドレスはニブル形式を使用して IP6.ARPA ドメインで検索されます。IP6.INT ドメインを使用する以前の RFC1886 方式を使用するには、\fB-i\fR オプションを指定します。ビット文字列ラベル (RFC 2874) は、実験的な段階であり、試行されません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-y\fR [\fIhmac\fR:]\fIname\fR:\fIkey\fR\fR
.ad
.sp .6
.RS 4n
コマンド行でトランザクション署名 (TSIG) 鍵を指定します。これは、\fBdig\fR によって送信される DNS クエリーと、その応答に署名するために行います。\fB-y\fR オプションを使用すると、TSIG 鍵自体をコマンド行で指定することもできます。オプションの \fIhmac\fR は TSIG のタイプであり、デフォルトは \fBHMAC-MD5\fR です。\fIname\fR 引数は TSIG 鍵の名前であり、\fIkey\fR 引数は実際の鍵です。鍵は base-64 でエンコードされた文字列であり、通常は、\fBdnssec-keygen\fR(8) によって生成されます。 
.sp
鍵が \fBps\fR(1) の出力またはシェルの履歴ファイルに示されるため、複数ユーザーシステムで \fB-y\fR オプションを使用するときは注意するようにしてください。\fBdig\fR で TSIG 認証を使用する場合は、照会されるネームサーバーが、使用される鍵とアルゴリズムを認識できる必要があります。BIND では、\fBnamed.conf\fR で適切な \fBkey\fR 文と \fBserver\fR 文を指定します。
.RE

.SH クエリーオプション
.sp
.LP
\fBdig\fR ユーティリティーには、検索方法と結果の表示方法に影響を与える多数のクエリーオプションが用意されています。これらのクエリーオプションを使用すると、クエリーヘッダーのフラグビットを設定/リセットしたり、回答のどの部分を出力するかを決定したり、タイムアウト/再試行方針を決定したりできます。
.sp
.LP
各クエリーオプションは、プラス記号 (+) とそれに続くキーワードによって識別されます。一部のキーワードは、オプションを設定またはリセットします。これらのキーワードの前に文字列 no を指定すると、そのキーワードの意味を否定できます。タイムアウトの間隔など、オプションに値を割り当てるキーワードもあります。これらは、\fB+keyword=\fR\fI value\fR の形式をとります。クエリーオプションを次に示します。
.sp
.ne 2
.mk
.na
\fB\fB+[no]tcp\fR\fR
.ad
.sp .6
.RS 4n
ネームサーバーに照会するときに TCP を使用します [使用しません]。デフォルトの動作では UDP が使用されます。ただし、TCP 接続が使用される AXFR または IXFR クエリーが要求された場合を除きます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]vc\fR\fR
.ad
.sp .6
.RS 4n
ネームサーバーに照会するときに TCP を使用します [使用しません]。\fB+[no]tcp\fR の代替構文は下位互換性を確保するために用意されています。「vc」は、「virtual circuit (仮想回路)」を表します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]ignore\fR\fR
.ad
.sp .6
.RS 4n
TCP で再試行する代わりに、UDP 応答での切り捨てを無視します。デフォルトでは、TCP での再試行が実行されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+domain=\fR\fIsomename\fR\fR
.ad
.sp .6
.RS 4n
\fB/etc/resolv.conf\fR の \fBdomain\fR 指令で指定された場合と同じように単一のドメイン \fIsomename\fR を含めるように検索リストを設定し、\fB+search\fR オプションが指定された場合と同じように検索リストが処理されるようにします。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]search\fR\fR
.ad
.sp .6
.RS 4n
\fBsearchlist\fR、または存在する場合は \fBresolv.conf\fR の \fBdomain\fR 指令で定義されている検索リストを使用します [使用しません]。デフォルトでは、検索リストは使用されません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]showsearch\fR\fR
.ad
.sp .6
.RS 4n
中間結果を表示して検索を実行します [実行しません]。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]defname\fR\fR
.ad
.sp .6
.RS 4n
非推奨、\fB+[no]search\fR の同義語として処理されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]aaonly\fR\fR
.ad
.sp .6
.RS 4n
クエリーで \fBaa\fR フラグを設定します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]aaflag\fR\fR
.ad
.sp .6
.RS 4n
\fB+[no]aaonly\fR の同義語です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]adflag\fR\fR
.ad
.sp .6
.RS 4n
クエリーで AD (Authentic Data、認証済みデータ) ビットを設定します [設定しません]。これは、サーバーのセキュリティーポリシーに従って、すべての回答セクションおよび権限セクションが検証されたかどうかにかかわらず、安全であると応答するようにサーバーに要求します。設定 \fBAD=1\fR は、すべてのレコードが安全であると検証されいて、回答が \fBOPT-OUT\fR の範囲からではないことを示します。\fBAD=0\fR は、回答の一部が安全ではないか、検証されていないことを示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]cdflag\fR\fR
.ad
.sp .6
.RS 4n
クエリーで CD (Checking Disabled、チェック無効) ビットを設定します [設定しません]。これは、応答の DNSSEC 検証を実行しないようにサーバーに要求します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]cl\fR\fR
.ad
.sp .6
.RS 4n
レコードを出力するときに CLASS を表示します [表示しません]。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]ttlid\fR\fR
.ad
.sp .6
.RS 4n
レコードを出力するときに TTL を表示します [表示しません]。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]recurse\fR\fR
.ad
.sp .6
.RS 4n
クエリーで RD (Recursion Desired、再帰要望) ビットの設定を切り替えます。デフォルトでは、このビットは設定されています。これは、\fBdig\fR で通常は再帰クエリーが送信されることを意味します。\fB+nssearch\fR または \fB+trace\fR クエリーオプションが使用されている場合、再帰は自動的に無効になります。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]nssearch\fR\fR
.ad
.sp .6
.RS 4n
このオプションを設定すると、\fBdig\fR は、検索対象の名前が含まれるゾーンの信頼できるネームサーバーを見つけて、各ネームサーバーが持つゾーンの SOA レコードを表示しようとします。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]trace\fR\fR
.ad
.sp .6
.RS 4n
検索対象の名前の、ルートネームサーバーからの委譲パスのトレースの有効/無効を切り替えます。デフォルトでは、トレースは無効になっています。トレースを有効にすると、\fBdig\fR は、反復クエリーを実行して検索対象の名前を解決します。ルートサーバーからのリフェラルを追跡し、検索の解決に使用した各サーバーからの回答を表示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]cmd\fR\fR
.ad
.sp .6
.RS 4n
出力の中にある、\fBdig\fR のバージョンと適用されているクエリーオプションを識別する先頭のコメントの有無を切り替えます。デフォルトでは、このコメントは出力されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]short\fR\fR
.ad
.sp .6
.RS 4n
簡易形式の回答を表示します。デフォルトでは、詳細形式の回答が出力されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]identify\fR\fR
.ad
.sp .6
.RS 4n
+\fIshort\fR オプションが有効になっている場合に、回答を返したサーバーの IP アドレスおよびポート番号を表示します [表示しません]。短い形式の回答を要求した場合、デフォルトでは、回答を返したサーバーの発信元アドレスおよびポート番号は表示されません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]comments\fR\fR
.ad
.sp .6
.RS 4n
出力でのコメント行の表示の有無を切り替えます。デフォルトでは、コメントが出力されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]stats\fR\fR
.ad
.sp .6
.RS 4n
クエリーが発行された時刻、応答のサイズなどの統計情報の出力の有無を切り替えます。デフォルトの動作では、クエリーの統計情報が出力されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]qr\fR\fR
.ad
.sp .6
.RS 4n
クエリーが送信されたときにクエリーを出力します [出力しません]。デフォルトでは、クエリーは出力されません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]question\fR\fR
.ad
.sp .6
.RS 4n
回答が返されたときに、クエリーの質問セクションを出力します [出力しません]。デフォルトでは、質問セクションがコメントとして出力されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]answer\fR\fR
.ad
.sp .6
.RS 4n
応答の回答セクションを表示します [表示しません]。デフォルトでは表示されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]authority\fR\fR
.ad
.sp .6
.RS 4n
応答の権限セクションを表示します [表示しません]。デフォルトでは表示されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]additional\fR\fR
.ad
.sp .6
.RS 4n
応答の追加セクションを表示します [表示しません]。デフォルトでは表示されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]all\fR\fR
.ad
.sp .6
.RS 4n
すべての表示フラグを設定またはクリアします。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+time=\fR\fIT\fR\fR
.ad
.sp .6
.RS 4n
クエリーのタイムアウトを \fIT\fR 秒に設定します。デフォルトのタイムアウトは 5 秒です。\fIT\fR を 1 未満に設定しようとした場合、1 秒が適用されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+tries=\fR\fIT\fR\fR
.ad
.sp .6
.RS 4n
UDP での最大試行回数を \fIT\fR に設定します。デフォルトの数値は 3 (最初の試行が 1 回と、その後の再試行が 2 回) です。T が 0 以下の場合、再試行回数は自動的に 1 に切り上げられます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+retry=\fR\fIT\fR\fR
.ad
.sp .6
.RS 4n
UDP での再試行回数を \fIT\fR に設定します。デフォルトは 2 です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+ndots=\fR\fID\fR\fR
.ad
.sp .6
.RS 4n
\fIname\fR に示すドットの数を \fID\fR に設定します。この数のドットが含まれる名前は絶対名と見なされます。デフォルト値は、\fB/etc/resolv.conf\fR で \fBndots\fR 文を使用して定義されている値です。\fBndots\fR 文が存在しない場合は 1 です。ドットがこの値よりも少ない名前は、相対名と解釈され、\fB/etc/resolv.conf\fR の \fBsearch\fR 指令または \fBdomain\fR 指令に示されているドメイン内で検索されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+bufsize=\fR\fIB\fR\fR
.ad
.sp .6
.RS 4n
EDNS0 を使用して通知される UDP メッセージバッファーサイズを \fIB\fR バイトに設定します。このバッファーの最大および最小サイズはそれぞれ 65535 と 0 です。この範囲外の値は、適切に切り上げられるか、切り下げられます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+edns=\fR\fI#\fR\fR
.ad
.sp .6
.RS 4n
クエリーで使用される EDNS バージョンを指定します。有効な値の範囲は 0 - 255 です。EDNS バージョンを設定すると、EDNS クエリーが送信されます。\fB+noedns\fR により、記憶されている EDNS バージョンはクリアされます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]multiline\fR\fR
.ad
.sp .6
.RS 4n
SOA レコードなどのレコードを、詳細な複数行形式で、人間が読める形式のコメントとともに出力します。デフォルトでは、\fBdig\fR 出力をマシンで容易に解析できるようにするため、各レコードが 1 行に 1 つずつ出力されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]fail\fR\fR
.ad
.sp .6
.RS 4n
\fBSERVFAIL\fR を受け取った場合に、次のサーバーを試行しません。デフォルトでは次のサーバーを試行しません。これは、通常のスタブリゾルバとは逆の動作です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]besteffort\fR\fR
.ad
.sp .6
.RS 4n
不正な形式のメッセージの内容を表示しようとします。デフォルトでは、不正な形式の回答は表示されません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]dnssec\fR\fR
.ad
.sp .6
.RS 4n
クエリーの追加セクションの OPT レコードで DNSSEC OK (DO) ビットを設定し、DNSSEC レコードが送信されるよう要求します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]sigchase\fR\fR
.ad
.sp .6
.RS 4n
DNSSEC 署名チェーンを追跡します。\fB-DDIG_SIGCHASE\fR を使用して \fBdig\fR をコンパイルする必要があります。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+trusted-key=\fR####\fR
.ad
.sp .6
.RS 4n
\fB+sigchase\fR で使用される信頼できる鍵が含まれるファイルを指定します。\fBDNSKEY\fR レコードは、1 行に 1 つずつ記述する必要があります。
.sp
ファイルを指定しない場合、dig は、\fB/etc/trusted-key.key\fR、現在のディレクトリの \fBtrusted-key.key\fR の順に検索します。
.sp
\fB-DDIG_SIGCHASE\fR を使用して \fBdig\fR をコンパイルする必要があります。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]topdown\fR\fR
.ad
.sp .6
.RS 4n
DNSSEC 署名チェーンを追跡するときに、トップダウン検証を実行します。\fB-DDIG_SIGCHASE\fR を使用して \fBdig\fR をコンパイルする必要があります。
.RE

.sp
.ne 2
.mk
.na
\fB\fB+[no]nsid\fR\fR
.ad
.sp .6
.RS 4n
クエリーを送信するときに、EDNS ネームサーバーの ID 要求を含めます。
.RE

.SH 複数のクエリー
.sp
.LP
BIND 9 における \fBdig\fR の実装では、(\fB-f\fR バッチファイルオプションのサポートに加えて) コマンド行での複数のクエリーの指定がサポートされます。これらの各クエリーは、それぞれ一連のフラグ、オプション、およびクエリーオプションを設定して発行できます。
.sp
.LP
この場合、各 \fIquery\fR 引数は、前述のコマンド行構文での個々のクエリーを表します。各クエリーは、標準のオプションとフラグ、検索対象の名前、クエリータイプ (省略可能)、クラス、およびそのクエリーに適用するクエリーオプションで構成されます。
.sp
.LP
すべてのクエリーに適用するクエリーオプションのグローバルセットを設定することもできます。これらのグローバルなクエリーオプションは、コマンド行で、名前、クラス、タイプ、オプション、フラグ、およびクエリーオプションの最初の組の前に指定する必要があります。グローバルなクエリーオプション (\fB+[no]cmd\fR オプションを除く) は、クエリーごとの一連のクエリーオプションで上書きできます。例: 
.sp
.in +2
.nf
dig +qr www.isc.org any -x 127.0.0.1 isc.org ns +noqr
.fi
.in -2
.sp

.sp
.LP
この例は、コマンド行から \fBdig\fR を使用して、3 つの検索 (\fBwww.isc.org\fR の ANY クエリー、127.0.0.1 の逆検索、および \fBisc.org\fR の NS レコードのクエリー) を実行する方法を示しています。グローバルなクエリーオプション \fB+qr\fR が適用されているため、\fBdig\fR によって、発行された最初のクエリーが各検索で表示されます。最後のクエリーには、ローカルなクエリーオプション \fB+noqr\fR が指定されています。これは、\fBdig\fR によって、\fBisc.org\fR の NS レコードを検索したときに、最初のクエリーが出力されないことを意味しています。
.SH ファイル
.sp
.ne 2
.mk
.na
\fB\fB/etc/resolv.conf\fR\fR
.ad
.sp .6
.RS 4n
リゾルバ構成ファイル
.RE

.sp
.ne 2
.mk
.na
\fB\fB${HOME}/.digrc\fR\fR
.ad
.sp .6
.RS 4n
ユーザー定義構成ファイル
.RE

.SH 属性
.sp
.LP
属性についての詳細は、マニュアルページの \fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件network/dns/bind
_
インタフェースの安定性流動的
.TE

.SH 関連項目
.sp
.LP
\fBdnssec-keygen\fR(8), \fBhost\fR(8), \fBnamed\fR(8), \fBnslookup\fR(8), \fBattributes\fR(5)
.sp
.LP
\fIRFC 1035\fR
.sp
.LP
『BIND 9 \fIAdministrator's Reference Manual\fR』を参照してください。このマニュアルページの発行日付時点で、このドキュメントは https://www.isc.org/software/bind/documentation から利用できます。
.SH 使用上の留意点
.sp
.LP
クエリーオプションが多すぎる可能性があります。
.SH 注意事項
.sp
.LP
\fBnslookup\fR(8) および \fBdig\fR で、「Not Implemented」が \fBNOTIMPL\fR ではなく \fBNOTIMP\fR と報告されるようになりました。これは、\fBNOTIMPL\fR を検索するスクリプトに影響します。
