'\" te
.\" Copyright (C) 2010 Internet Systems Consortium, Inc. ("ISC")
.\" Permission to use, copy, modify, and/or distribute this software for any purpose  with or without fee is hereby granted, provided that the above copyright notice  and this permission notice appear in all copies.  THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL,  DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING  FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE  USE OR PERFORMANCE OF THIS SOFTWARE.
.\" Portions Copyright (c) 2010, Sun Microsystems, Inc. All Rights Reserved.
.TH dnssec-keygen 8 "2010 年 1 月 11 日" "SunOS 5.12" "システム管理コマンド"
.SH 名前
dnssec-keygen \- DNSSEC 鍵生成ツール
.SH 形式
.LP
.nf
\fBdnssec-keygen\fR \fB-a\fR \fIalgorithm\fR \fB-b\fR \fIkeysize\fR \fB-n\fR \fInametype\fR [\fB-ehk\fR] 
     [\fB-c\fR \fIclass\fR] [\fB-f\fR \fIflag\fR] [\fB-g\fR \fIgenerator\fR] [\fB-p\fR \fIprotocol\fR] 
     [\fB-r\fR \fIrandomdev\fR] [\fB-s\fR \fIstrength\fR] [\fB-t\fR \fItype\fR] [\fB-v\fR \fIlevel\fR] \fIname\fR
.fi

.SH 機能説明
.sp
.LP
\fBdnssec-keygen\fR ユーティリティーは、RFC 2535 および RFC 4034 で定義されている DNSSEC (Secure DNS) の鍵を生成します。また、RFC 2845 で定義されている TSIG (Transaction Signatures) で使用する鍵も生成します。
.SH オプション
.sp
.LP
サポートしているオプションは、次のとおりです。
.sp
.ne 2
.mk
.na
\fB\fB-a\fR \fIalgorithm\fR\fR
.ad
.sp .6
.RS 4n
暗号化アルゴリズムを選択します。algorithm の値は、RSAMD5 (RSA) または RSASHA1、DSA、NSEC3RSASHA1、NSEC3DSA、\fBDH\fR (Diffie-Hellman)、HMAC-MD5 のいずれかにする必要があります。これらの値は大文字と小文字が区別されません。
.sp
DNSSEC の場合、RSASHA1 は実装が必須のアルゴリズムであるため、DSA が推奨されます。TSIG の場合は、HMAC-MD5 が必須です。
.LP
注 - 
.sp
.RS 2
HMAC-MD5 と DH では、\fB-k\fR フラグが自動的に設定されます。
.RE
.RE

.sp
.ne 2
.mk
.na
\fB\fB-b\fR \fIkeysize\fR\fR
.ad
.sp .6
.RS 4n
鍵のビット数を指定します。鍵サイズの選択は、使用されるアルゴリズムによって異なります。RSAMD5 鍵と RSASHA1 鍵は、512 - 2048 ビットの間にする必要があります。Diffie-Hellman 鍵は、128 - 4096 ビットの間にする必要があります。DSA 鍵は、512 - 1024 ビットの間で、ちょうど 64 の倍数になる値にする必要があります。HMAC-MD5 鍵は、1 - 512 ビットの間にする必要があります。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-c\fR \fIclass\fR\fR
.ad
.sp .6
.RS 4n
鍵を含む DNS レコードに、指定されたクラスが存在するべきであることを示します。指定されていない場合は、クラス IN が使用されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-e\fR\fR
.ad
.sp .6
.RS 4n
RSAMD5 鍵または RSASHA1 鍵を生成する場合は、大きな指数を使用します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-f\fR \fIflag\fR\fR
.ad
.sp .6
.RS 4n
指定されたフラグを KEY/DNSKEY レコードのフラグフィールドに設定します。認識されるフラグは KSK (Key Signing Key) DNSKEY のみです。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-g\fR \fIgenerator\fR\fR
.ad
.sp .6
.RS 4n
Diffie Hellman 鍵を生成する場合は、この \fIgenerator\fR を使用します。指定可能な値は 2 と 5 です。ジェネレータが指定されていない場合は、可能であれば RFC 2539 からの既知の素数が使用されます。それ以外の場合、デフォルトは 2 です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-h\fR\fR
.ad
.sp .6
.RS 4n
\fBdnssec-keygen\fR のオプションと引数の簡単なサマリーを出力します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-k\fR\fR
.ad
.sp .6
.RS 4n
DNSKEY レコードではなく KEY レコードを生成します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-n\fR \fInametype\fR\fR
.ad
.sp .6
.RS 4n
鍵の所有者型を指定します。\fInametype\fR の値は、\fBZONE\fR (DNSSEC ゾーン鍵 (KEY/DNSKEY) の場合)、\fBHOST\fR または \fBENTITY\fR (ホストに関連付けられた鍵 (KEY) の場合)、USER (ユーザーに関連付けられた鍵 (KEY) の場合)、\fBOTHER\fR (DNSKEY) のいずれかにする必要があります。これらの値は大文字と小文字が区別されません。デフォルトは、DNSKEY 生成用の ZONE です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-p\fR \fIprotocol\fR\fR
.ad
.sp .6
.RS 4n
生成された鍵のプロトコル値を設定します。\fIprotocol\fR 引数は 0 - 255 の数値です。デフォルトは 3 (DNSSEC) です。この引数に指定可能なのほか値は、RFC 2535 およびそれ以降のバージョンに記載されています。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-r\fR \fIrandomdev\fR\fR
.ad
.sp .6
.RS 4n
乱数発生元を指定します。オペレーティングシステムによって \fB/dev/random\fR または同等のデバイスが提供されていない場合、デフォルトの乱数発生元はキーボード入力です。\fIrandomdev\fR は、このデフォルトの代わりに使用される、ランダムデータを含む文字デバイスまたはファイルの名前を指定します。特殊な値「\fBkeyboard\fR」は、キーボード入力を使用する必要があることを示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR \fIstrength\fR\fR
.ad
.sp .6
.RS 4n
鍵の強さの値を指定します。\fIstrength\fR 引数は 0 - 15 の数値で、現時点では DNSSEC でその用途は定義されていません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR \fItype\fR\fR
.ad
.sp .6
.RS 4n
鍵の使用を示します。\fBtype\fR は、\fBAUTHCONF\fR、\fBNOAUTHCONF\fR、\fBNOAUTH\fR、\fBNOCONF\fR のいずれかにする必要があります。デフォルトは \fBAUTHCONF\fR です。\fBAUTH\fR はデータを認証する機能を、\fBCONF\fR はデータを暗号化する機能を示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-v\fR \fIlevel\fR\fR
.ad
.sp .6
.RS 4n
デバッグのレベルを設定します。
.RE

.SH 生成される鍵
.sp
.LP
\fBdnssec-keygen\fR が正常に完了すると、\fBK\fInnnn\fR.+\fIaaa\fR+\fIiiiii\fR\fR の形式の文字列が標準出力に表示されます。これは、生成された鍵の識別文字列です。
.RS +4
.TP
.ie t \(bu
.el o
\fInnnn\fR は鍵名です。
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fIaaa\fR はアルゴリズムの数値表現です。
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fIiiiii\fR は鍵識別子 (またはフットプリント) です。
.RE
.sp
.LP
\fBdnssec-keygen\fR ユーティリティーは、出力された文字列に基づいた名前を持つ 2 つのファイルを作成します。 
.RS +4
.TP
.ie t \(bu
.el o
\fBK\fR\fInnnn\fR.+\fIaaa\fR+\fIiiiii\fR.\fBkey\fR には公開鍵が含まれます。
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fBK\fR\fInnnn\fR.+\fIaaa\fR+\fIiiiii\fR.\fBprivate\fR には秘密鍵が含まれます。
.RE
.sp
.LP
\fB\&.key\fR ファイルには、ゾーンファイルに (直接、または \fB$INCLUDE\fR 文を使用して) 挿入できる DNS \fBKEY\fR レコードが含まれます。
.sp
.LP
\fB\&.private\fR ファイルには、アルゴリズムに固有のフィールドが含まれます。セキュリティー上の理由から、このファイルには一般的な読み取り権はありません。
.sp
.LP
公開鍵と秘密鍵が同じである場合でも、HMAC-MD5 などの対称暗号化アルゴリズム用に \fB\&.key\fR ファイルと \fB\&.private\fR ファイルの両方が生成されます。
.SH 使用例
.LP
\fB例 1 \fR768 ビットの DSA 鍵の生成
.sp
.LP
ドメイン \fBexample.com\fR 用に 768 ビットの DSA 鍵を生成するには、次のコマンドを発行します。

.sp
.in +2
.nf
dnssec-keygen -a DSA -b 768 -n ZONE example.com
.fi
.in -2
.sp

.sp
.LP
このコマンドは、次の形式の文字列を出力します。

.sp
.in +2
.nf
Kexample.com.+003+26160
.fi
.in -2
.sp

.sp
.LP
次のファイルが作成されます。

.sp
.in +2
.nf
Kexample.com.+003+26160.key
Kexample.com.+003+26160.private
.fi
.in -2
.sp

.SH 属性
.sp
.LP
属性についての詳細は、マニュアルページの \fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件service/network/dns/bind
_
インタフェースの安定性流動的
.TE

.SH 関連項目
.sp
.LP
\fBdnssec-signzone\fR(8), \fBattributes\fR(5)
.sp
.LP
\fIRFC 2539\fR、\fIRFC 2845\fR、\fIRFC 4033\fR
.sp
.LP
『BIND 9 \fIAdministrator's Reference Manual\fR』を参照してください。このマニュアルページの発行日付時点で、このドキュメントは https://www.isc.org/software/bind/documentation から利用できます。
