'\" te
.\" Copyright (C) 2010 Internet Systems Consortium, Inc. ("ISC")
.\" Permission to use, copy, modify, and/or distribute this software for any purpose  with or without fee is hereby granted, provided that the above copyright notice  and this permission notice appear in all copies.  THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL,  DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING  FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE  USE OR PERFORMANCE OF THIS SOFTWARE.
.\" Portions Copyright (c) 2010, Sun Microsystems, Inc. All Rights Reserved.
.TH dnssec-keyfromlabel 8 "2010 年 1 月 11 日" "SunOS 5.12" "システム管理コマンド"
.SH 名前
dnssec-keyfromlabel \- DNSSEC 鍵生成ツール
.SH 形式
.LP
.nf
\fBdnssec-keyfromlabel\fR \fB-a\fR \fIalgorithm\fR \fB-l\fR \fIlabel\fR [\fB-c\fR \fIclass\fR] [\fB-f\fR \fIflag\fR] [\fB-k\fR]
     [\fB-n\fR \fInametype\fR] [\fB-p\fR \fIprotocol\fR] [\fB-t\fR \fItype\fR] [\fB-v\fR \fIlevel\fR] \fIname\fR
.fi

.SH 機能説明
.sp
.LP
\fBdnssec-keyfromlabel\fR は、指定されたラベルを含む鍵を暗号化ハードウェアデバイスから取得し、RFC 2535 および RFC 4034 で定義されている DNSSEC (Secure DNS) の鍵ファイルを作成します。
.SH オプション
.sp
.LP
サポートしているオプションは、次のとおりです。
.sp
.ne 2
.mk
.na
\fB\fB-a\fR \fIalgorithm\fR\fR
.ad
.sp .6
.RS 4n
暗号化アルゴリズムを選択します。\fIalgorithm\fR の値は、\fBRSAMD5\fR (RSA) または \fBRSASHA1\fR、\fBDSA\fR、\fBNSEC3RSASHA1\fR、\fBNSEC3DSA\fR、\fBDH\fR (Diffie-Hellman) のいずれかにする必要があります。これらの値は大文字と小文字が区別されません。
.sp
\fBDNSSEC\fR の場合、\fBRSASHA1\fR は実装が必須のアルゴリズムであるため、DSA が推奨されることに注意してください。また、\fBDH\fR では \fB-k\fR フラグが自動的に設定されることにも注意してください。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-l\fR \fIlabel\fR \fR
.ad
.sp .6
.RS 4n
暗号化ハードウェア (PKCS#11) デバイス内の鍵のラベルを指定します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-n\fR \fInametype\fR\fR
.ad
.sp .6
.RS 4n
鍵の所有者型を指定します。\fInametype\fR の値は、\fBZONE\fR (\fBDNSSEC\fR ゾーン鍵 (\fBKEY\fR/\fBDNSKEY\fR) の場合)、\fBHOST\fR または \fBENTITY\fR (ホストに関連付けられた鍵 (\fBKEY\fR) の場合)、\fBUSER\fR (ユーザーに関連付けられた鍵 (\fBKEY\fR) の場合)、\fBOTHER\fR (\fBDNSKEY\fR) のいずれかにする必要があります。これらの値は大文字と小文字が区別されません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-c\fR \fIclass\fR\fR
.ad
.sp .6
.RS 4n
鍵を含む DNS レコードに、指定されたクラスが存在するべきであることを示します。指定されていない場合は、クラス \fBIN\fR が使用されます。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-f\fR \fIflag\fR\fR
.ad
.sp .6
.RS 4n
指定されたフラグを \fBKEY\fR/\fBDNSKEY\fR レコードのフラグフィールドに設定します。認識されるフラグは \fBKSK\fR (Key Signing Key) \fBDNSKEY\fR のみです。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-h\fR\fR
.ad
.sp .6
.RS 4n
\fBdnssec-keyfromlabel\fR のオプションと引数の簡単なサマリーを表示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-k\fR \fI\fR\fR
.ad
.sp .6
.RS 4n
\fBDNSKEY\fR レコードではなく \fBKEY\fR レコードを生成します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-p\fR \fIprotocol\fR\fR
.ad
.sp .6
.RS 4n
生成された鍵のプロトコル値を設定します。プロトコルは 0 - 255 の数値です。デフォルトは \fB3\fR (\fBDNSSEC\fR) です。この引数に指定可能なほかの値は、RFC 2535 およびそれ以降のバージョンに記載されています。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR \fItype\fR\fR
.ad
.sp .6
.RS 4n
鍵の使用を示します。\fItype\fR は、\fBAUTHCONF\fR、\fBNOAUTHCONF\fR、\fBNOAUTH\fR、\fBNOCONF\fR のいずれかにする必要があります。デフォルトは \fBAUTHCONF\fR です。\fBAUTH\fR はデータを認証する機能を、\fBCONF\fR はデータを暗号化する機能を示します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-v\fR \fIlevel\fR\fR
.ad
.sp .6
.RS 4n
デバッグのレベルを設定します。
.RE

.SH 生成される鍵ファイル
.sp
.LP
\fBdnssec-keyfromlabel\fR が正常に完了すると、\fBK\fInnnn\fR.+\fIaaa\fR+\fIiiiii\fR\fR の形式の文字列が標準出力に表示されます。これは生成された鍵ファイルの識別文字列で、次の内容を示します。
.RS +4
.TP
.ie t \(bu
.el o
\fInnnn\fR は鍵名です。
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fIaaa\fR はアルゴリズムの数値表現です。
.RE
.RS +4
.TP
.ie t \(bu
.el o
\fIiiiii\fR は鍵識別子 (またはフットプリント) です。
.RE
.sp
.LP
\fBdnssec-keyfromlabel\fR は、表示された文字列に基づいた名前を持つ 2 つのファイルを作成します。\fBK\fInnnn\fR.+\fIaaa\fR+\fIiiiii\fR.key\fR には公開鍵が、\fBK\fInnnn\fR.+\fI aaa\fR+\fIiiiii\fR.private\fR には秘密鍵が含まれます。
.sp
.LP
最初のファイルには、ゾーンファイルに (直接、または \fB$INCLUDE\fR 文を使用して) 挿入できる \fBDNS\fR \fBKEY\fR レコードが含まれます。
.sp
.LP
2 番目のファイルには、アルゴリズムに固有のフィールドが含まれます。セキュリティー上の理由から、このファイルには一般的な読み取り権はありません。
.SH 属性
.sp
.LP
属性についての詳細は、マニュアルページの \fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件service/network/dns/bind
_
インタフェースの安定性流動的
.TE

.SH 関連項目
.sp
.LP
\fBdnssec-keygen\fR(8), \fBdnssec-signzone\fR(8), \fBattributes\fR(5)
.sp
.LP
\fIRFC 2539\fR、\fIRFC 2845\fR、\fIRFC 4033\fR
.sp
.LP
『BIND 9 \fIAdministrator's Reference Manual\fR』を参照してください。このマニュアルページの発行日付時点で、このドキュメントは https://www.isc.org/software/bind/documentation から利用できます。
