'\" te
.\" Copyright (C) 2010 Internet Systems Consortium, Inc. ("ISC")
.\" Permission to use, copy, modify, and/or distribute this software for any purpose  with or without fee is hereby granted, provided that the above copyright notice  and this permission notice appear in all copies.  THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL,  DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING  FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE  USE OR PERFORMANCE OF THIS SOFTWARE.
.\" Portions Copyright (c) 2010, Sun Microsystems, Inc. All Rights Reserved.
.TH dnssec-dsfromkey 8 "2010 年 1 月 11 日" "SunOS 5.12" "システム管理コマンド"
.SH 名前
dnssec-dsfromkey \- DNSSEC DS RR 生成ツール
.SH 形式
.LP
.nf
\fBdnssec-dsfromkey\fR [\fB-v\fR \fIlevel\fR] [\fB-1\fR] [\fB-2\fR] [\fB-a\fR \fIalg\fR] \fIkeyfile\fR
.fi

.LP
.nf
\fBdnssec-dsfromkey\fR \fB-s\fR [\fB-v\fR \fIlevel\fR] [\fB-1\fR] [\fB-2\fR] [\fB-a\fR \fIalg\fR] [\fB-c\fR \fIclass\fR]
     [\fB-d\fR \fIdir\fR] \fIkeyfile\fR
.fi

.SH 機能説明
.sp
.LP
\fBdnssec-dsfromkey\fR
.SH オプション
.sp
.LP
サポートしているオプションは、次のとおりです。
.sp
.ne 2
.mk
.na
\fB\fB-1\fR\fR
.ad
.sp .6
.RS 4n
ダイジェストアルゴリズムとして \fBSHA-1\fR を使用します。デフォルトでは、\fBSHA-1\fR と \fBSHA-256\fR の両方を使用します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-2\fR\fR
.ad
.sp .6
.RS 4n
ダイジェストアルゴリズムとして SHA-256 を使用します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-a\fR \fIalgorithm\fR\fR
.ad
.sp .6
.RS 4n
ダイジェストアルゴリズムを選択します。\fIalgorithm\fR の値は、\fBSHA-1\fR (\fBSHA1\fR) または \fBSHA-256\fR (\fBSHA256\fR) のいずれかにする必要があります。これらの値は大文字と小文字が区別されません。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-v\fR \fIlevel\fR\fR
.ad
.sp .6
.RS 4n
デバッグのレベルを設定します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR\fR
.ad
.sp .6
.RS 4n
鍵セットモード: 鍵ファイル名の代わりに、鍵セットファイルの DNS ドメイン名が引数になります。\fB-c\fR オプションと \fB-d\fR オプションは、このモードでのみ有効です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-c\fR \fIclass\fR\fR
.ad
.sp .6
.RS 4n
DNS クラスを指定します (デフォルトは \fBIN\fR)。これは鍵セットモードでのみ有効です。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-d\fR \fIdirectory\fR\fR
.ad
.sp .6
.RS 4n
directory ディレクトリ内の鍵セットファイルを検索します。鍵セットモードでないときは無視されます。
.RE

.SH 使用例
.sp
.LP
\fBKexample.com.+003+26160\fR の鍵ファイル名から SHA-256 DS RR を作成するには、次のようなコマンドを使用します。
.sp
.in +2
.nf
# \fBdnssec-dsfromkey -2 Kexample.com.+003+26160\fR
.fi
.in -2
.sp

.sp
.LP
このコマンドによって、次のような出力が生成されます。
.sp
.in +2
.nf
example.com. IN DS 26160 5 2
3A1EADA7A74B8D0BA86726B0C227AA85AB8BBD2B2004F41A868A54F0
C5EA0B94
.fi
.in -2
.sp

.SH ファイル
.sp
.LP
鍵ファイルは、鍵 ID \fBK\fR\fInnnn\fR.+\fIaaa\fR+\fIiiiii\fR、または完全なファイル名 \fBK\fInnnn\fR.+\fIaaa\fR+\fIiiiii\fR.key\fR によって指定できます。これらの鍵は、\fBdnssec-keygen\fR(8) によって生成されます。
.sp
.LP
鍵セットファイル名は、ディレクトリ、文字列 \fBkeyset-\fR、および \fIdnsname\fR から作成されます。
.SH 属性
.sp
.LP
属性についての詳細は、マニュアルページの \fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件service/network/dns/bind
_
インタフェースの安定性流動的
.TE

.SH 関連項目
.sp
.LP
\fBdnssec-keygen\fR(8), \fBdnssec-signzone\fR(8), \fBattributes\fR(5)
.sp
.LP
\fIRFC 3658\fR、\fIRFC 4509\fR
.sp
.LP
『BIND 9 \fIAdministrator's Reference Manual\fR』を参照してください。このマニュアルページの発行日付時点で、このドキュメントは https://www.isc.org/software/bind/documentation から利用できます。
.SH 注意
.sp
.LP
鍵ファイルのエラーにより、ファイルが存在する場合でも「ファイルが見つかりません」というメッセージが生成されることがあります。
