#
# Copyright (c) 2015, 2016, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice (including the next
# paragraph) shall be included in all copies or substantial portions of the
# Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
#
###############################################################################
#
#  Makefile.rules - Rules commonly shared among kernel modules
#
###############################################################################

#TOP:sh=hg root

# Are we doing a debug build? if so, make sure to use the debug proto path.
# $(BUILD_DEBUG:yes=$(POUND_SIGN)) PROTODIR = $(PROTODIR_DEBUG)

# defines unique to kernel modules
# Note that the following paths are what should be expected.
# CTFCONVERT = /opt/onbld/bin/$(MACH)/ctfconvert
# CTFMERGE = /opt/onbld/bin/$(MACH)/ctfmerge
CTFCONVERT	= ctfconvert
CTFMERGE	= ctfmerge
CTFCVTFLAGS	= -i -L VERSION
# XXXX Need a better label.
CTFMERGE_LABEL	= -l 'SunOS Development'

#
# Paths to install locations
# These are selected by the driver and passed back as part of the
# driver's Makefile "ROOTMODULE" path.
# XXXX Need to find a way to remove the hard-code for MACH64_i386.
#

ROOT_DRV_DIR	= /kernel/drv/$(MACH64_i386)
ROOT_MISC_DIR	= /kernel/misc/$(MACH64_i386)
ROOT_MDB_DIR	= /usr/lib/mdb/kvm/$(MACH64_i386)
ROOT_KMOD_DIR	= /kernel/kmdb/$(MACH64_i386)
ROOT_MAN_DIR	= /usr/share/man

MANTARGET	= $(ROOT_MAN_DIR)/$(MANSECTION)
