'\" te
.TH firefox 1 "10 Jul 2008" "SunOS 5.12" "User Commands"
.SH "NAME"
firefox \- Firefox for 
Oracle Solaris Desktop
.SH "SYNOPSIS"
.PP
\fBfirefox\fR [\fBoptions \&.\&.\&. \fR] [\fB\fIurl\fR\fR]
.SH "DESCRIPTION"
.PP
Firefox is a free, open-source web browser based on the Mozilla codebase\&.
It is small, fast and easy to use, and offers many advantages over other browsers,
such as the ability to block pop-up windows\&.
.SH "OPTIONS"
.PP
The following options are supported:
.sp
.ne 2
.mk
\fB-\fBheight \fIvalue\fR\fR\fR
.in +24n
.rt
Set the height of startup window to \fIvalue\fR\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBh \fRor -\fBhelp \fR\fR
.in +24n
.rt
Display the help message\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBwidth \fIvalue\fR\fR\fR
.in +24n
.rt
Set the width of startup window to \fIvalue\fR\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBv \fRor -\fBversion \fR\fR
.in +24n
.rt
Display the version message\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBP \fIprofile\fR\fR\fR
.in +24n
.rt
Start with the profile named: \fIprofile\fR\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBProfileManager \fR\fR
.in +24n
.rt
Start with profile manager\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBUILocale \fIlocale\fR\fR\fR
.in +24n
.rt
Start with the UI Locale listed: \fIlocale\fR\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBsafe-mode \fR\fR
.in +24n
.rt
Disables extensions and themes for this session\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBjsconsole \fR\fR
.in +24n
.rt
Open the JavaScript console\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBbrowser \fR\fR
.in +24n
.rt
Open a browser window\&.
.sp
.sp 1
.in -24n
.sp
.ne 2
.mk
\fB-\fBsetDefaultBrowser \fR\fR
.in +24n
.rt
Set this app as the default browser\&.
.sp
.sp 1
.in -24n
.SH "EXAMPLES"
.PP
\fBExample 1: Launching Firefox\fR
.PP
.PP
.nf
example% \fBfirefox \fR
.PP
When logged via 'ssh -X', dbus-launch is advised to use:
.PP
example% \fBdbus-launch firefox \fR
.fi
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.sp
.ne 2
.mk
\fB\fB0\fR\fR
.in +9n
.rt
Application
exited successfully
.sp
.sp 1
.in -9n
.sp
.ne 2
.mk
\fB\fB1\fR\fR
.in +9n
.rt
Application
exited with failure
.sp
.sp 1
.in -9n
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
\fB\fB/usr/bin/firefox\fR \fR
.sp .6
.in +4
Executable for Firefox application
.sp
.sp 1
.in -4
.sp
.ne 2
.mk
\fB\fB$HOME/\&.mozilla/firefox\fR \fR
.sp .6
.in +4
User configuration files for Firefox
.sp
.sp 1
.in -4
.SH "SEE ALSO"
.PP
For more information about firefox, please refer to
\fBhttp://www\&.mozilla\&.org/firefox\fR
.PP
Refer to Help->Firefox Help for more information\&.
.SH "NOTES"
.PP
Updated by Evan Yan, Sun Microsystems Inc\&., 2008\&. 
...\" created by instant / solbook-to-man, Tue 27 Jan 2015, 17:22
