/*
 * Copyright (c) 2003, 2011, Oracle and/or its affiliates. All rights reserved.
 *
 * U.S. Government Rights - Commercial software. Government users are subject
 * to the Sun Microsystems, Inc. standard license agreement and applicable
 * provisions of the FAR and its supplements.
 *
 *
 * This distribution may include materials developed by third parties. Sun,
 * Sun Microsystems, the Sun logo and Solaris are trademarks or registered
 * trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
 *
 */
/*
 * Note: this file originally auto-generated by mib2c using
 * 	: mib2c.scalar.conf,v 1.5 2002/07/18 14:18:52 dts12 Exp $
 */
#ifndef SUNHOSTPERF_H
#define	SUNHOSTPERF_H

/* function declarations */
void init_sunHostPerf(void);
Netsnmp_Node_Handler get_rsNiceModeTime;
Netsnmp_Node_Handler get_rsIdleModeTime;
Netsnmp_Node_Handler get_rsVSwapIn;
Netsnmp_Node_Handler get_rsDiskXfer1;
Netsnmp_Node_Handler get_rsDiskXfer2;
Netsnmp_Node_Handler get_rsIfInErrors;
Netsnmp_Node_Handler get_rsDiskXfer3;
Netsnmp_Node_Handler get_rsVSwapOut;
Netsnmp_Node_Handler get_rsVPagesOut;
Netsnmp_Node_Handler get_rsDiskXfer4;
Netsnmp_Node_Handler get_rsSystemProcessTime;
Netsnmp_Node_Handler get_rsIfInPackets;
Netsnmp_Node_Handler get_rsVPagesIn;
Netsnmp_Node_Handler get_rsIfOutErrors;
Netsnmp_Node_Handler get_rsUserProcessTime;
Netsnmp_Node_Handler get_rsIfOutPackets;
Netsnmp_Node_Handler get_rsVIntr;
Netsnmp_Node_Handler get_rsIfCollisions;

#endif /* SUNHOSTPERF_H */
