/*
 * Copyright (c) 2003, 2011, Oracle and/or its affiliates. All rights reserved.
 *
 * U.S. Government Rights - Commercial software. Government users are subject
 * to the Sun Microsystems, Inc. standard license agreement and applicable
 * provisions of the FAR and its supplements.
 *
 *
 * This distribution may include materials developed by third parties. Sun,
 * Sun Microsystems, the Sun logo and Solaris are trademarks or registered
 * trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
 *
 */
/*
 * Note: this file originally auto-generated by mib2c using
 * 	: mib2c.scalar.conf,v 1.5 2002/07/18 14:18:52 dts12 Exp $
 */
#ifndef	SUNSYSTEM_H
#define	SUNSYSTEM_H

/* function declarations */
void init_sunSystem(void);
Netsnmp_Node_Handler get_motd;
Netsnmp_Node_Handler get_hostID;
Netsnmp_Node_Handler get_agentDescr;
Netsnmp_Node_Handler get_unixTime;

#define	AGENT_DESCR "Sun Microsystems SNMP Agent"

#endif /* SUNSYSTEM_H */
