.TH yelp 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
yelp, gnome-help \- GNOME help browser
.SH "SYNOPSIS"
.PP
.B "yelp\fR [\fB\-\-private-session\fR] [\fB\-\-with-cache-dir=\fIstring\fR\fR] [\fB\fIgnome-std-options\fR\fR] \fB\fIurl\fR"
.SH "DESCRIPTION"
.PP
The GNOME help browser is a utility that allows users to view documentation
for GNOME in several formats including man pages, Mallard, HTML, SGML(DocBook),
and GNU info files\&.
.SH "OPTIONS"
.PP
The following options are supported:
.TP 32
.B \-\-private-session
Use a private session\&.
.TP 32
\fB\-\-with-cache-dir=\fIdirectory\fR\fR
Specify which cache \fIdirectory\fR to use\&.
.TP 32
.I gnome-std-options
Standard options available for use with most GNOME applications\&.  See
.BR gnome-std-options (7)
for more information\&.
.SH "OPERANDS"
.PP
The following operands are supported:
.TP 16
.I url
This allows you to view a specific help document by providing the complete
\fIurl\fR to the documentation that you wish to view\&.
.sp
If \fIurl\fR starts with "ghelp:",
\fByelp\fR opens the help document within
\fBghelp\fR\&.
.sp
If \fIurl\fR does not start with "ghelp:",
\fByelp\fR attempts to launch a default Internet browser window
and display the contents of the help document within this browser window\&.
.SH "EXTENDED DESCRIPTION"
.PP
Refer to the GNOME Documentation Project webpages:
.PP
.B "https://wiki\&.gnome\&.org/DocumentationProject/"
.SH "EXAMPLES"
.PP
.B "Example 1: Launching GNOME Help Browser"
.PP
.PP
.nf
example% \fByelp\fR
.fi
.PP
.B "Example 2: Launching GNOME Help Browser and loading the help information for the GNOME Accessibility guide\&."
.PP
.PP
.nf
example% \fByelp ghelp:///usr/share/gnome/help/gnome-access-guide/C/gnome-access-guide\&.xml\fR
.fi
.PP
.B "Example 3: Launching GNOME Help Browser with a standard Internet URL"
.PP
.PP
.nf
example% \fByelp \fBhttp://www\&.gnome\&.org\fR\fR
.fi
.PP
The default Internet browser is launched (unless a browser is already
running), and this URL is displayed within the browser window\&.
.SH "ENVIRONMENT VARIABLES"
.PP
See \fBenviron\fR(7) for descriptions of the following environment
variables:
.TP 24
.B "INFOPATH"
Location of GNU Info files\&.
.TP 24
.B "MANPATH"
Location of man pages\&.
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.TP 9
.B 0
Application exited successfully
.TP 9
.B >0
Application exited with failure
.SH "SEE ALSO"
.PP
Latest version of the \fIGNOME Desktop User Guide\fR
for your platform\&.
.PP
.BR attributes (7),
.BR environ (7),
.BR gnome-std-options (7)
.SH "NOTES"
.PP
\fByelp\fR and \fBgnome-help\fR are the same application\&.
.PP
Written by Matt Keenan, Sun Microsystems Inc\&., 2003, 2007\&.
