'\" te
.TH gnome-interfaces 7 "3 Jan 2016"
.SH "NAME"
gnome-interfaces \- GNOME interface classifications
.SH "DESCRIPTION"
.PP
This page describes the interface classifications for items shipped
with the GNOME desktop\&. For the definitions of the interface classifications,
see \fBattributes\fR(7)\&.
.PP
Those wishing to integrate with the GNOME desktop are recommended to depend on
interfaces marked as Committed\&.  These interfaces will not break after upgrade\&.
The set of Committed interfaces is a subset of the GNOME Platform libraries
(plus additional interfaces such as FreeDesktop interfaces and pkg-config)\&.
.PP
Oracle believes that the list of Committed interfaces is suitable
for writing a great GTK+ based application\&.  Examples of programs that depend
only on these interfaces include: GIMP, Firefox, and Thunderbird\&.
.PP
Note that when you build software, any configure script may use the
\fBpkg-config\fR to identify what libraries are installed to
the system\&.  Solaris includes pc files for non-Committed interfaces in
\fB/usr/lib/pkgconfig\fR, so be aware of the commitment
level of any dependencies you may be using\&.  Some such dependencies are
optional and configure options can disable them\&.  It is recommended that
non-Committed interfaces are not enabled if you require stability\&.
.PP
GNOME Platform libraries have an API/ABI stability guarantee from
the external GNOME community\&.  While it is unlikely that non-Committed
interfaces in the GNOME Platform would break after upgrade, Sun makes no
guarantee that these interfaces have any stability\&.  Refer to the
GNOME community for a list of Platform libraries for the version of GNOME
being used\&.  Use non-Committed interfaces at your own risk\&.
.PP
GNOME Desktop interfaces have no stability guarantee and are intended only
for use for programs provided by the GNOME community\&.  Xiph\&.org interfaces
also have no stability guarantee\&.
.PP
Instructions on how to integrate with the GNOME panel menu, the MIME
database, and icon integration are discussed in the GNOME System
Administration Guide\&.
.PP
You must install the GNOME development packages for access to developer
applications and API documentation\&. API documentation for GNOME interfaces
can be found in related manpages and the API documentation installed to
/usr/share/gtk-doc in HTML format\&.
.PP
The interfaces listed below ship with API documentation\&.  Refer to the specific
manpage for details\&.  GNOME interfaces which are not listed in the table below
should be considered Volatile, even if the interfaces have gtk-docs installed
in \fB/usr/share/gtk-doc\fR\&.  Interfaces in Committed libraries
that are not documented in the man page or referenced gtk-doc API documentation
should be considered Volatile\&.
.sp
.TS
tab() allbox;
lw(2.750000i)| lw(2.750000i).
INTERFACE NAMECLASSIFICATION
\fBgdk-pixbuf-csource\fRCommitted GNOME Platform
\fBgdk-pixbuf-query-loaders\fRCommitted GNOME Platform
\fBglib-genmarshal\fRCommitted GNOME Platform
\fBglib-gettextize\fRCommitted GNOME Platform
\fBglib-mkenums\fRCommitted GNOME Platform
\fBgobject-query\fRCommitted GNOME Platform
\fBgtk-builder-convert\fRCommitted GNOME Platform
\fBgtk-query-immodules-2\&.0\fRCommitted GNOME Platform
\fBgtk-update-icon-cache\fRCommitted GNOME Platform
\fBpkg-config\fRCommitted
\fBlibIDL-2\fRVolatile GNOME Platform
\fBlibORBit-2\fRVolatile GNOME Platform
\fBlibORBitCosNaming-2\fRVolatile GNOME Platform
\fBlibart_lgpl_2\fRVolatile GNOME Platform
\fBlibatk-1\&.0\fRCommitted GNOME Platform
\fBlibaudiofile\fRVolatile GNOME Platform
\fBlibbonobo-2\fRVolatile GNOME Platform
\fBlibbonobo-activation\fRVolatile GNOME Platform
\fBlibbonoboui-2\fRVolatile GNOME Platform
\fBlibcairo\fRUncommitted FreeDesktop
\fBlibcspi\fRCommitted GNOME Platform
T{
\fB/usr/include/at-spi-1\&.0/libspi/Accessibility\&.h\fR
T}Volatile GNOME Platform
T{
\fB/usr/lib/python2\&.4/site-packages/pyatspi/*\fR
T}Volatile GNOME Platform
\fBat-spi\fRCommitted GNOME Platform
\fBlibesd\fRVolatile GNOME Platform
\fBlibgailutil\fRVolatile GNOME Platform
\fBlibgconf-2\fRVolatile GNOME Platform
\fBlibgdk-x11-2\&.0\fRCommitted GNOME Platform
\fBlibgdk_pixbuf-2\&.0\fRCommitted GNOME Platform
\fBlibgio-2\&.0\fRVolatile GNOME Platform
\fBlibglade-2\&.0\fRVolatile GNOME Platform
\fBlibglib-2\&.0\fRCommitted GNOME Platform
\fBlibglibmm-2\&.4\fRUncommitted GNOME Platform
\fBlibgiomm-2\&.4\fRUncommitted GNOME Platform
\fBlibgmodule-2\&.0\fRCommitted GNOME Platform
\fBlibgthread-2\&.0\fRCommitted GNOME Platform
\fBlibgnome-2\fRVolatile GNOME Platform
\fBlibgnomecanvas-2\fRVolatile GNOME Platform
\fBlibgnome-desktop-2\fRVolatile GNOME Desktop
\fBlibgnomeprint-2\&.2\fRVolatile GNOME Desktop
\fBlibgnomeprintui-2\&.2\fRObsolete GNOME Desktop
\fBlibgnomeui-2\fRVolatile GNOME Platform
\fBlibgnomevfs-2\fRObsolete Volatile GNOME Platform
\fBlibgobject-2\&.0\fRCommitted GNOME Platform
\fBlibgstreamer-10\&.0\fRVolatile GNOME Desktop
\fBlibgstbase-10\&.0\fRVolatile GNOME Desktop
\fBlibgtk-x11-2\&.0\fRCommitted GNOME Platform
\fBlibogg\fRVolatile Xiph\&.org
\fBlibpanel-applet-2\fRVolatile GNOME Desktop
\fBlibpango-1\&.0\fRCommitted GNOME Platform
\fBlibpangoft2-1\&.0\fRCommitted GNOME Platform
\fBlibpangocairo-1\&.0\&.3\fRCommitted GNOME Platform
\fBibpangoxft-1\&.0\&.3\fRCommitted GNOME Platform
\fBlibpangox-1\&.0\fRCommitted GNOME Platform
\fBlibpopt\fRVolatile
\fBlibrsvg\fRVolatile GNOME Desktop
\fBlibvorbis\fRVolatile Xiph\&.org
\fBlibvte\fRVolatile GNOME Desktop
\fBgnome-vfs-mime-magic\fRObsolete Volatile GNOME Platform
\fBgnome-vfs\&.applications\fRObsolete Volatile GNOME Platform
\fBgnome-vfs\&.keys\fRObsolete Volatile GNOME Platform
\fBgnome-vfs\&.mime\fRObsolete Volatile GNOME Platform
\fBdefault\&.session\fRVolatile GNOME Desktop
\fB/usr/lib/pkgconfig\fRCommitted
\fB/usr/share/applications\fRCommitted FreeDesktop
\fB$HOME/\&.local/share/applications\fRCommitted FreeDesktop
\fB/usr/share/gdm/defaults\&.conf\fRVolatile
\fB/etc/X11/gdm/custom\&.conf\fRVolatile
\fB/usr/bin/update-mime-database\fRCommitted
\fB/usr/bin/update-desktop-database\fRCommitted
\fB/usr/bin/pango-querymodules\fRCommitted
\fB/usr/lib/libgtop\fRVolatile GNOME Platform
.TE
.sp
.SH "SEE ALSO"
.PP
\fBgdk-pixbuf-csource\fR(1),
\fBgdk-pixbuf-query-loaders\fR(1),
\fBgdm\fR(8),
\fBglib-genmarshal\fR(1),
\fBglib-gettextize\fR(1),
\fBglib-mkenums\fR(1),
\fBgobject-query\fR(1),
\fBgtk-builder-convert\fR(1),
\fBgtk-query-immodules-2\&.0\fR(1),
\fBgtk-update-icon-cache\fR(1),
\fBpango-querymodules\fR(1),
\fBpkg-config\fR(1),
\fBupdate-desktop-database\fR(1),
\fBupdate-mime-database\fR(1),
\fBlibIDL-2\fR(3lib),
\fBlibORBit-2\fR(3lib),
\fBlibORBitCosNaming-2\fR(3lib),
\fBlibart_lgpl_2\fR(3lib),
\fBlibatk-1\&.0\fR(3lib),
\fBlibaudiofile\fR(3lib),
\fBlibbonobo-2\fR(3lib),
\fBlibbonobo-activation\fR(3lib),
\fBlibbonoboui-2\fR(3lib),
\fBlibcairo\fR(3lib),
\fBlibcspi\fR(3lib),
\fBlibesd\fR(3lib),
\fBlibgailutil\fR(3lib),
\fBlibgconf-2\fR(3lib),
\fBlibgdk-x11-2\&.0\fR(3lib),
\fBlibgdk_pixbuf-2\&.0\fR(3lib),
\fBlibgio-2\&.0\fR(3lib),
\fBlibglade-2\&.0\fR(3lib),
\fBlibglib-2\&.0\fR(3lib),
\fBlibglibmm-2\&.4\fR(3lib),
\fBlibgiomm-2\&.4\fR(3lib),
\fBlibgnome-2\fR(3lib),
\fBlibgnome-desktop-2\fR(3lib),
\fBlibgnomecanvas-2\fR(3lib),
\fBlibgnomeprint-2-2\fR(3lib),
\fBlibgnomeprintui-2-2\fR(3lib),
\fBlibgnomeui-2\fR(3lib),
\fBlibgnomevfs-2\fR(3lib),
\fBlibgobject-2\&.0\fR(3lib),
\fBlibgstreamer-10\&.0\fR(3lib),
\fBlibgtk-x11-2\&.0\fR(3lib),
\fBlibogg\fR(3lib),
\fBlibpanel-applet-2\fR(3lib),
\fBlibpango-1\&.0\fR(3lib),
\fBlibpopt\fR(3lib),
\fBlibrsvg\fR(3lib),
\fBlibvorbis\fR(3lib),
\fBlibvte\fR(3lib),
\fBlibgtop\fR(3)
\fBattributes\fR(7),
\fBenviron\fR(7)
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(7)
for descriptions of the above attributes:
.PP
Latest version of the \fIGNOME Desktop System Administration Guide\fR for
your platform\&.
.PP
The following web resources are useful for learning more about the GNOME
desktop and its interfaces:
.PP
\fBhttp://www\&.gnome\&.org/\fR
.PP
\fBhttp://developer\&.gnome\&.org/\fR
.PP
\fBhttp://live\&.gnome\&.org/\fR
.PP
\fBhttp://www\&.gtkmm\&.org/\fR
.PP
\fBhttp://www\&.freedesktop\&.org/\fR
.PP
\fBhttp://www\&.xiph\&.org/\fR
.SH "NOTES"
.PP
Written by Brian Cameron and Matt Keenan, Sun Microsystems Inc\&., 2003, 2007, 2008\&.

