.\"
.\" Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
.\"
.\" logilab-astng.3
.\"
.TH logilab-astng 3 "30 Apr 2009"
.SH NAME
logilab-astng \- Python Abstract Syntax Tree New Generation
.SH DESCRIPTION
The
.I logilab-astng
The aim of this module is to provide a common base representation of 
python source code for projects such as pychecker, pyreverse, pylint.

.LP
It is governed by pylint's needs.  It extends class defined in the 
compiler.ast [1] module with some additional methods and attributes. 
Instance attributes are added by a builder object, which can either 
generate extended ast by visiting an existant ast tree or by inspecting 
living object. Methods are added by monkey patching ast classes.

.LP
Main modules are:
.LP

* nodes and scoped_nodes for more information about methods 
and attributes added to different node classes

.LP
* the manager contains a high level object to get astng trees 
from source files and living objects. It maintains a cache of 
previously constructed tree for quick access

.LP
* builder contains the class responsible to build astng trees


.LP

.SH FILES
.TP 2.2i
.B /usr/lib/python2.6/vendor-packages/logilab/astng
shared object library files

.SH AUTHORS
Sylvain Thenault (sylvain.thenault@logilab.fr)

.SH SUPPORT
python-projects@logilab.org

.SH SEE ALSO
.IR logilab-common (3),
.IR pylint (1),
