.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "OCT 2015"  ""


.SH NAME
.PP
docker\-network\-disconnect \- disconnect a container from a network


.SH SYNOPSIS
.PP
\fBdocker network disconnect\fP
[\fB\-\-help\fP]
[\fB\-\-force\fP]
NETWORK CONTAINER


.SH DESCRIPTION
.PP
Disconnects a container from a network.

.PP
.RS

.nf
  $ docker network disconnect multi\-host\-network container1

.fi
.RE


.SH OPTIONS
.PP
\fBNETWORK\fP
  Specify network name

.PP
\fBCONTAINER\fP
    Specify container name

.PP
\fB\-\-force\fP
  Force the container to disconnect from a network

.PP
\fB\-\-help\fP
  Print usage statement


.SH HISTORY
.PP
OCT 2015, created by Mary Anthony 
\[la]mary@docker.com\[ra]
