.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-start \- Start one or more containers


.SH SYNOPSIS
.PP
\fBdocker start\fP
[\fB\-a\fP|\fB\-\-attach\fP]
[\fB\-\-detach\-keys\fP[=\fI[]\fP]]
[\fB\-\-help\fP]
[\fB\-i\fP|\fB\-\-interactive\fP]
CONTAINER [CONTAINER...]


.SH DESCRIPTION
.PP
Start one or more containers.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-attach\fP=\fItrue\fP|\fIfalse\fP
   Attach container's STDOUT and STDERR and forward all signals to the
   process. The default is \fIfalse\fP.

.PP
\fB\-\-detach\-keys\fP=""
   Override the key sequence for detaching a container. Format is a single character \fB\fC[a\-Z]\fR or \fB\fCctrl\-<value>\fR where \fB\fC<value>\fR is one of: \fB\fCa\-z\fR, \fB\fC@\fR, \fB\fC^\fR, \fB\fC[\fR, \fB\fC,\fR or \fB\fC\_\fR.

.PP
\fB\-\-help\fP
  Print usage statement

.PP
\fB\-i\fP, \fB\-\-interactive\fP=\fItrue\fP|\fIfalse\fP
   Attach container's STDIN. The default is \fIfalse\fP.


.SH See also
.PP
\fBdocker\-stop(1)\fP to stop a container.


.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com)
based on docker.com source material and internal work.
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
