.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-pause \- Pause all processes within a container


.SH SYNOPSIS
.PP
\fBdocker pause\fP
CONTAINER [CONTAINER...]


.SH DESCRIPTION
.PP
The \fB\fCdocker pause\fR command uses the cgroups freezer to suspend all processes in
a container.  Traditionally when suspending a process the \fB\fCSIGSTOP\fR signal is
used, which is observable by the process being suspended. With the cgroups freezer
the process is unaware, and unable to capture, that it is being suspended,
and subsequently resumed.

.PP
See the 
\[la]https://www.kernel.org/doc/Documentation/cgroups/freezer-subsystem.txt\[ra] for
further details.


.SH OPTIONS
.PP
There are no available options.


.SH See also
.PP
\fBdocker\-unpause(1)\fP to unpause all processes within a container.


.SH HISTORY
.PP
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
