.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-restart \- Restart a container


.SH SYNOPSIS
.PP
\fBdocker restart\fP
[\fB\-\-help\fP]
[\fB\-t\fP|\fB\-\-time\fP[=\fI10\fP]]
CONTAINER [CONTAINER...]


.SH DESCRIPTION
.PP
Restart each container listed.


.SH OPTIONS
.PP
\fB\-\-help\fP
  Print usage statement

.PP
\fB\-t\fP, \fB\-\-time\fP=\fI10\fP
   Number of seconds to try to stop for before killing the container. Once killed it will then be restarted. Default is 10 seconds.


.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com)
based on docker.com source material and internal work.
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
