.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-wait \- Block until a container stops, then print its exit code.


.SH SYNOPSIS
.PP
\fBdocker wait\fP
[\fB\-\-help\fP]
CONTAINER [CONTAINER...]


.SH DESCRIPTION
.PP
Block until a container stops, then print its exit code.


.SH OPTIONS
.PP
\fB\-\-help\fP
  Print usage statement


.SH EXAMPLES
.PP
.RS

.nf
$ docker run \-d fedora sleep 99
079b83f558a2bc52ecad6b2a5de13622d584e6bb1aea058c11b36511e85e7622
$ docker wait 079b83f558a2bc
0

.fi
.RE


.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com)
based on docker.com source material and internal work.
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
