.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "FEBRUARY 2015"  ""


.SH NAME
.PP
docker\-ps \- List containers


.SH SYNOPSIS
.PP
\fBdocker ps\fP
[\fB\-a\fP|\fB\-\-all\fP]
[\fB\-f\fP|\fB\-\-filter\fP[=\fI[]\fP]]
[\fB\-\-format\fP=\fI"TEMPLATE"\fP]
[\fB\-\-help\fP]
[\fB\-l\fP|\fB\-\-latest\fP]
[\fB\-n\fP[=\fI\-1\fP]]
[\fB\-\-no\-trunc\fP]
[\fB\-q\fP|\fB\-\-quiet\fP]
[\fB\-s\fP|\fB\-\-size\fP]


.SH DESCRIPTION
.PP
List the containers in the local repository. By default this shows only
the running containers.


.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-all\fP=\fItrue\fP|\fIfalse\fP
   Show all containers. Only running containers are shown by default. The default is \fIfalse\fP.

.PP
\fB\-f\fP, \fB\-\-filter\fP=[]
   Filter output based on these conditions:
   \- exited=<int> an exit code of <int>
   \- label=<key> or label=<key>=<value>
   \- status=(created|restarting|running|paused|exited|dead)
   \- name=<string> a container's name
   \- id=<ID> a container's ID
   \- before=(<container-name>|<container-id>)
   \- since=(<container-name>|<container-id>)
   \- ancestor=(<image-name>[:tag]|<image-id>|
\[la]image@digest\[ra]) \- containers created from an image or a descendant.

.PP
\fB\-\-format\fP="\fITEMPLATE\fP"
   Pretty\-print containers using a Go template.
   Valid placeholders:
      .ID \- Container ID
      .Image \- Image ID
      .Command \- Quoted command
      .CreatedAt \- Time when the container was created.
      .RunningFor \- Elapsed time since the container was started.
      .Ports \- Exposed ports.
      .Status \- Container status.
      .Size \- Container disk size.
      .Labels \- All labels assigned to the container.
      .Label \- Value of a specific label for this container. For example \fB\fC{{.Label "com.docker.swarm.cpu"}}\fR

.PP
\fB\-\-help\fP
  Print usage statement

.PP
\fB\-l\fP, \fB\-\-latest\fP=\fItrue\fP|\fIfalse\fP
   Show only the latest created container (includes all states). The default is \fIfalse\fP.

.PP
\fB\-n\fP=\fI\-1\fP
   Show n last created containers (includes all states).

.PP
\fB\-\-no\-trunc\fP=\fItrue\fP|\fIfalse\fP
   Don't truncate output. The default is \fIfalse\fP.

.PP
\fB\-q\fP, \fB\-\-quiet\fP=\fItrue\fP|\fIfalse\fP
   Only display numeric IDs. The default is \fIfalse\fP.

.PP
\fB\-s\fP, \fB\-\-size\fP=\fItrue\fP|\fIfalse\fP
   Display total file sizes. The default is \fIfalse\fP.


.SH EXAMPLES

.SH Display all containers, including non\-running
.PP
.RS

.nf
# docker ps \-a
CONTAINER ID        IMAGE                 COMMAND                CREATED             STATUS      PORTS    NAMES
a87ecb4f327c        fedora:20             /bin/sh \-c #(nop) MA   20 minutes ago      Exit 0               desperate\_brattain
01946d9d34d8        vpavlin/rhel7:latest  /bin/sh \-c #(nop) MA   33 minutes ago      Exit 0               thirsty\_bell
c1d3b0166030        acffc0358b9e          /bin/sh \-c yum \-y up   2 weeks ago         Exit 1               determined\_torvalds
41d50ecd2f57        fedora:20             /bin/sh \-c #(nop) MA   2 weeks ago         Exit 0               drunk\_pike

.fi
.RE


.SH Display only IDs of all containers, including non\-running
.PP
.RS

.nf
# docker ps \-a \-q
a87ecb4f327c
01946d9d34d8
c1d3b0166030
41d50ecd2f57

.fi
.RE


.SH Display only IDs of all containers that have the name \fB\fCdetermined\_torvalds\fR
.PP
.RS

.nf
# docker ps \-a \-q \-\-filter=name=determined\_torvalds
c1d3b0166030

.fi
.RE


.SH Display containers with their commands
.PP
.RS

.nf
# docker ps \-\-format "{{.ID}}: {{.Command}}"
a87ecb4f327c: /bin/sh \-c #(nop) MA
01946d9d34d8: /bin/sh \-c #(nop) MA
c1d3b0166030: /bin/sh \-c yum \-y up
41d50ecd2f57: /bin/sh \-c #(nop) MA

.fi
.RE


.SH Display containers with their labels in a table
.PP
.RS

.nf
# docker ps \-\-format "table {{.ID}}\\t{{.Labels}}"
CONTAINER ID        LABELS
a87ecb4f327c        com.docker.swarm.node=ubuntu,com.docker.swarm.storage=ssd
01946d9d34d8
c1d3b0166030        com.docker.swarm.node=debian,com.docker.swarm.cpu=6
41d50ecd2f57        com.docker.swarm.node=fedora,com.docker.swarm.cpu=3,com.docker.swarm.storage=ssd

.fi
.RE


.SH Display containers with their node label in a table
.PP
.RS

.nf
# docker ps \-\-format 'table {{.ID}}\\t{{(.Label "com.docker.swarm.node")}}'
CONTAINER ID        NODE
a87ecb4f327c        ubuntu
01946d9d34d8
c1d3b0166030        debian
41d50ecd2f57        fedora

.fi
.RE


.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com)
based on docker.com source material and internal work.
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
August 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
November 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
February 2015, updated by André Martins 
\[la]martins@noironetworks.com\[ra]
