.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JULY 2015"  ""


.SH NAME
.PP
docker\-volume\-ls \- List all volumes


.SH SYNOPSIS
.PP
\fBdocker volume ls\fP
[\fB\-f\fP|\fB\-\-filter\fP[=\fIFILTER\fP]]
[\fB\-\-help\fP]
[\fB\-q\fP|\fB\-\-quiet\fP[=\fItrue\fP|\fIfalse\fP]]


.SH DESCRIPTION
.PP
Lists all the volumes Docker knows about. You can filter using the \fB\fC\-f\fR or \fB\fC\-\-filter\fR flag. The filtering format is a \fB\fCkey=value\fR pair. To specify more than one filter,  pass multiple flags (for example,  \fB\fC\-\-filter "foo=bar" \-\-filter "bif=baz"\fR)

.PP
There is a single supported filter \fB\fCdangling=value\fR which takes a boolean of \fB\fCtrue\fR or \fB\fCfalse\fR.


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-filter\fP=""
  Provide filter values (i.e. 'dangling=true')

.PP
\fB\-\-help\fP
  Print usage statement

.PP
\fB\-q\fP, \fB\-\-quiet\fP=\fItrue\fP|\fIfalse\fP
  Only display volume names


.SH HISTORY
.PP
July 2015, created by Brian Goff 
\[la]cpuguy83@gmail.com\[ra]
