.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-unpause \- Unpause all processes within a container


.SH SYNOPSIS
.PP
\fBdocker unpause\fP
CONTAINER [CONTAINER...]


.SH DESCRIPTION
.PP
The \fB\fCdocker unpause\fR command uses the cgroups freezer to un\-suspend all
processes in a container.

.PP
See the 
\[la]https://www.kernel.org/doc/Documentation/cgroups/freezer-subsystem.txt\[ra] for
further details.


.SH OPTIONS
.PP
There are no available options.


.SH See also
.PP
\fBdocker\-pause(1)\fP to pause all processes within a container.


.SH HISTORY
.PP
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
