.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-stop \- Stop a container by sending SIGTERM and then SIGKILL after a grace period


.SH SYNOPSIS
.PP
\fBdocker stop\fP
[\fB\-\-help\fP]
[\fB\-t\fP|\fB\-\-time\fP[=\fI10\fP]]
CONTAINER [CONTAINER...]


.SH DESCRIPTION
.PP
Stop a container (Send SIGTERM, and then SIGKILL after
 grace period)


.SH OPTIONS
.PP
\fB\-\-help\fP
  Print usage statement

.PP
\fB\-t\fP, \fB\-\-time\fP=\fI10\fP
  Number of seconds to wait for the container to stop before killing it. Default is 10 seconds.

.PP
#See also
\fBdocker\-start(1)\fP to restart a stopped container.


.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com)
based on docker.com source material and internal work.
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
