.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-logout \- Log out from a Docker registry.


.SH SYNOPSIS
.PP
\fBdocker logout\fP
[SERVER]


.SH DESCRIPTION
.PP
Log out of a Docker Registry located on the specified \fB\fCSERVER\fR. You can
specify a URL or a \fB\fChostname\fR for the \fB\fCSERVER\fR value. If you do not specify a
\fB\fCSERVER\fR, the command attempts to log you out of Docker's public registry
located at \fB\fChttps://registry\-1.docker.io/\fR by default.


.SH OPTIONS
.PP
There are no available options.


.SH EXAMPLES
.SH Log out from a registry on your localhost
.PP
.RS

.nf
# docker logout localhost:8080

.fi
.RE


.SH See also
.PP
\fBdocker\-login(1)\fP to register or log in to a Docker registry server.


.SH HISTORY
.PP
June 2014, Originally compiled by Daniel, Dao Quang Minh (daniel at nitrous dot io)
July 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
April 2015, updated by Mary Anthony for v2 
\[la]mary@docker.com\[ra]
