.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-top \- Display the running processes of a container


.SH SYNOPSIS
.PP
\fBdocker top\fP
[\fB\-\-help\fP]
CONTAINER [ps OPTIONS]


.SH DESCRIPTION
.PP
Display the running process of the container. ps\-OPTION can be any of the options you would pass to a Linux ps command.

.PP
All displayed information is from host's point of view.


.SH OPTIONS
.PP
\fB\-\-help\fP
  Print usage statement


.SH EXAMPLES
.PP
Run \fBdocker top\fP with the ps option of \-x:

.PP
.RS

.nf
$ docker top 8601afda2b \-x
PID      TTY       STAT       TIME         COMMAND
16623    ?         Ss         0:00         sleep 99999

.fi
.RE


.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com)
based on docker.com source material and internal work.
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
June 2015, updated by Ma Shimiao 
\[la]mashimiao.fnst@cn.fujitsu.com\[ra]
December 2015, updated by Pavel Pospisil 
\[la]pospispa@gmail.com\[ra]
