.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-port \- List port mappings for the CONTAINER, or lookup the public\-facing port that is NAT\-ed to the PRIVATE\_PORT


.SH SYNOPSIS
.PP
\fBdocker port\fP
[\fB\-\-help\fP]
CONTAINER [PRIVATE\_PORT[/PROTO]]


.SH DESCRIPTION
.PP
List port mappings for the CONTAINER, or lookup the public\-facing port that is NAT\-ed to the PRIVATE\_PORT


.SH OPTIONS
.PP
\fB\-\-help\fP
  Print usage statement


.SH EXAMPLES
.PP
.RS

.nf
# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                            NAMES
b650456536c7        busybox:latest      top                 54 minutes ago      Up 54 minutes       0.0.0.0:1234\->9876/tcp, 0.0.0.0:4321\->7890/tcp   test

.fi
.RE

.SH Find out all the ports mapped
.PP
.RS

.nf
# docker port test
7890/tcp \-> 0.0.0.0:4321
9876/tcp \-> 0.0.0.0:1234

.fi
.RE

.SH Find out a specific mapping
.PP
.RS

.nf
# docker port test 7890/tcp
0.0.0.0:4321

# docker port test 7890
0.0.0.0:4321

.fi
.RE

.SH An example showing error for non\-existent mapping
.PP
.RS

.nf
# docker port test 7890/udp
2014/06/24 11:53:36 Error: No public port '7890/udp' published for test

.fi
.RE


.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com)
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
November 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
