.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JULY 2015"  ""


.SH NAME
.PP
docker\-volume\-inspect \- Get low\-level information about a volume


.SH SYNOPSIS
.PP
\fBdocker volume inspect\fP
[\fB\-f\fP|\fB\-\-format\fP[=\fIFORMAT\fP]]
[\fB\-\-help\fP]
VOLUME [VOLUME...]


.SH DESCRIPTION
.PP
Returns information about one or more volumes. By default, this command renders all results
in a JSON array. You can specify an alternate format to execute a given template
is executed for each result. Go's

\[la]http://golang.org/pkg/text/template/\[ra] package describes all the details of the
format.


.SH OPTIONS
.PP
\fB\-f\fP, \fB\-\-format\fP=""
  Format the output using the given go template.

.PP
\fB\-\-help\fP
  Print usage statement


.SH HISTORY
.PP
July 2015, created by Brian Goff 
\[la]cpuguy83@gmail.com\[ra]
