.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "OCTOBER 2014"  ""


.SH NAME
.PP
docker\-rename \- Rename a container


.SH SYNOPSIS
.PP
\fBdocker rename\fP
OLD\_NAME NEW\_NAME


.SH OPTIONS
.PP
There are no available options.


.SH DESCRIPTION
.PP
Rename a container.  Container may be running, paused or stopped.
