.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""


.SH NAME
.PP
docker\-info \- Display system\-wide information


.SH SYNOPSIS
.PP
\fBdocker info\fP
[\fB\-\-help\fP]


.SH DESCRIPTION
.PP
This command displays system wide information regarding the Docker installation.
Information displayed includes the number of containers and images, pool name,
data file, metadata file, data space used, total data space, metadata space used
, total metadata space, execution driver, and the kernel version.

.PP
The data file is where the images are stored and the metadata file is where the
meta data regarding those images are stored. When run for the first time Docker
allocates a certain amount of data space and meta data space from the space
available on the volume where \fB\fC/var/lib/docker\fR is mounted.


.SH OPTIONS
.PP
\fB\-\-help\fP
  Print usage statement


.SH EXAMPLES
.SH Display Docker system information
.PP
Here is a sample output:

.PP
.RS

.nf
# docker info
Containers: 14
 Running: 3
 Paused: 1
 Stopped: 10
Images: 52
Server Version: 1.9.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 80
Execution Driver: native\-0.2
Logging Driver: json\-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0\-24\-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86\_64
CPUs: 1
Total Memory: 2 GiB

.fi
.RE


.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com)
based on docker.com source material and internal work.
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
