#!/usr/ruby/1.8/bin/ruby
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
 
#
# Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
#

pass_on_args = []
suppress = false
deprecation_msg =  "WARNING: gem_mirror has been deprecated and will be removed in a future release of Solaris, use 'gem mirror' instead. (use -s to suppress these warnings)\n\n"

print deprecation_msg unless ARGV.include?("-s")

ARGV.each do |arg|
  pass_on_args << arg unless arg == "-s"
end

system("gem", "mirror", *pass_on_args)
