#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2025 Marcel Telka
#

%patch% 01-no-jsonpath-ng.patch
%patch% 02-no-virtue.patch

%include-2%
# Python 3.9 is not supported by jsonschema >= 4.26.0
PYTHON_VERSIONS := $(filter-out 3.9,$(PYTHON_VERSIONS))
%include-3%
# This project does not support tox so we need to provide test requirements
# manually.
TEST_REQUIREMENTS_PEP735 += test

# We have no jsonpath-ng packaged (yet)
PYTEST_ADDOPTS += --ignore jsonschema/tests/test_exceptions.py
