.TH libtoolize 1 "18 Sep 2007"
.SH NAME
libtoolize - prepare a package to use \fBlibtool\fR(1)
.SH SYNOPSIS
libtoolize [OPTION]...
.SH DESCRIPTION
libtoolize is used to prepare a source tree for \fBlibtool\fR(1).
.LP
For additional information on using libtool, see the Info format
documentation by running the following command from your shell:
.RS
.I /usr/bin/info libtool
.RE
.LP
\fBlibtoolize\fR is provided for developers who are working on software
that has already adopted it.   However, it is not recommended that
\fBlibtoolize\fR be used when developing new software projects.
.LP
Note that the \fBlibtoolize\fR command has an interface stability of
Uncommitted (Obsolete).
.PD
.SH SEE ALSO
.BR libtool (1)
