.TH libtool 1 "18 Sep 2007"
.SH NAME
libtool \- shared library support tool
.SH SYNOPSIS
libtool [OPTION]... [MODE-ARG]...
.SH DESCRIPTION
GNU Libtool is a script that allows package developers to
provide generic shared library support.
.LP
For additional information on using libtool, see the Info format
documentation by running the following command from your shell:
.RS
.I /usr/bin/info libtool
.RE
.LP
\fBlibtool\fR is provided for developers who are working on software
that has already adopted it.   However, it is not recommended that
\fBlibtool\fR be used when developing new software projects.
.LP
Note that the \fBlibtool\fR command has an interface stability of
Uncommitted (Obsolete).
.PD
