#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2023 Marcel Telka
#

%include-2%
TEST_STYLE = pytest
%include-3%
# To get the POSIX conformant declaration of iconv(3c)
CFLAGS += $(CPP_XPG6MODE)

# Tests use non-default naming convention
PYTEST_ADDOPTS += -o python_files=test.py
