.TH vino-server 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
vino-server \- remote desktop server
.SH "SYNOPSIS"
.PP
.B "vino-server"
.SH "DESCRIPTION"
.PP
\fBvino-server\fR is a remote desktop server based on VNC protocol\&.
\fBvino-server\fR provides remote desktop takeover and remote desktop
view functions\&. \fBvino-server\fR allows multiple client to access a
GNOME desktop session remotely\&. It is based on the VNC technology\&.
\fBvino-server\fR provides service at port 5800\&. Each desktop has a vino
server which disabled by default and a Java client application which is made
available to a client via a web browser (via port 5900 of the server machine is
the service is enabled by the user)\&.
.SH "SEE ALSO"
.PP
.BR vino-passwd (1),
.BR vino-preferences (1),
.BR attributes (7)
.SH "NOTES"
.PP
Written by Steven Zhang, Sun Microsystems Inc\&., 2006\&.
.PP
Updated by Halton Huo, Sun Microsystems Inc\&., 2008\&.
