#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2022 Marcel Telka
#

%patch% 01-unixccompiler.patch
%patch% 02-test-disable-maint.patch
%patch% 03-no-pytest-perf.patch
%patch% 04-test-pkg.patch

%include-2%
# This component is required by following bootstrapped components so it must be
# bootstrapped too.
# - cachetools (test bootstrap)
# - calver (test bootstrap)
# - chardet (test bootstrap)
# - distlib (test bootstrap)
# - importlib_metadata
# - iniconfig (test bootstrap)
# - pluggy (test bootstrap)
# - pytest (test bootstrap)
# - setuptools-scm
# - tox-current-env (test bootstrap)
# - trove-classifiers (test bootstrap)
# - zipp
PYTHON_BOOTSTRAP = yes
%include-3%
# nose causes the test_pyproject_sets_attribute test to fail
TEST_CONFLICTING_PACKAGES.python += library/python/nose
# many tests are failing with recent setuptools-scm
TEST_CONFLICTING_PACKAGES.python += library/python/setuptools-scm

# fails with tox-current-env
PYTEST_ADDOPTS += --deselect setuptools/tests/config/test_setupcfg.py::TestOptions::test_cmdclass
PYTEST_ADDOPTS += --deselect setuptools/tests/test_extern.py::test_distribution_picklable

# https://github.com/pypa/setuptools/issues/5094
PYTEST_ADDOPTS += --deselect setuptools/tests/test_egg_info.py::TestEggInfo::test_setup_cfg_license_file_license_files

# https://github.com/pypa/setuptools/issues/5097
PYTEST_ADDOPTS += --deselect setuptools/tests/test_bdist_wheel.py::test_universal_deprecated

# Random directory name
COMPONENT_TEST_TRANSFORMS += "-e 's|/tmp/.*/garbage[^/]*|\$$(TMPDIR)|'"
