/*
 * Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
 *
 * U.S. Government Rights - Commercial software. Government users are subject
 * to the Sun Microsystems, Inc. standard license agreement and applicable
 * provisions of the FAR and its supplements.
 *
 *
 * This distribution may include materials developed by third parties. Sun,
 * Sun Microsystems, the Sun logo and Solaris are trademarks or registered
 * trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
 */
 
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 1.1.1.1 2003/03/26 18:12:29 pcarroll Exp $
 */
#ifndef DEMO_MODULE_2_H
#define DEMO_MODULE_2_H



/* function declarations */
void init_demo_module_2(void);
void initialize_table_me1FileTable(void);
Netsnmp_Node_Handler me1FileTable_handler;

Netsnmp_First_Data_Point  me1FileTable_get_first_data_point;
Netsnmp_Next_Data_Point   me1FileTable_get_next_data_point;

/* column number definitions for table me1FileTable */
       #define COLUMN_ME1FILEINDEX		1
       #define COLUMN_ME1FILENAME		2
       #define COLUMN_ME1FILESIZE		3
       #define COLUMN_ME1FILEPERM		4

typedef struct fileTable{
    unsigned long     findex;
    char     fileName[255];
    unsigned long     fileSize;
    char     filePerm[255];
    struct  fileTable* next;
} fileEntry;

#define ADDFILE 1
#define RMFILE  2
#define GETFILE 3
#define ME1FILE_SET_FILENAME "me1FileName"

#endif /* DEMO_MODULE_2_H */
