.TH AALIB 1
.SH NAME
aalib-config - script to get information about the installed version of aalib
.SH SYNOPSIS
.B aalib-config
[\-\-prefix\fI[=DIR]\fP] [\-\-exec\-prefix\fI[=DIR]\fP] [\-\-version] [\-\-libs] [\-\-static-libs] [\-\-cflags]
.SH DESCRIPTION
.PP
\fIaalib-config\fP is a tool that is used to configure to determine
the compiler and linker flags that should be used to compile
and link programs that use \fIaalib\fP. It is also used internally
to the .m4 macros for GNU autoconf that are included with \fIaalib\fP.
.
.SH OPTIONS
\fIaalib-config\fP accepts the following options:
.TP 8
.B  \-\-version
Print the currently installed version of \fIaalib\fP on the standard output.
.TP 8
.B  \-\-libs
Print the linker flags that are necessary to link a \fIaalib\fP program.
.TP 8
.B  \-\-static-libs
Print the linker flags that are necessary to link a \fIaalib\fP program
statically.
.TP 8
.B  \-\-cflags
Print the compiler flags that are necessary to compile a \fIaalib\fP program.
.TP 8
.B  \-\-prefix=PREFIX
If specified, use PREFIX instead of the installation prefix that \fIaalib\fP
was built with when computing the output for the \-\-cflags and
\-\-libs options. This option is also used for the exec prefix
if \-\-exec\-prefix was not specified. This option must be specified
before any \-\-libs or \-\-cflags options.
.TP 8
.B  \-\-exec\-prefix=PREFIX
If specified, use PREFIX instead of the installation exec prefix that
\fIaalib\fP was built with when computing the output for the \-\-cflags
and \-\-libs options.  This option must be specified before any
\-\-libs or \-\-cflags options.
.SH COPYRIGHT
Copyright \(co  1998 Owen Taylor

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation.

Modified for aalib by Joey Hess
