.TH csslint-0\&.6 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
csslint-0\&.6 \- command line CSS tool
.SH "SYNOPSIS"
.PP
\fBcsslint-0\&.6\fR [\fB\-\-help\fR] [\fB\-\-version\fR]
.PP
\fBcsslint-0\&.6\fR [\fB\-\-dump-location\fR] [\fB\fIfile\fR\fR\&...]
.PP
\fBcsslint-0\&.6\fR [\fB\-\-evaluate\fR] [\fB\-\-author-sheet \fIpath\fR\fR] [\fB\-\-ua-sheet \fIpath\fR\fR] [\fB\-\-user-sheet \fIpath\fR\fR] [\fB\-\-xml \fIpath\fR\fR] [\fB\-\-xpath \fIexpression\fR\fR] [\fB\fIfile\fR\fR\&...]
.SH "DESCRIPTION"
.PP
\fBcsslint-0\&.6\fR parses one or more CSS (Cascading Style Sheet) files,
specified on the command line\&.  It displays various types of output depending
on the options specified\&.  It is useful for detecting errors in the CSS code
and in the CSS parser itself\&.
.PP
Except when the \fB\-\-dump-location\fR option is used,
\fBcsslint-0\&.6\fR parses a CSS file and builds a CSS object model\&.
.SH "OPTIONS"
.PP
The following options are supported:
.TP 24
.BI \-\-author-sheet " path"
Specify the \fIpath\fR to an author sheet\&.  This option
is only useful with the \fB\-\-evaluate\fR option\&.
.TP 24
.B \-\-dump-location
Dumps parsing location information for selectors and property declarations\&.
.TP 24
\fB\-e\fR, \fB\-\-evaluate\fR
Display the CSS properties associated to the XML nodes referred to by an
xpath expression\&.  The xpath expression must be specified using the
\fB\-\-xpath\fR option and at least one type of stylesheet by using
the \fB\-\-author-sheet\fR, \fB\-\-ua-sheet\fR, and
\fB\-\-user-sheet\fR options\&.  An XML file can be specified with the
\fB\-\-xml\fR option\&.
.TP 24
.B \-\-help
Display usage information\&.
.TP 24
.BI \-\-ua-sheet " path"
Specify the \fIpath\fR to an ua sheet\&.  This option
is only useful with the \fB\-\-evaluate\fR option\&.
.TP 24
.BI \-\-user-sheet " path"
Specify the \fIpath\fR to an user sheet\&.  This option
is only useful with the \fB\-\-evaluate\fR option\&.
.TP 24
\fB\-v\fR, \fB\-\-version\fR
Display version information\&.
.TP 24
.BI \-\-xml " path"
Specify the \fIpath\fR to an XML file\&.  This option
is only useful with the \fB\-\-evaluate\fR option\&.
.TP 24
.BI \-\-xpath " expression"
Specify the xpath \fIexpression\fR to a\&.  This option
is only useful with the \fB\-\-evaluate\fR option\&.
.SH "OPERANDS"
.PP
The following operands are supported:
.TP 24
.I file
The name of one or more CSS files to be parsed\&.
.SH "SEE ALSO"
.PP
.BR libcroco-0\&.6 (3lib),
.BR attributes (7),
.SH "NOTES"
.PP
Original manpage written by Gael CHAMOULAUD (strider) <freespiders\&.org>\&.
Updated by Brian Cameron, Sun Microsystems, Inc\&., 2009\&.
