'\" te
.TH libjpeg 3 "06 Apr 2004" "SunOS 5.11" "C Library Functions"
.SH "NAME"
libjpeg \- image
compression library
.SH "SYNOPSIS"
.PP
\fBcc\fR [\fB\fIflag\fR\fR\&...] \fB\fIfile\fR\fR [\fB\fIlibrary\fR\fR\&...] -\fBljpeg\fR
.SH "DESCRIPTION"
.PP
This package contains C software to implement JPEG image compression
and decompression\&. JPEG is a standardized compression method for full-color
and grayscale images\&.
.SH "SEE ALSO"
.PP
\fBcjpeg\fR(1), \fBdjpeg\fR(1), \fBjpegtran\fR(1), \fBrdjpgcom\fR(1), \fBwrjpgcom\fR(1)
.SH "NOTES"
.PP
This man page was originally written by the Independent JPEG Group\&.
Updated by Breda McColgan, Sun Microsystems Inc\&., 2004\&.
