#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2025 Marcel Telka
#

%hook-no-license%
# license-detector is unable to detect the license due to unexpected formatting
LICENSE='PSF-2.0'

%include-2%
# This is needed for Python <= 3.10 only
PYTHON_VERSIONS = 3.9
