.\"
.\" generic ccache-swig man page for the swig Project
.br
.br
.TH ccache-swig 1 "07 Jun 2016" "swig 3.0.10" "User commands"
.SH NAME
.P
ccache-swig - a fast compiler cache
.br
.SH SYNOPSIS
.P
ccache-swig [OPTION]
.br
.P
ccache-swig <compiler> [COMPILER OPTIONS]
.br
.P
<compiler> [COMPILER OPTIONS]
.br
.SH DESCRIPTION
.P
ccache-swig is a compiler cache. It speeds up the re-compilation of C/C++/SWIG code by caching previous compiles and detecting when the same compile is being done again. ccache-swig is ccache plus support for SWIG. ccache and ccache-swig are used interchangeably in this document.
.br
.P
.SH "SEE ALSO"
.br
Installed documentation: /usr/share/swig/3.0.10/doc/manual/CCache.html
.br
.P
