'\" te
.\" Copyright (C) 2010 Internet Systems Consortium, Inc. ("ISC")
.\" Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies. THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\" Portions Copyright (c) 2010, Sun Microsystems, Inc. All Rights Reserved.
.TH dnssec-dsfromkey 8 "2010 年 1 月 11 日" "SunOS 5.12" "系统管理命令"
.SH 名称
dnssec-dsfromkey \- DNSSEC DS RR 生成工具
.SH 用法概要
.LP
.nf
\fBdnssec-dsfromkey\fR [\fB-v\fR \fIlevel\fR] [\fB-1\fR] [\fB-2\fR] [\fB-a\fR \fIalg\fR] \fIkeyfile\fR
.fi

.LP
.nf
\fBdnssec-dsfromkey\fR \fB-s\fR [\fB-v\fR \fIlevel\fR] [\fB-1\fR] [\fB-2\fR] [\fB-a\fR \fIalg\fR] [\fB-c\fR \fIclass\fR]
     [\fB-d\fR \fIdir\fR] \fIkeyfile\fR
.fi

.SH 描述
.sp
.LP
\fBdnssec-dsfromkey\fR
.SH 选项
.sp
.LP
支持以下选项：
.sp
.ne 2
.mk
.na
\fB\fB-1\fR\fR
.ad
.sp .6
.RS 4n
将 \fBSHA-1\fR 用作摘要算法。缺省情况下，同时使用 \fBSHA-1\fR 和 \fBSHA-256\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-2\fR\fR
.ad
.sp .6
.RS 4n
将 SHA-256 用作摘要算法。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-a\fR \fIalgorithm\fR\fR
.ad
.sp .6
.RS 4n
选择摘要算法。\fIalgorithm\fR 的值必须是 \fBSHA-1\fR (\fBSHA1\fR) 或 \fBSHA-256\fR (\fBSHA256\fR) 之一。这些值不区分大小写。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-v\fR \fIlevel\fR\fR
.ad
.sp .6
.RS 4n
设置调试级别。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR\fR
.ad
.sp .6
.RS 4n
密钥集模式：代替密钥文件名称，该参数是密钥集文件的 DNS 域名。\fB-c\fR 和 \fB-d\fR 选项仅在该模式下才有意义。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-c\fR \fIclass\fR\fR
.ad
.sp .6
.RS 4n
指定 DNS 类（缺省类是 \fBIN\fR）；仅在密钥集模式下才有用。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-d\fR \fIdirectory\fR\fR
.ad
.sp .6
.RS 4n
在作为目录的 directory 中查找密钥集文件；不处于密钥集模式下时忽略。
.RE

.SH 示例
.sp
.LP
要从 \fBKexample.com.+003+26160\fR 密钥文件名称构建 SHA-256 DS RR，请使用以下命令：
.sp
.in +2
.nf
# \fBdnssec-dsfromkey -2 Kexample.com.+003+26160\fR
.fi
.in -2
.sp

.sp
.LP
此命令将生成与下面类似的输出：
.sp
.in +2
.nf
example.com. IN DS 26160 5 2
3A1EADA7A74B8D0BA86726B0C227AA85AB8BBD2B2004F41A868A54F0
C5EA0B94
.fi
.in -2
.sp

.SH 文件
.sp
.LP
该密钥文件可以通过密钥标识 \fBK\fR\fInnnn\fR.+\fIaaa\fR+\fIiiiii\fR 或完整文件名 \fBK\fInnnn\fR.+\fIaaa\fR+\fIiiiii\fR.key \fR 指定，与由 \fBdnssec-keygen\fR(8) 生成的一样。
.sp
.LP
密钥集文件名基于目录、字符串 \fBkeyset-\fR 和 \fIdnsname\fR 构建而成。
.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性service/network/dns/bind
_
接口稳定性Volatile（可变）
.TE

.SH 另请参见
.sp
.LP
\fBdnssec-keygen\fR(8)、\fBdnssec-signzone\fR(8)、\fBattributes\fR(5)
.sp
.LP
\fIRFC 3658\fR、\fIRFC 4509\fR
.sp
.LP
请参见《\fIBIND 9 管理员参考手册\fR》。从本手册页发布之日起，将在 https://www.isc.org/software/bind/documentation 上提供该文档。
.SH 注意
.sp
.LP
密钥文件错误可以生成“未找到文件”消息，即使该文件存在也是如此。
