'\" te
.\" Copyright (C) 2004 Internet Systems Consortium, Inc. ("ISC") Copyright (C) 2000, 2001, 2003 Internet Software Consortium. Permission to use, copy, modify, and distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies. THE SOFTWARE IS PROVIDED "AS IS" AND ISC DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL ISC BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\" Portions Copyright (c) 2004, Sun Microsystems, Inc. All Rights Reserved.
.TH nsupdate 8 "2008 年 12 月 24 日" "SunOS 5.12" "系统管理命令"
.SH 名称
nsupdate \- 动态 DNS 更新实用程序
.SH 用法概要
.LP
.nf
\fBnsupdate\fR [\fB-dv\fR] [\fB-y\fR \fIkeyname:secret\fR | \fB-k\fR \fIkeyfile\fR] [\fB-t\fR \fItimeout\fR]
     [\fB-u\fR \fIudptimeout\fR] [\fB-r\fR \fIudpretries\fR] [\fIfilename\fR]
.fi

.SH 描述
.sp
.LP
\fBnsupdate\fR 实用程序向名称服务器提交动态 DNS 更新请求（如 RFC 2136 中定义）。该实用程序允许从区域添加或删除资源记录，无需手动编辑区域文件。单一更新请求可以包含添加或删除多个资源记录的请求。
.sp
.LP
\fBnsupdate\fR 或 DHCP 服务器动态控制下的区域不应手动编辑。手动编辑会与动态更新冲突，从而导致数据丢失。
.sp
.LP
通过 \fBnsupdate\fR 动态添加或删除的资源记录必须在相同区域中。请求将发送到区域 SOA 记录的 \fBMNAME\fR 字段标识的区域主服务器。
.sp
.LP
事务签名可用于对使用 RFC 2845 中描述的 TSIG 资源记录类型的动态 DNS 更新进行验证。签名依赖于应仅由 \fBnsupdate\fR 和名称服务器知道的共享秘密。当前，TSIG 唯一支持的加密算法是 HMAC-MD5，该算法在 RFC 2104 中定义。一旦为 TSIG 定义其他算法，应用程序在彼此验证时将需要确保它们选择了适当的算法和密钥。例如，适用的 \fBkey\fR 和 \fBserver\fR 语句将会添加到 \fB/etc/named.conf\fR，这样，名称服务器可以将适当的密钥和算法与将要使用 TSIG 验证的客户机应用程序的 IP 地址关联。\fBnsupdate\fR 实用程序不会读取 \fB/etc/named.conf\fR。
.sp
.LP
\fBnsupdate\fR 实用程序使用 \fB-y\fR 或 \fB-k\fR 选项提供共享秘密，生成用于验证动态 DNS 更新请求的 TSIG 记录时需要该秘密。这些选项是互斥的。请参见“选项”部分。
.SH 选项
.sp
.LP
支持以下选项：
.sp
.ne 2
.mk
.na
\fB\fB-d\fR\fR
.ad
.RS 21n
.rt  
在调试模式下操作。这可以提供有关提出的更新请求以及从名称服务器接收到的回复的跟踪信息。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-k\fR \fIkeyfile\fR\fR
.ad
.RS 21n
.rt  
从文件 \fIkeyfile\fR 读取共享秘密，其名称格式为 \fBK{\fIname\fR}.+157.+{\fIrandom\fR}.private\fR。由于历史原因，还必须存在文件 \fBK{\fIname\fR}.+157.+{\fI random\fR}.key\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-r\fR \fIudpretries\fR\fR
.ad
.RS 21n
.rt  
设置 UDP 重试次数。缺省为重试 3 次。如果将 \fIudpretries\fR 设置为零，仅进行一次更新请求。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-t\fR \fItimeout\fR\fR
.ad
.RS 21n
.rt  
设置中止更新前的 \fItimeout\fR 间隔（以秒为单位）。缺省值是 300 秒。设置为零会禁用超时。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-u\fR \fIudptimeout\fR\fR
.ad
.RS 21n
.rt  
以秒为单位设置 UDP 重试之间的间隔，缺省设置是 3 秒。如果设置为零，会根据超时 (\fB-t\fR) 和 UDP 重试次数 (\fB-r\fR) 计算间隔时间。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-v\fR\fR
.ad
.RS 21n
.rt  
使用 TCP 连接。进行批量更新请求时，使用 TCP 连接更合适。缺省情况下，\fBnsupdate\fR 使用 UDP 向名称服务器发送更新请求。
.RE

.sp
.ne 2
.mk
.na
\fB\fB-y\fR \fIkeyname\fR:\fIsecret\fR\fR
.ad
.RS 21n
.rt  
从 \fIkeyname\fR:\fIsecret\fR 生成签名，其中 \fIkeyname\fR 是密钥名称，\fIsecret\fR 是 base64 编码的共享秘密。
.sp
不建议使用 \fB-y\fR 选项，因为共享秘密作为命令行参数以明文形式提供，可以在 \fBps\fR(1)的输出中或用户 shell 维护的历史文件中看到。
.RE

.SH 输入格式
.sp
.LP
\fBnsupdate\fR 实用程序从 \fIfilename\fR 读取输入或读取标准输入。每个命令都以单行输入提供。有些命令用于管理目的。其他则是对区域内容的更新说明或先决条件检查。这些检查设置某些名称或资源记录集合 (RRset) 在区域中存在或不存在的条件。要成功执行整个更新请求，必须满足这些条件。如果对先决条件的测试失败，更新将被拒绝。
.sp
.LP
每个更新请求都包含零或多个先决条件以及零或多个更新。如果某些指定资源记录在区域中存在或缺失，该条件允许适当验证的更新请求继续执行。空白输入行（或 \fBsend\fR 命令）将累积的命令作为一个动态 DNS 更新请求发送到名称服务器。
.sp
.LP
命令格式及其意义如下：
.sp
.ne 2
.mk
.na
\fB\fBserver\fR \fIservername\fR [ \fIport\fR ]\fR
.ad
.sp .6
.RS 4n
将全部动态更新请求发送到名称服务器 \fIservername\fR。未提供 \fBserver\fR 语句时，\fBnsupdate\fR 将更新发送至正确区域的主服务器。该区域 SOA 记录的 \fBMNAME\fR 字段标识该区域的主服务器。\fIport\fR 参数是动态更新请求发送到的 \fIservername\fR 上的端口号。如果未指定端口号，会使用缺省 DNS 端口号 53。
.RE

.sp
.ne 2
.mk
.na
\fB\fBlocal\fR \fIaddress\fR [ \fIport\fR ]\fR
.ad
.sp .6
.RS 4n
使用本地 \fIaddress\fR 发送所有动态更新请求。未提供 \fBlocal\fR 语句时，\fBnsupdate\fR 使用系统选择的地址和端口发送更新。\fIport\fR 参数也可用于从特定端口提出请求。如果没有指定端口号，系统会分配一个。
.RE

.sp
.ne 2
.mk
.na
\fB\fBzone\fR \fIzonename\fR\fR
.ad
.sp .6
.RS 4n
指定要对区域 \fIzonename\fR 做出所有更新。如果未提供 \fBzone\fR 语句，\fBnsupdate\fR 会根据输入的剩余部分尝试确定要更新的正确区域。
.RE

.sp
.ne 2
.mk
.na
\fB\fBclass\fR \fIclassname\fR\fR
.ad
.sp .6
.RS 4n
指定缺省类。如果未指定类，缺省类为 IN。
.RE

.sp
.ne 2
.mk
.na
\fB\fBkey\fR \fIname\fR \fIsecret\fR\fR
.ad
.sp .6
.RS 4n
指定所有更新将使用 \fIname\fR \fIsecret\fR 对进行 TSIG 签名。\fBkey\fR 命令覆盖通过 \fB-y\fR 或 \fB-k\fR 选项在命令行上指定的所有密钥。
.RE

.sp
.ne 2
.mk
.na
\fB\fBprereq nxdomain\fR \fIdomain-name\fR\fR
.ad
.sp .6
.RS 4n
要求不能存在名称为 \fIdomain-name\fR 的任何类型的资源记录。
.RE

.sp
.ne 2
.mk
.na
\fB\fBprereq yxdomain\fR \fIdomain-name\fR\fR
.ad
.sp .6
.RS 4n
要求存在 \fIdomain-name\fR（至少有一个资源记录，无论类型如何）。
.RE

.sp
.ne 2
.mk
.na
\fB\fBprereq nxrrset\fR \fIdomain-name\fR [ \fIclass\fR ] \fItype\fR\fR
.ad
.sp .6
.RS 4n
要求不能存在指定 \fItype\fR、\fIclass\fR 和 \fIdomain-name\fR 的资源记录。如果省略 \fIclass\fR，则假定是 IN (internet)。
.RE

.sp
.ne 2
.mk
.na
\fB\fBprereq yxrrset\fR \fIdomain-name\fR [ \fIclass\fR ] \fItype\fR\fR
.ad
.sp .6
.RS 4n
要求必须存在指定 \fItype\fR、\fIclass\fR 和 \fIdomain-name\fR 的资源记录。如果省略 \fIclass\fR，则假定是 IN (internet)。
.RE

.sp
.ne 2
.mk
.na
\fB\fBprereq yxrrset\fR \fIdomain-name\fR [ \fIclass\fR ] \fItype\fR \fIdata\fR...\fR
.ad
.sp .6
.RS 4n
来自共享相同 \fItype\fR、\fIclass\fR 和 \fIdomain-name\fR 的格式的每一组先决条件的 \fIdata\fR 将组合构成一个 RR 集合。该 RR 集合必须与区域中给定 \fItype\fR、\fIclass\fR 和 \fIdomain-name\fR 的现有 RR 集合完全匹配。\fIdata\fR 以资源记录的 RDATA 的标准文本表示来书写。
.RE

.sp
.ne 2
.mk
.na
\fB\fBupdate delete\fR \fIdomain-name\fR [ \fIttl\fR ] [ \fIclass\fR ] [ \fItype\fR [ \fIdata\fR... ] ]\fR
.ad
.sp .6
.RS 4n
删除名为 \fIdomain-name\fR 的任何资源记录。如果提供了 \fItype\fR 和 \fIdata\fR，只会删除匹配的资源记录。如果未提供 \fIclass\fR，则假定为 internet 类。将忽略 \fIttl\fR，其仅为兼容性而提供。
.RE

.sp
.ne 2
.mk
.na
\fB\fBupdate add\fR \fIdomain-name\fR \fIttl\fR [ \fIclass\fR ] \fItype\fR \fIdata\fR...\fR
.ad
.sp .6
.RS 4n
添加具有指定 \fIttl\fR、\fIclass\fR 和 \fIdata\fR 的新资源记录。
.RE

.sp
.ne 2
.mk
.na
\fB\fBshow\fR\fR
.ad
.sp .6
.RS 4n
显示当前消息，包含上次发送以来指定的所有先决条件和更新。
.RE

.sp
.ne 2
.mk
.na
\fB\fBsend\fR\fR
.ad
.sp .6
.RS 4n
发送当前消息。这等效于输入空白行。
.RE

.sp
.ne 2
.mk
.na
\fB\fBanswer\fR\fR
.ad
.sp .6
.RS 4n
显示回答。
.RE

.sp
.LP
以分号开始的行是注释，将被忽略。
.SH 示例
.LP
\fB示例 1 \fR在区域中插入和删除资源记录
.sp
.LP
以下示例显示如何使用 \fBnsupdate\fR 在 \fBexample.com\fR 区域插入和删除资源记录。请注意，每个示例中的输入包括一个结尾空白行，这样，一组命令会作为一个动态更新请求发送到 \fBexample.com\fR 主名称服务器。

.sp
.in +2
.nf
# nsupdate
> update delete oldhost.example.com A
> update add newhost.example.com 86400 A 172.16.1.1
> send
.fi
.in -2
.sp

.sp
.LP
\fBoldhost.example.com\fR 的所有 A 记录都会删除。会为 IP 地址为 172.16.1.1 的 \fBnewhost.example.com\fR 添加 A 记录。新添加的记录有 1 天的 TTL（86400 秒）。

.LP
\fB示例 2 \fR仅当无记录存在时添加 CNAME
.sp
.LP
以下命令仅在其不存在记录时添加 CNAME。

.sp
.in +2
.nf
# nsupdate
> prereq nxdomain nickname.example.com
> update add nickname.example.com 86400 CNAME somehost.example.com
> send
.fi
.in -2
.sp

.sp
.LP
先决条件使名称服务器检查 \fBnickname.example.com\fR 是否有任何类型的资源记录。如果有，更新请求失败。如果该名称不存在，会为其添加 \fBCNAME\fR。该操作确保添加 \fBCNAME\fR 时，它不会与 RFC 1034 中的以下长期存在的规则冲突：如果一个名称作为 \fBCNAME\fR 存在，就不能作为任何其他的记录类型存在。（该规则已经为 RFC 4035 中的 DNSSEC 进行了更新，以允许 \fBCNAME\fR 具有\fB RSIG\fR、\fBDNSKEY\fR 和 \fBNSEC\fR 记录。）

.SH 文件
.sp
.ne 2
.mk
.na
\fB\fB/etc/resolv.conf\fR\fR
.ad
.sp .6
.RS 4n
用于标识缺省名称服务器
.RE

.sp
.ne 2
.mk
.na
\fB\fBK{\fIname\fR}.+157.+{\fIrandom\fR}.key\fR\fR
.ad
.sp .6
.RS 4n
\fBdnssec-keygen\fR(8) 创建的 HMAC-MD5 密钥的 base-64 编码。
.RE

.sp
.ne 2
.mk
.na
\fB\fBK{\fIname\fR}.+157.+{\fIrandom\fR}.private\fR\fR
.ad
.sp .6
.RS 4n
\fBdnssec-keygen\fR(8) 创建的 HMAC-MD5 密钥的 base-64 编码
.RE

.SH 已知问题
.sp
.LP
TSIG 密钥分别存储在两个单独文件中。这是为加密操作使用 DST 库的 \fBnsupdate\fR 结果，在未来的发行版中可能会有所变化。
.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性service/network/dns/bind
_
接口稳定性Volatile（可变）
.TE

.SH 另请参见
.sp
.LP
\fBnamed\fR(8)、\fBdnssec-keygen\fR(8)、\fBattributes\fR(5)
.sp
.LP
\fIRFC 2136\fR、\fIRFC 3007\fR、\fIRFC 2104\fR、\fIRFC 2845\fR、\fIRFC 1034\fR、\fIRFC 2535\fR、\fIRFC 2931\fR、\fIRFC 4035\fR
