'\" t
.\" Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
.\" Modified for Solaris to add the Solaris stability classification,
.\" and to add a note about source availability.
.\"
.TH "IB_CLOCK_TEST" 1 "4 April 2011" "User Commands"

.SH "NAME"
ib_clock_test \- Test accuracy of system clock used in conjunction with
other IB perftest utilities
.SH "SYNOPSIS"
.sp
.nf
\fBib_clock_test\fR
.fi
.SH "DESCRIPTION"
.sp
The \fBib_clock_test\fR() test utility is part of the \fB"perftest"\fR
utilities that are used for InfiniBand related performance testing. The
\fB"perftest"\fR utilities (See \fBib_read_lat\fR(1), 
\fBib_write_bw_postlist\fR(1), \fBib_write_bw\fR(1), etc.) are micro
bench mark utilities. Users of the these can use \fBib_clock_test\fR(1M)
to test accuracy of system clock.
.sp
The \fBib_clock_test\fR(1M) utility, tests the accuracy of the system clock,
takes no parameters and provides the following output:
          #ib_clock_test
          Type CTRL-C to cancel.
          1 sec = 1.00004e+06 usec
          1 sec = 1.00004e+06 usec
          1 sec = 1.00004e+06 usec
          1 sec = 1.00004e+06 usec
          1 sec = 1.00004e+06 usec
          ...
.sp
.SH "SEE ALSO"
.PP
\fBib_write_bw\fR(1), \fBib_send_bw\fR(1), \fBib_rdma_lat\fR(1),
\fBib_read_bw\fR(1), \fBib_read_lat\fR(1), \fBib_write_bw_postlist\fR(1),
\fBib_rdma_bw\fR(1), \fBib_write_lat\fR(1), \fBib_send_lat\fR(1)
