'\" t
.\" Copyright (c) 2012, 2017, Oracle and/or its affiliates. All rights reserved.
.\" Modified for Solaris to add the Solaris stability classification,
.\" and to add a note about source availability.
.\"
.TH IB_READ_BW(1) IB_READ_LAT 1 " Oct 15, 2011"
.SH "NAME"
ib_read_bw, ib_read_lat - Bandwith and latency test using RDMA read transactions. 
.PP
.SH SYNOPSIS
.HP
.nf
ib_read_bw [-p, --port=<port>] [-d, --ib-dev=<dev>]
      [-i, --ib-port=<port number.] [-c, --connection=<RC|UD>]
      [-m, --mtu=<mtu>] [-s, --size=<size>] [-a, --all]
      [-n, --iters=<iterations>] [-t, --tx-depth=<depth>]
      [-u, --qp-timeout=<timeout] [-S, --sl=<sl>]
      [-x, --gid-index=<index>] [-F, --CPU-freq] [-V, --version]
      [-b, --bidirectional] [-e, --events] [-N, --no peak-bw]
      [-o, --outs=<num>] [server]
.fi
.HP

.nf
ib_read_lat [-p, --port=<port>] [-d, --ib-dev=<dev>]
      [-i, --ib-port=<port number.] [-c, --connection=<RC|UD>]
      [-m, --mtu=<mtu>] [-s, --size=<size>] [-a, --all]
      [-n, --iters=<iterations>] [-t, --tx-depth=<depth>]
      [-u, --qp-timeout=<timeout] [-S, --sl=<sl>]
      [-x, --gid-index=<index>] [-F, --CPU-freq] [-V, --version]
      [-e, --events] [-o, --outs=<num>] [-C, --report-cycles]
      [-H, --report-histogram] [-U, --report-unsorted] [server]
.fi


.SH DESCRIPTION
.PP
.Nm
The ib_read_bw and ib_read_lat tests are part of the "perftest" utilities that  are  used  for  InfiniBand  related  performance  testing. The "perftest" utilities are micro bench mark utilities.

.PP
First a passive receiving instance is started.
.RS 12

	#ib_read_bw
.RE
.PP
Then an active sending instance is started, giving it the address at which it will find a listening passive receiver.
.PP
.RS 12
	#ib_read_bw server 
.RE
.PP
If options are used then the same options must be  used for both client and server.
.PP
.SH OPTIONS
.PP
The following options are available for use on the command line:

.TP 7
\fB\-p, --port  <port>
Listen on/connect to port <port> (default 18515)
.TP
\fB\-d, --ib-dev <dev>
Use IB device <dev> (default first device found)
.TP
\fB\-i, --ib-port <port number>
Use port <port number> of IB device (default 1)
.TP
\fB\-c, --connection <RC|UD>
 Connection type RC or UD (default RC)
.TP
\fB\-m, --mtu <mtu>s
Mtu size : 256 - 4096 (default port mtu)
.TP
\fB\-s, --size <size>
Size of message to exchange (default 2)
.TP
\fB\-a, --all
Run sizes from 2 till 2^23
.TP
\fB\-n, --iters <iterations>
Number of exchanges (at least 5, default 1000)
.TP
\fB\-t, --tx-depth  <depth>
Size of tx queue (default 50)
.TP
\fB\-u, --qp-timeout <timeout>
QP timeout, timeout value is 4 usec * 2 ^(timeout), default 14
.TP
\fB\-S, --sl <sl>
SL (default 0)
.TP
\fB\-x, --gid-index <index>
Test uses GID with GID index (Default : IB - no gid)
.TP
\fB\-F, --CPU-freq
Do not fail even if cpufreq_ondemand module is loaded
.TP
\fB\-V, --version
Display version number
.TP
\fB\-b, --bidirectional
Measure bidirectional bandwidth (default unidirectional)
.TP
\fB\-e, --events
Sleep on CQ events (default poll)
.TP
\fB\-N, --no peak-bw
Cancel peak-bw calculation (default with peak)
.TP
\fB\-o, --outs <num>
Specify <num> as number of outstanding read/atom(default max of device)
.TP
\fB\-C, --report-cycles
report times in cpu cycle units (default microseconds)
.TP
\fB\-H, --report-histogram
Print out all results (default print summary only)
.TP
\fB\-U, --report-unsorted
(implies -H) print out unsorted results (default sorted)
.PP
.SH SEE ALSO
ib_write_bw(1), ib_send_bw(1), rdma_lat(1), ib_write_bw_postlist(1), rdma_bw(1), ib_write_lat(1), ib_send_lat(1), ib_clock_test(8)
