'\" te
.\"
.\" Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
.\"
.\" ident	"@(#)madt.1	1.2	10/03/16 SMI"
.\"
.TH madt 1 "24 Apr 2009" "SunOS 5.11" "User Commands"
.SH NAME
madt - parse ACPI tables
.SH SYNOPSIS
.LP
.nf
\fBmadt [ACPI data file]
.fi

.SH DESCRIPTION
.sp
.LP
This utility parses the specified data file containing an extracted image of an ACPI table.  It displays the results to the user in human-readable text.

.SH EXAMPLES
.sp
.LP
# madt < SRAT2.dat


.SH SEE ALSO
acpidump(1), acpixtract(1)

.SH RESOURCES
.sp
.LP
http://www.lesswatts.org/projects/acpi/utilities.php
.sp

