.TH libxml 3 "23 May 2002"
.SH NAME
libxml \- library used to parse XML files
.SH DESCRIPTION
The
.I  libxml
library is used to parse XML files. 
Its internal document repesentation is as close as possible to the 
.I DOM 
(Document Object Model) interface,
an API for accessing XML or HTML structured documents.
.LP
The
.I libxml
library also has a 
.IR SAX -like
interface, 
which is designed to be compatible with that of another XML parser library
called 
.IR expat.
NOTE:
.IR SAX , 
the Simple API for XML,
is a standard interface for event-based XML parsing,
developed collaboratively by the members of the XML-DEV mailing list, 
currently hosted by OASIS.
The
.I expat
library is a XML 1.0 parser written in C,
which aims to be fully conforming. 
It is currently not a validating XML processor.
.LP
The
.I libxml 
library now includes a nearly complete 
.I XPath 
implementation. 
The
.I XPath
(XML Path Language) is a language for addressing parts of an 
XML document,
designed to be used by both 
.I XSLT 
and 
.IR XPointer .
.LP
The
.I libxml 
library exports Push and Pull type parser interfaces for both XML and 
.IR html . 
.SH FILES
.TP 2.2i
.B /usr/lib/libxml2.so
shareable library
.TP
.B /usr/bin/xmlcatalog
binary application for parsing and manipulating XML or SGML catalog files
.TP
.B /usr/bin/xmllint
binary application for parsing XML files
.TP
.B /usr/bin/xml2-config
binary application for printing library configuration
.TP
.B /usr/include/libxml2
header files
.SH AUTHORS
Daniel Veillard (daniel@veillard.com).
If you download and install this package please send the author email.
Manual page by Ziying Sherwin (sherwin@nlm.nih.gov),
Lister Hill National Center for Biomedical Communications,
U.S. National Library of Medicine.
.\" end of manual page
.SH SEE ALSO
.IR xmlcatalog (1),
.IR xmllint (1),
.IR xml2-config (1).
