.TH libxslt 3 "17 Jul 2002"
.SH NAME
libxslt \- library for transforming XML documents
.SH DESCRIPTION
The
.I libxslt
library is the XSLT library developed for the Gnome project.  XSLT
itself is a declarative language for transforming XML documents into other
XML documents, or arbitrary text output using a stylesheet.

.LP
The
.I libxslt
library is based on
.I libxml2 
library developed for the Gnome project.  It also implements most
of the EXSLT set of processor-portable extensions functions and some of Saxon's
evaluate and expressions extensions.

.SH FILES
.TP 2.2i
.B /usr/lib/libxslt.so
shared object library
.TP
.B /usr/lib/libexslt.so
shared object library
.TP
.B /usr/bin/xsltproc
command line XSLT processor
.TP
.B /usr/bin/xslt-config
binary application for printing library configuration
.TP
.B /usr/include/libxslt
header files
.TP
.B /usr/share/lib/xml/style
stylesheets

.SH AUTHORS
Daniel Veillard (daniel@veillard.com).

.SH SEE ALSO
.IR xsltproc (1),
.IR xslt-config (1),
.IR libxml (3)
