#
# MAPFILE HEADER START
#
# WARNING:  STOP NOW.  DO NOT MODIFY THIS FILE.
# Object versioning must comply with the rules detailed in
#
#	usr/src/lib/README.mapfiles
#
# You should not be making modifications here until you've read the most current
# copy of that file. If you need help, contact a gatekeeper for guidance.
#
# MAPFILE HEADER END
#
# Note that the source above actually lives in the ON tree.
#
$mapfile_version 2

SYMBOL_VERSION SUNW_1.5 {
	global:
		xsltMaxVars;
		xsltFreeLocales;
		xsltXPathCompileFlags;
} SUNW_1.4;

SYMBOL_VERSION SUNW_1.4 {
	global:
		xsltCheckExtURI;
		xsltExtensionInstructionResultFinalize;
		xsltExtensionInstructionResultRegister;
		xsltFreeLocale;
		xsltInit;
		xsltInitAllDocKeys;
		xsltInitGlobals;
		xsltLocaleStrcmp;
		xsltLocalVariablePop;
		xsltLocalVariablePush;
		xsltNewLocale;
		xsltRegisterLocalRVT;
		xsltReleaseRVT;
		xsltStrxfrm;
		xsltUninit;
} SUNW_1.3;

SYMBOL_VERSION SUNW_1.3 {
	global:
		xsltDocDefaultLoader;
		xsltSetLoaderFunc;
} SUNW_1.2;

SYMBOL_VERSION SUNW_1.2 {
	global:
		xsltAttrTemplateValueProcessNode;
		xsltCheckRead;
		xsltCheckWrite;
		xsltCompileAttr;
		xsltComputeSortResult;
		xsltCopyTextString;
		xsltCreateRVT;
		xsltDebugGetDefaultTrace;
		xsltDebugSetDefaultTrace;
		xsltDefaultSortFunction;
		xsltDefaultTrace;
		xsltEvalAVT;
		xsltEvalXPathStringNs;
		xsltFreeAVTList;
		xsltFreeRVTs;
		xsltFreeSecurityPrefs;
		xsltGetCNsProp;
		xsltGetDebuggerStatus;
		xsltGetDefaultSecurityPrefs;
		xsltGetExtInfo;
		xsltGetPlainNamespace;
		xsltGetProfileInformation;
		xsltGetQNameURI2;
		xsltGetSecurityPrefs;
		xsltGetUTF8Char;
		xsltNewSecurityPrefs;
		xsltNormalizeCompSteps;
		xsltParseStylesheetImportedDoc;
		xsltRegisterPersistRVT;
		xsltRegisterTmpRVT;
		xsltSecurityAllow;
		xsltSecurityForbid;
		xsltSetCtxtParseOptions;
		xsltSetCtxtSecurityPrefs;
		xsltSetCtxtSortFunc;
		xsltSetDebuggerStatus;
		xsltSetDefaultSecurityPrefs;
		xsltSetSecurityPrefs;
		xsltSetSortFunc;
		xsltSetTransformErrorFunc;
		xsltSplitQName;
		xsltTransformError;
		xsltXPathCompile;
} SUNW_1.1;

SYMBOL_VERSION SUNW_1.1 {
	global:
		xslAddCall;
		xslDropCall;
		xslHandleDebugger;
		xsltAddKey;
		xsltAddStackElemList;
		xsltAddTemplate;
		xsltAllocateExtra;
		xsltAllocateExtraCtxt;
		xsltApplyAttributeSet;
		xsltApplyImports;
		xsltApplyOneTemplate;
		xsltApplyStripSpaces;
		xsltApplyStylesheet;
		xsltApplyStylesheetUser;
		xsltApplyTemplates;
		xsltAttrListTemplateProcess;
		xsltAttrTemplateProcess;
		xsltAttrTemplateValueProcess;
		xsltAttribute;
		xsltCalibrateAdjust;
		xsltCallTemplate;
		xsltCheckExtPrefix;
		xsltChoose;
		xsltCleanupGlobals;
		xsltCleanupTemplates;
		xsltComment;
		xsltCompilePattern;
		xsltCopy;
		xsltCopyNamespace;
		xsltCopyNamespaceList;
		xsltCopyOf;
		xsltCopyTree;
		xsltDebug;
		xsltDebugDumpExtensions;
		xsltDecimalFormatGetByName;
		xsltDoSortFunction;
		xsltDocumentComp;
		xsltDocumentElem;
		xsltDocumentFunction;
		xsltDocumentSortFunction;
		xsltElement;
		xsltElementAvailableFunction;
		xsltEvalAttrValueTemplate;
		xsltEvalGlobalVariables;
		xsltEvalOneUserParam;
		xsltEvalStaticAttrValueTemplate;
		xsltEvalTemplateString;
		xsltEvalUserParams;
		xsltEvalXPathPredicate;
		xsltEvalXPathString;
		xsltExtElementLookup;
		xsltExtModuleElementLookup;
		xsltExtModuleElementPreComputeLookup;
		xsltExtModuleFunctionLookup;
		xsltExtModuleTopLevelLookup;
		xsltFindDocument;
		xsltFindElemSpaceHandling;
		xsltFindTemplate;
		xsltForEach;
		xsltFormatNumberConversion;
		xsltFormatNumberFunction;
		xsltFreeAttributeSetsHashes;
		xsltFreeCompMatchList;
		xsltFreeCtxtExts;
		xsltFreeDocumentKeys;
		xsltFreeDocuments;
		xsltFreeExts;
		xsltFreeGlobalVariables;
		xsltFreeKeys;
		xsltFreeNamespaceAliasHashes;
		xsltFreeStackElemList;
		xsltFreeStyleDocuments;
		xsltFreeStylePreComps;
		xsltFreeStylesheet;
		xsltFreeTemplateHashes;
		xsltFreeTransformContext;
		xsltFunctionAvailableFunction;
		xsltFunctionNodeSet;
		xsltGenerateIdFunction;
		xsltGetExtData;
		xsltGetKey;
		xsltGetNamespace;
		xsltGetNsProp;
		xsltGetQNameURI;
		xsltGetSpecialNamespace;
		xsltGetTemplate;
		xsltGetXIncludeDefault;
		xsltIf;
		xsltInitCtxtExts;
		xsltInitCtxtKeys;
		xsltInitElemPreComp;
		xsltIsBlank;
		xsltKeyFunction;
		xsltLoadDocument;
		xsltLoadStyleDocument;
		xsltLoadStylesheetPI;
		xsltMessage;
		xsltNamespaceAlias;
		xsltNeedElemSpaceHandling;
		xsltNewDocument;
		xsltNewElemPreComp;
		xsltNewStyleDocument;
		xsltNewStylesheet;
		xsltNewTransformContext;
		xsltNextImport;
		xsltNumber;
		xsltNumberFormat;
		xsltParseGlobalParam;
		xsltParseGlobalVariable;
		xsltParseStylesheetAttributeSet;
		xsltParseStylesheetCallerParam;
		xsltParseStylesheetDoc;
		xsltParseStylesheetFile;
		xsltParseStylesheetImport;
		xsltParseStylesheetInclude;
		xsltParseStylesheetOutput;
		xsltParseStylesheetParam;
		xsltParseStylesheetProcess;
		xsltParseStylesheetVariable;
		xsltParseTemplateContent;
		xsltPreComputeExtModuleElement;
		xsltPrintErrorContext;
		xsltProcessOneNode;
		xsltProcessingInstruction;
		xsltProfileStylesheet;
		xsltQuoteOneUserParam;
		xsltQuoteUserParams;
		xsltRegisterAllElement;
		xsltRegisterAllExtras;
		xsltRegisterAllFunctions;
		xsltRegisterExtElement;
		xsltRegisterExtFunction;
		xsltRegisterExtModule;
		xsltRegisterExtModuleElement;
		xsltRegisterExtModuleFull;
		xsltRegisterExtModuleFunction;
		xsltRegisterExtModuleTopLevel;
		xsltRegisterExtPrefix;
		xsltRegisterExtras;
		xsltRegisterTestModule;
		xsltResolveStylesheetAttributeSet;
		xsltRunStylesheet;
		xsltRunStylesheetUser;
		xsltSaveProfiling;
		xsltSaveResultTo;
		xsltSaveResultToFd;
		xsltSaveResultToFile;
		xsltSaveResultToFilename;
		xsltSaveResultToString;
		xsltSetDebuggerCallbacks;
		xsltSetGenericDebugFunc;
		xsltSetGenericErrorFunc;
		xsltSetXIncludeDefault;
		xsltShutdownCtxtExts;
		xsltShutdownExts;
		xsltSort;
		xsltStyleGetExtData;
		xsltStylePreCompute;
		xsltSystemPropertyFunction;
		xsltTemplateProcess;
		xsltTestCompMatchList;
		xsltText;
		xsltTimestamp;
		xsltUnparsedEntityURIFunction;
		xsltUnregisterExtModule;
		xsltUnregisterExtModuleElement;
		xsltUnregisterExtModuleFunction;
		xsltUnregisterExtModuleTopLevel;
		xsltValueOf;
		xsltVariableLookup;
		xsltXPathFunctionLookup;
		xsltXPathGetTransformContext;
		xsltXPathVariableLookup;
		xslDebugStatus;
		xsltEngineVersion;
		xsltExtMarker;
		xsltGenericDebug;
		xsltGenericDebugContext;
		xsltGenericError;
		xsltGenericErrorContext;
		xsltLibxmlVersion;
		xsltLibxsltVersion;
		xsltMaxDepth;
	local:
		*;
};
