.TH xslt-config 1 "17 Jul 2002"
.SH NAME
xslt-config - script to get information about the installed version of libxslt
.SH SYNOPSIS
.B xslt-config
[\-\-prefix\fI[=DIR]\fP] [\-\-exec\-prefix\fI[=DIR]\fP] 
[\-\-libs] [\-\-cflags] [\-\-version] [\-\-help]
.SH DESCRIPTION
\fIxslt-config\fP is a tool that is used to determine the compile and
linker flags that should be used to compile and link programs that use
\fIlibxslt\fP.
.SH OPTIONS
.l
\fIxslt-config\fP accepts the following options:
.TP 8
.B  \-\-version
Print the currently installed version of \fIlibxslt\fP on the standard output.
.TP 8
.B  \-\-libs
Print the linker flags that are necessary to link a \fIlibxslt\fP program.
.TP 8
.B  \-\-cflags
Print the compiler flags that are necessary to compile a \fIlibxslt\fP program.
.TP 8
.B  \-\-prefix=PREFIX
If specified, use PREFIX instead of the installation prefix that
\fIlibxslt\fP was built with when computing the output for the
\-\-cflags and \-\-libs options. This option must be specified before
any \-\-libs or \-\-cflags options.
.TP 8
.B  \-\-exec\-prefix=PREFIX
If specified, use PREFIX instead of the executable prefix that
\fIlibxslt\fP was built with when computing the output for the
\-\-cflags and \-\-libs options. This option must be specified before
any \-\-libs or \-\-cflags options.

.SH AUTHORS
Daniel Veillard (daniel@veillard.com)
