.TH gnome-character-map 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
gucharmap, charmap, gnome-character-map \- insert special characters into a document
.SH "SYNOPSIS"
.PP
\fBgucharmap\fR [-\fB-font=\fIstring\fR\fR] [\fB\fIgnome-std-options\fR\fR]
.SH "DESCRIPTION"
.PP
The Character Map application enables you to select characters from a
character table, then combine the characters into a text string with standard
characters\&. You can insert the text string that you create into other
applications, such as text editor documents\&.
.PP
Character Map provides accented characters, mathematical symbols, special
symbols, and punctuation marks\&. Many of the characters are not available on
a standard keyboard\&.
.PP
.BR charmap (1)
and
.BR gnome-character-map (1)
have been deprecated and are now symbolic links to gucharmap\&.
.SH "OPTIONS"
.PP
The following options are supported:
.TP 30
\fB\-\-font=\fIstring\fR\fR
Specify the font name and point size that you want to use to display the
characters in the character table, when you start Character Map\&.
.TP 30
.I gnome-std-options
Standard options available for use with most GNOME applications\&.  See
.BR gnome-std-options (7)
for more information\&.
.SH "EXAMPLES"
.PP
.B "Example 1: Launching Character Map"
.PP
.nf
example% \fBgucharmap \fR
.fi
.PP
.B "Example 2: Launching Character Map With Specified Font Name and Point Size"
.PP
.nf
example% \fBgucharmap -\fB-font="bitstream vera sans italic 20"\fR\fR
.fi
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.TP 8
.B 0
Application exited successfully
.TP 8
.B >0
Application exited with failure
.SH "SEE ALSO"
.PP
.BR fc-list (1),
.BR gnome-font-viewer (1),
.BR attributes (7),
.BR gnome-std-options (7)
.PP
\fICharacter Map Manual\fR
.PP
Latest version of the \fIGNOME Desktop User Guide\fR
for your platform\&.
.SH "NOTES"
.PP
Manual page written by Glynn Foster, updated by Halton Huo, Sun Microsystems
Inc\&., 2003, 2007, 2008\&.
