'\" te
.\" Copyright (c) 2017, Oracle and/or its affiliates. All rights reserved.
.TH autoconf-2.13 1 "19 May 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
autoconf-2.13 \- Generate configuration scripts (Obsolete)
.SH "DESCRIPTION"
GNU autoconf 2.13 is an obsolete version for building projects that haven't moved to something more current.
.SH NOTES
.LP
This tool is outdated, but is required by Mozilla products. It should not be used for any other purposes. Use package developer/build/autoconf for your default autoconf.
