.\"
.\" Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
.\"
.\" logilab-common.3
.\"
.TH logilab-common 3 "30 Apr 2009"
.SH NAME
logilab-common \- Common Modules used by Logilab projects
.SH DESCRIPTION
The
.I logilab-common
package contains some modules used by different Logilab
projects.

.LP
.SH Provided modules
.LP

A brief description of the available modules :
.LP

* adbh.py:
helper functions for using database advanced. Supported RDBMS
include PostgreSQL, MySQL and sqlite. See also db.py. 
.LP

* astutils:
Deprecated module. Use logilab.astng. 
.LP

* bind.py :
Deprecated module. 
Provides a way to optimize globals in certain functions by binding
their names to values provided in a dictionnary.
.LP

* cache.py :
A cache implementation with a least recently used algorithm.
.LP

* clcommands.py:
helper functions for command line programs handling different
subcommands
.LP

* cli.py :
Command line interface helper classes (for interactive programs
using the command line)
.LP

* compat.py: 
Transparent compatibility layer between different python version
.LP

* configuration.py :
Two mix-in classes to handle configuration from both command line 
(using optik/optparse) and configuration file.
.LP

* corbautils.py:
Usefull functions for use with the OmniORB CORBA library.
.LP

* daemon.py :
A daemon mix-in class.
.LP

* date.py:
date manipulation helper functions
.LP

* db.py :
A generic method to get a database connection. See also adbh.py.
.LP

* debugger.py:
pdb customization
.LP

* decorators.py:
useful decorators (cached, timed...)
.LP

* deprecation.py:
mark functions / classes as deprecated or moved
.LP

* fileutils.py :
Some file / file path manipulation utilities.
.LP

* graph.py:
graph manipulations, dot file generation
.LP

* html.py :
Deprecated module
Return an html formatted traceback from python exception infos.
.LP

* interface.py
Bases class for interfaces.
.LP

* logger.py :
Deprecated module : use logging from stdlib. 
Define a logger interface and two concrete loggers : one which prints
everything on stdout, the other using syslog.
.LP

* logging_ext.py:
extensions to stdlib's logging module
.LP

* logservice.py:
Deprecated module. Use logging from stdlib. 
.LP

* modutils.py :
Module manipulation utilities.
.LP

* monclient.py:
Deprecated module
.LP

* monserver.py:
Deprecated module
.LP

* optik_ext :
Add an abstraction level to transparently import optik classes from
optparse (python >= 2.3) or the optik package. It also defines two
new option types (regexp, csv, color, date...)
.LP

* optparser.py:
extend optparse's OptionParser to support commands 
.LP

* patricia.py :
A Python implementation of PATRICIA trie (Practical Algorithm to
Retrieve Information Coded in Alphanumeric).
.LP

* pdf_ext.py:
pdf and fdf file manipulations, with pdftk. 
.LP

* pytest.py:
unittest runner. See testlib
.LP

* shellutils.py:
Some utilities to replace shell scripts with python scripts.
.LP

* sqlgen.py :
Helper class to generate SQL strings to use with python's DB-API.
.LP

* table.py:
manage tabular data (supports column and row names, sorting, grouping...
.LP

* testlib.py :
Generic tests execution methods.
.LP

* textutils.py:
Some text manipulation utilities (ansi colorization, line wrapping,
rest support...)
.LP

* tree.py :
Base class to represent tree structure, and some others to make it
works with the visitor implementation (see below).
.LP

* umessage.py:
unicode email support
.LP

* ureports:
Provides a way to create simple reports using python objects
without care of the final formatting. Some formatters text and html
are provided.
.LP

* vcgutils.py :
utilities functions to generate file readable with Georg Sander's vcg
(Visualization of Compiler Graphs).
.LP

* visitor.py :
A generic visitor pattern implementation.
.LP

* twisted_distutils.py
This module enables the installation of plugins.tml files using standard
distutils syntax. Note that you can use this to install files that
are not twisted plugins in any package directory of your application.
.LP

* xmlrpcutils.py:
Auth support for XML RPC

.LP

.SH FILES
.TP 2.2i
.B /usr/lib/python2.6/vendor-packages/logilab/common
shared object library files

.SH AUTHORS
Sylvain Thenault (sylvain.thenault@logilab.fr)

.SH SUPPORT
python-projects@logilab.org

.SH SEE ALSO
.IR logilab-astng (3),
.IR pylint (1)
