.TH totem-audio-preview 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
totem-audio-preview \- audio previewer for the GNOME desktop\&.
.SH "SYNOPSIS"
.PP
.B "totem-audio-preview\fR [\fB\-\-mimetype\fR] [\fB\fIgst-std-options\fR\fR] \fB\fIfile\fR"
.SH "DESCRIPTION"
.PP
\fBtotem-audio-preview\fR is used internally by GNOME applications such as
.BR nautilus (1)
to provide a preview of audio files\&.  It will play audio passed via standard
input or the filename specified in the command line\&.
.SH "OPTIONS"
.PP
The following options are supported:
.TP 24
\fB\-m\fR, \fB\-\-mimetype\fR
List the supported mime-types\&.
.TP 24
.I gst-std-options
Standard options available for use with most GStreamer applications\&.  See
.BR gst-std-options (7)
for more information\&.
.SH "OPERANDS"
.PP
The following operands are supported:
.TP 24
.I file
The input \fIfile\fR\&.  This can be in any audio format that
.BR totem (1)
can play\&.
.SH "SEE ALSO"
.PP
.BR nautilus (1),
.BR totem (1),
.BR totem-video-indexer (1),
.BR totem-video-thumbnailer (1),
.BR attributes (7),
.BR gst-std-options (7)
.SH "NOTES"
.PP
Written by Brian Cameron, Sun Microsystems Inc\&., 2009\&.
