/*
 * Copyright (c) 2003, 2011, Oracle and/or its affiliates. All rights reserved.
 *
 * U.S. Government Rights - Commercial software. Government users are subject
 * to the Sun Microsystems, Inc. standard license agreement and applicable
 * provisions of the FAR and its supplements.
 *
 *
 * This distribution may include materials developed by third parties. Sun,
 * Sun Microsystems, the Sun logo and Solaris are trademarks or registered
 * trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
 *
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */
#ifndef ENTALIASMAPPINGTABLE_H
#define ENTALIASMAPPINGTABLE_H

/* function declarations */
void init_entAliasMappingTable(void);
void initialize_table_entAliasMappingTable(void);
Netsnmp_Node_Handler entAliasMappingTable_handler;

Netsnmp_First_Data_Point  entAliasMappingTable_get_first_data_point;
Netsnmp_Next_Data_Point   entAliasMappingTable_get_next_data_point;

/* column number definitions for table entAliasMappingTable */
       #define COLUMN_ENTALIASLOGICALINDEXORZERO		1
       #define COLUMN_ENTALIASMAPPINGIDENTIFIER		2

typedef struct logicalAlias_s {
    int_l entAliasLogicalIndexorZero;
    oid *entAliasMapId;
    int_l entAliasMapIdSize;
} logicalAlias;

typedef struct entAliasMappingTableEntry_s {
    int_l entPhysicalIndex;
    logicalAlias *entlogicalAliases; /*array of LogicalAlias structs*/
    struct entAliasMappingTableEntry_s *pNextEntry;
} entAliasMappingTableEntry_t;

extern int addAliasMappingTableEntry(int, int, oid*, int);
extern int deleteAliasMappingLogicalIndex(int xentLogicalIndex);
extern int deleteAliasMappingPhysicalIndex(int xentPhysicalIndex);
extern int deleteAliasMappingTableEntry(int xentPhysicalIndex, int xentLogicalIndex);





#endif /* ENTALIASMAPPINGTABLE_H */
