/*
 * Copyright (c) 2003, 2011, Oracle and/or its affiliates. All rights reserved.
 *
 * U.S. Government Rights - Commercial software. Government users are subject
 * to the Sun Microsystems, Inc. standard license agreement and applicable
 * provisions of the FAR and its supplements.
 *
 *
 * This distribution may include materials developed by third parties. Sun,
 * Sun Microsystems, the Sun logo and Solaris are trademarks or registered
 * trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
 *
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */
#ifndef ENTPHYSICALCONTAINSTABLE_H
#define ENTPHYSICALCONTAINSTABLE_H

/* function declarations */
void init_entPhysicalContainsTable(void);
void initialize_table_entPhysicalContainsTable(void);
Netsnmp_Node_Handler entPhysicalContainsTable_handler;

Netsnmp_First_Data_Point  entPhysicalContainsTable_get_first_data_point;
Netsnmp_Next_Data_Point   entPhysicalContainsTable_get_next_data_point;

/* column number definitions for table entPhysicalContainsTable */
#define COLUMN_ENTPHYSICALCHILDINDEX		1

typedef struct physIndexAndChildIndex_s {
    int_l entPhysicalIndex;
    int_l *childIndexes;      /* array of child indexes */
    struct physIndexAndChildIndex_s *pNextEntry;
} physIndexAndChildIndex_t;

typedef struct {
    physIndexAndChildIndex_t *pCurEntry;
    int_l *pCuridx;
} PhysChildtable;

/* Fix for 4915033 */
extern int addPhysicalContainsTableEntry(int xentPhysicalIndex, int xentChildIndex);
extern int* getPhysicalContainsChildren(int parentIndex);
extern int deletePhysicalContainsTableEntry(int xParentIndex, int xChildIndex);
extern int deletePhysicalContainsParentIndex(int xParentIndex);
extern int deletePhysicalContainsChildIndex(int xChildIndex);
/* End of Fix for 4915033 */

#endif /* ENTPHYSICALCONTAINSTABLE_H */
