'\" te
.TH hal-cups-utils 5 "14 Apr 2009" "SunOS 5.11" "Standards, Environments, and Macros"
.SH NAME
hal-cups-utils - automatic queue configuration for CUPS
.SH DESCRIPTION
.sp
.LP
hal-cups-utils is a Hardware Abstraction Layer (HAL) plugin module that
automatically creates print queues under the Common UNIX Printing System (CUPS)
for printers detected by HAL.  When a printer is detected by the HAL framework,
HAL activates hal-cups-utils to attempt to create a corresponding print queue
under the CUPS print service.  If the CUPS print service is not active, no
action is taken.  See http://fedorahosted.org/hal-cups-utils/ for additional
information.
.SH SEE ALSO
.sp
.LP
\fBhal\fR(5), 
.sp
http://fedorahosted.org/hal-cups-utils/
.sp
http://www.cups.org/
.sp
.LP
.SH ATTRIBUTES
.sp
.LP
See
.BR attributes (5)
for descriptions of the following attributes:
.sp
.TS
box;
cbp-1 | cbp-1
l | l .
ATTRIBUTE TYPE  ATTRIBUTE VALUE
=
Availability    print/cups/hal-cups-utils
=
Interface Stability     Volatile
.TE 
.PP
.SH NOTES
Source for hal-cups-utils is available on http://opensolaris.org.
