/*
 * Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
 *
 * U.S. Government Rights - Commercial software. Government users are subject
 * to the Sun Microsystems, Inc. standard license agreement and applicable
 * provisions of the FAR and its supplements.
 *
 *
 * This distribution may include materials developed by third parties. Sun,
 * Sun Microsystems, the Sun logo and Solaris are trademarks or registered
 * trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 1.1.1.1 2003/03/26 18:12:29 pcarroll Exp $
 */
#ifndef DEMO_MODULE_3_H
#define DEMO_MODULE_3_H

/* function declarations */
void init_init_demo_module_3(void);
void initialize_table_me1ContactInfoTable(void);
Netsnmp_Node_Handler me1ContactInfoTable_handler;

Netsnmp_First_Data_Point  me1ContactInfoTable_get_first_data_point;
Netsnmp_Next_Data_Point   me1ContactInfoTable_get_next_data_point;

/* column number definitions for table me1ContactInfoTable */
       #define COLUMN_ME1FLOORNUMBER		1
       #define COLUMN_ME1ROOMNUMBER		2
       #define COLUMN_ME1NAME		3
       #define COLUMN_ME1EXTENSION		4


typedef struct me1ContactEntry_s {
    long me1FloorNumber;
    long me1RoomNumber; 
    char me1Name[255];
    long me1Extension;
    struct me1ContactEntry_s* pNext;
} me1ContactEntry;

#endif /* DEMO_MODULE_3_H */
