/* Smalltalk from Squeak4.6 with VMMaker 4.21.5 translated as C source on 15 October 2025 2:53:31 pm */
/* Automatically generated by
	SmartSyntaxPluginCodeGenerator VMMaker-dtl.452 uuid: c05043a9-bcd9-4669-9960-d289ab89e02c
   from
	PseudoTTYPlugin VMConstruction-Plugins-PseudoTTYPlugin-dtl.4 uuid: 0a480274-7560-4dfe-bccb-7224e8835f40
 */
static char __buildInfo[] = "PseudoTTYPlugin VMConstruction-Plugins-PseudoTTYPlugin-dtl.4 uuid: 0a480274-7560-4dfe-bccb-7224e8835f40 " __DATE__ ;




/* Configuration options */
#include "sqConfig.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
/*  The virtual machine proxy definition */
#include "sqVirtualMachine.h"
/* Platform specific definitions */
#include "sqPlatformSpecific.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
#undef EXPORT
// was #undef EXPORT(returnType) but screws NorCroft cc
#define EXPORT(returnType) static returnType
#endif
#include "PseudoTTYPlugin.h"

#include "sqMemoryAccess.h"


/*** Constants ***/

/*** Function Prototypes ***/
static AsyncFile * asyncFileValueOf(sqInt oop);
#pragma export on
EXPORT(const char*) getModuleName(void);
#pragma export off
static sqInt halt(void);
#pragma export on
EXPORT(sqInt) initialiseModule(void);
EXPORT(sqInt) primPtyClose(void);
EXPORT(sqInt) primPtyForkAndExec(void);
EXPORT(sqInt) primPtyWindowSize(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
EXPORT(sqInt) shutdownModule(void);
#pragma export off
/*** Variables ***/

#ifdef SQUEAK_BUILTIN_PLUGIN
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"PseudoTTYPlugin 15 October 2025 (i)"
#else
	"PseudoTTYPlugin 15 October 2025 (e)"
#endif
;
static sqInt sCOAFfn;
static sqInt simulator;



/*	Return a pointer to the first byte of the async file record within the given Smalltalk bytes object, or nil if oop is not an async file record. */

static AsyncFile * asyncFileValueOf(sqInt oop) {
	interpreterProxy->success((!((oop & 1))) && ((interpreterProxy->isBytes(oop)) && ((interpreterProxy->slotSizeOf(oop)) == (sizeof(AsyncFile)))));
	if (interpreterProxy->failed()) {
		return null;
	}
	return ((AsyncFile *) (interpreterProxy->firstIndexableField(oop)));
}


/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

EXPORT(const char*) getModuleName(void) {
	return moduleName;
}

static sqInt halt(void) {
	;
	return null;
}


/*	We have to load AsyncFile first, to get the sessionID. */

EXPORT(sqInt) initialiseModule(void) {
	interpreterProxy->ioLoadFunctionFrom("initializeModule", "AsynchFilePlugin");
	return ptyInit();
}

EXPORT(sqInt) primPtyClose(void) {
	AsyncFile *f;
	sqInt fHandle;

	fHandle = interpreterProxy->stackValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	f = asyncFileValueOf(fHandle);
	if (!(interpreterProxy->failed())) {
		ptyClose(f);
	}
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->pop(1);
	return null;
}

EXPORT(sqInt) primPtyForkAndExec(void) {
	char *cmdIdx;
	sqInt fOop;
	char *argIdx;
	AsyncFile *f;
	sqInt cmdLen;
	sqInt argLen;
	sqInt cmd;
	sqInt args;
	sqInt semaIndex;

	cmd = interpreterProxy->stackValue(2);
	args = interpreterProxy->stackValue(1);
	semaIndex = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->success(interpreterProxy->isBytes(cmd));
	interpreterProxy->success(interpreterProxy->isPointers(args));
	if (interpreterProxy->failed()) {
		return null;
	}
	cmdIdx = interpreterProxy->firstIndexableField(cmd);

	/* in bytes */

	cmdLen = interpreterProxy->slotSizeOf(cmd);
	argIdx = interpreterProxy->firstIndexableField(args);

	/* in fields */

	argLen = interpreterProxy->slotSizeOf(args);
	fOop = interpreterProxy->instantiateClassindexableSize(interpreterProxy->classByteArray(), sizeof(AsyncFile));
	f = asyncFileValueOf(fOop);
	if (!(interpreterProxy->failed())) {
		ptyForkAndExec(f, semaIndex, cmdIdx, cmdLen, argIdx, argLen);
	}
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->popthenPush(4, fOop);
	return null;
}

EXPORT(sqInt) primPtyWindowSize(void) {
	AsyncFile *f;
	sqInt fHandle;
	sqInt cols;
	sqInt rows;

	fHandle = interpreterProxy->stackValue(2);
	cols = interpreterProxy->stackIntegerValue(1);
	rows = interpreterProxy->stackIntegerValue(0);
	if (interpreterProxy->failed()) {
		return null;
	}
	f = asyncFileValueOf(fHandle);
	if (!(interpreterProxy->failed())) {
		ptyWindowSize(f, cols, rows);
	}
	if (interpreterProxy->failed()) {
		return null;
	}
	interpreterProxy->pop(3);
	return null;
}


/*	Note: This is coded so that is can be run from Squeak. */

EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter) {
	sqInt ok;

	interpreterProxy = anInterpreter;
	ok = interpreterProxy->majorVersion() == VM_PROXY_MAJOR;
	if (ok == 0) {
		return 0;
	}
	ok = interpreterProxy->minorVersion() >= VM_PROXY_MINOR;
	return ok;
}

EXPORT(sqInt) shutdownModule(void) {
	return ptyShutdown();
}


#ifdef SQUEAK_BUILTIN_PLUGIN


void* PseudoTTYPlugin_exports[][3] = {
	{"PseudoTTYPlugin", "primPtyWindowSize", (void*)primPtyWindowSize},
	{"PseudoTTYPlugin", "shutdownModule", (void*)shutdownModule},
	{"PseudoTTYPlugin", "primPtyClose", (void*)primPtyClose},
	{"PseudoTTYPlugin", "setInterpreter", (void*)setInterpreter},
	{"PseudoTTYPlugin", "initialiseModule", (void*)initialiseModule},
	{"PseudoTTYPlugin", "primPtyForkAndExec", (void*)primPtyForkAndExec},
	{"PseudoTTYPlugin", "getModuleName", (void*)getModuleName},
	{NULL, NULL, NULL}
};


#endif /* ifdef SQ_BUILTIN_PLUGIN */

