'\" te
.TH gam_server 1 "25 Mar 2008" "SunOS 5.11" "User Commands"
.SH "NAME"
gam_server \- The Gamin server gathers file events from the kernel and sends
these events to clients\&.
.SH "SYNOPSIS"
.PP
/usr/lib/\fBgam_server\fR
.SH "DESCRIPTION"
.PP
Gamin uses a client-server model\&.  gam_server is the server which centralizes
client requests for monitoring files, gathers file events via File Event
Notification kernel API methods (see
\fBport_create\fR(3C)), 
and then sends modification events to application clients\&.  It also shares
file events when multiple applications monitor the same file\&.
  
.PP
For configuring gam_server refer to
\fBhttp://www\&.gnome\&.org/~veillard/gamin/config\&.html\fR
  
.SH "ATTRIBUTES"
.PP
See \fBattributes\fR(7)
for descriptions of the following attributes:
  
.sp
.SH "SEE ALSO"
.PP
\fBport_create\fR(3C),
\fBlibgamin-1\fR(3),
\fBattributes\fR(7)
.PP
Gamin Homepage: \fBhttp://www\&.gnome\&.org/~veillard/gamin\fR
.SH "NOTES"
.PP
Written by Lin Ma, Sun Microsystems Inc\&., 2008\&.
...\" created by instant / solbook-to-man, Tue 27 Jan 2015, 17:22
...\" LSARC 2007/398 Gamin - the File Alteration Monitor
