'\" t
.\"
.\" This man page created by Oracle to provide an overview of the Tk
.\" library.
.\"
.TH libtk 3 "16 July 2001"
.SH NAME
libtk \- Tcl GUI Toolkit
.SH SYNOPSIS
.LP
.B cc
.RI "[ " "flag " \|.\|.\|. ] " "file \|.\|.\|."
.RI "[ " "library" " \|.\|.\|. ]"
.B \-ltk8.5
.sp 1n
.SH DESCRIPTION
The Tk library is a collection of graphical user interfaces useful for
create powerful GUIs quickly. For more detail, see section 3 man pages 
specific to the library interfaces.  Additional information is also 
available from the Tcl Developer Xchange site:
.IP
.B http://tcl.tk/
.LP
.SH LICENSE
The Tk software is copyrighted by the Regents of the University of
California, Oracle, Scriptics Corporation,
and other parties. 
.SH FILES
.PD 0
.TP 20
/usr/lib/libtk8.5.so
shared object
.TP
/usr/lib/libtkstub8.5.a
stubs library
.PD
.SH "SEE ALSO"
libtcl(3)
