.TH notify-send 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
notify-send \- a CLI program to send desktop notifications
.SH "SYNOPSIS"
.PP
\fBnotify-send\fR [\fB\-\-help\fR] [\fB\-\-urgency=\fIlevel\fR\fR] [\fB\-\-expire-time=\fItime\fR\fR] [\fB\-\-icon=\fIicon,icon\&.\&.\&.\fR\fR] [\fB\-\-category=\fItype,type\&.\&.\&.\fR\fR] [\fB\-\-hint=\fItype:name:value\fR\fR] [\fIsummary\fR] [\fIbody\fR]
.SH "DESCRIPTION"
.PP
Using notify-send, you can send desktop notifications from the command line
to the user via a notification daemon\&. The notifications are used to inform
the user about an asynchronous event or display some useful information without
getting in the user\&'s way\&.
.SH "OPTIONS"
.PP
The following options are supported:
.TP 24
\fB\-?\fR, \fB\-\-help\fR
Display help text\&.
.TP 24
\fB\-u\fR, \fB\-\-urgency=\fIlevel\fR\fR
Specifies the urgency level, including low, normal and critical\&.
.TP 24
\fB\-t\fR, \fB\-\-expire-time=\fItime\fR\fR
Specifies the timeout in milliseconds at which to expire the notification\&.
.TP 24
\fB\-i\fR, \fB\-\-icon=\fIicons\fR\fR
Specifies an icon filename or stock icon to display\&.
.TP 24
\fB\-c\fR, \fB\-\-category=\fItypes\fR\fR
Specifies the notification category\&.
.TP 24
\fB\-h\fR, \fB\-\-hint=\fIhint\fR\fR
Specifies basic extra data to pass\&. The format is type:name:value and
valid types are int, double, string and byte
.TP 24
\fB\-v\fR, \fB\-\-version\fR
Display version information\&.
.SH "EXIT STATUS"
.PP
.TP 4
0
All information was written successfully\&.
.TP 4
>0
An error occurred\&.
.SH "SEE ALSO"
.PP
.BR libnotify (3lib)
.PP
The Desktop Notification Spec on
\fBhttp://www\&.galago-project\&.org/specs/notification/\fR\&.
.SH "NOTES"
.PP
Written by Jedy Wang, Sun Microsystems Inc\&., 2007\&.
