#!/usr/ruby/1.8/bin/ruby
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
 
#
# Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
#

print "update_rubygems has been deprecated, please use:\n\n"
print "\t\tgem update --system\n\n"
print "Note: Manually updating the RubyGems version included in the "
print "OpenSolaris Ruby packages will overwrite files in those packages\n\n"

