.TH gdm-screenshot 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
gdm-screenshot \- GDM Screenshot Application
.SH "SYNOPSIS"
.PP
\fBgdm-screenshot\fR [\fB\-\-debug\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
\fBgdm-screenshot\fR is a utility for generating a PNG image of the
currently running GDM login GUI screen\&.  It is normally launched by pressing
the key defined as the screenshot keybinding\&.  The resulting image is saved
to a file named \fB/var/run/gdm/greeter/GDM-Screenshot\&.png\fR\&.
.SH "OPTIONS"
.PP
The following options are supported:
.TP 16
\fB\-d\fR, \fB\-\-debug\fR
Display debug output\&.
.TP 16
\fB\-h\fR, \fB\-\-help\fR
Display detailed usage message\&.
.SH "EXAMPLES"
.PP
.B "Example 1: Take a screenshot\&."
.PP
.PP
.nf
example% \fBgdm-screenshot\fR
.fi
.SH "FILES"
.PP
The following files are used by this application:
.sp
.ne 2
.mk
.B /usr/bin/gdm-screenshot
Executable for GDM Screenshot Application\&.
.TP 4
.B /var/run/gdm/greeter/GDM-Screenshot\&.png
Resulting image file created when \fBgdm-screenshot\fR is run\&.
.SH "SEE ALSO"
.PP
Latest version of the \fIGNOME Desktop User Guide\fR
for your platform\&.
.PP
.BR gdmflexiserver (1),
.BR gdm (1m),
.BR attributes (7)
.SH "NOTES"
.PP
Written by Brian Cameron, Sun Microsystems Inc\&., 2009\&.
