#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2025 Marcel Telka
#

%patch% 01-dbus-daemon.patch

%include-3%
# https://github.com/martinpitt/python-dbusmock/issues/247
PYTEST_ADDOPTS += --deselect tests/test_code.py::StaticCodeTests::test_black
# https://github.com/martinpitt/python-dbusmock/issues/246
PYTEST_ADDOPTS += --deselect tests/test_code.py::StaticCodeTests::test_pylint

# Manually added test dependencies
TEST_REQUIRED_PACKAGES += system/library/dbus
