'\" t
.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\" Copyright 2010 Sun Microsystems, Inc.  All rights reserved.
.\" Use is subject to license terms.
.\"
.\" #ident	"@(#)pgadmin3.1	1.2	10/03/16 SMI"
.\"
.TH "pgadmin3" "1" "" "" "User Commands"
.SH NAME
pgAdmin III \- administration and development GUI for PostgreSQL
.SH SYNOPSIS
.sp
\fBpgadmin3\fR [ \fB\fIoption\fB\fR\fI...\fR ]  

.SH DESCRIPTION
pgAdmin III is the most popular and feature rich Open Source administration
and development platform for PostgreSQL, the most advanced Open Source 
database in the world. pgAdmin III is designed to answer the needs of most
users, from writing simple SQL queries to developing complex databases. 
It includes a graphical administration interface, an SQL query tool, 
a procedural code editor and much more.

This program is a graphical application and the binary file is available
in /usr/bin. Simply type "pgadmin3" on a command line to launch the GUI. 
However, some of the features can be accessed through command line.

.SH "OPTIONS"

The following options are supported:
.TP
\fB-h\fR
.TP
\fB--help\fR
Display command line option help
.TP
\fB-s \fIserver\fB\fR
.TP
\fB--server=\fIserver\fB\fR
Auto connect to the specified server. \fIserver\fR is the description
entered when you added the server to the treeview in pgAdmin, 
quoted if required. If multiple servers are registered with the same 
description, the first found will be auto-connected.
.TP
\fB-q\fR
.TP
\fB--query\fR
Open a Query Tool window upon connection. If used together with the
-s \fIserver\fR option, the query tool will automatically be 
connected to this server. If used alone, a dialog box will appear 
prompting for the connection information. This switch cannot be used
together with the -qc \fIconnection\fR option.
.TP
\fB-qc \fIconnection\fB\fR
.TP
\fB--queryconnect=\fIconnection\fB\fR
Open a Query Tool window upon connection. The query tool will 
automatically be connected to the server specified in the connection 
string. This option cannot be used together with the -q switch.
.TP
\fB-cm \fIfile\fB\fR
.TP
\fB--configfile=\fIfile\fB\fR
Edit the specified postgresql.conf config file.
.TP
\fB-ch \fIfile\fB\fR
.TP
\fB--hbafile=file\fR
Edit the specified pg_hba.conf config file.
.TP
\fB-c \fIfile\fB\fR
.TP
\fB-file=\fIfile\fB\fR
Edit the config files in specified cluster directory.
.TP
\fB-t\fR
.TP
\fB--testmode\fR
Start in dialogue translation test mode. This mode allows each dialogue
to be viewed without running the application to assist with string 
translation.
.PP

.\" Begin Sun update
.SH ATTRIBUTES
See
.BR attributes (5)
for descriptions of the following attributes:
.sp
.TS
box;
cbp-1 | cbp-1
l | l .
ATTRIBUTE TYPE	ATTRIBUTE VALUE
=
Availability	database/postgres/pgadmin
=
Interface Stability	Committed
.TE

.SH NOTES
You may find useful informations in the help menu of pgadmin3.
You may also find Solaris specific PostgreSQL informations in "postgres_82"
man page. Source for pgAdmin3 is available on http://opensolaris.org.
.\" End Sun update


.SH SEE ALSO
.PP
pgagent(1), postgres_82(1), initdb(1), pg_ctl(1), postgres(1), postmaster(1)

.SH REFERENCES
.PP
http://www.pgadmin.org
