#!/bin/ksh -p
#
# Copyright (c) 2008, 2011, Oracle and/or its affiliates. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, and/or sell copies of the Software, and to permit persons
# to whom the Software is furnished to do so, provided that the above
# copyright notice(s) and this permission notice appear in all copies of
# the Software and that both the above copyright notice(s) and this
# permission notice appear in supporting documentation.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
# OF THIRD PARTY RIGHTS. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# HOLDERS INCLUDED IN THIS NOTICE BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL
# INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY DAMAGES WHATSOEVER RESULTING
# FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
# Except as contained in this notice, the name of a copyright holder
# shall not be used in advertising or otherwise to promote the sale, use
# or other dealings in this Software without prior written authorization
# of the copyright holder.
#
###########################################################################
#
PATH=/usr/bin:/usr/sbin

. /lib/svc/share/smf_include.sh

USAGE="Usage: $0 { start | refresh }"
FIND_NEWER=/usr/share/desktop-cache/find_newer

if [ $# -ne 1 ] ; then
    echo $USAGE
    exit 2
fi

#
# IF the mime cache exist then :
#   get the list of mime type files newer than the cache file
# ELSE
#   make list greater than zero to generate a cache
#
# generate the cache
#

MIMEFILE="/usr/share/applications/mimeinfo.cache"
MIMEDIR="/usr/share/applications"

start_desktop_mime_cache () {

test -w $MIMEDIR || { 
  echo "$MIMEDIR is not writable, skipping."
  return
}

if [ -a $MIMEFILE ]; then
  RESULT=`${FIND_NEWER} -f -c -m \
      --newer $MIMEFILE \
      /usr/share/applications 2>/dev/null`
else
  RESULT="no cache found"
fi

if [ -n "$RESULT" ]; then 
  test -x /usr/bin/update-desktop-database || {
    echo "update-desktop-database not installed"
    return
  }
  echo "updating desktop file cache" 
  /usr/bin/update-desktop-database -q
  if [ $? -ne 0 ]; then
    echo "update-mime-database exited with an error while generating the desktop file cache $MIMEFILE"
    exit $SMF_EXIT_ERR_FATAL
  else
    echo "desktop file cache $MIMEFILE generated"
  fi
fi
}

refresh_desktop_mime_cache () {

test -w $MIMEDIR || { 
  echo "$MIMEDIR is not writable, skipping."
  return
}

if [ -a $MIMEFILE ]; then
  RESULT=`/usr/bin/find /usr/share/applications ! -type d -follow 2>/dev/null`
else
  RESULT="no cache found"
fi

if [ -n "$RESULT" ]; then 
  test -x /usr/bin/update-desktop-database || {
    echo "update-desktop-database not installed"
    return
  }
  echo "updating desktop file cache" 
  /usr/bin/update-desktop-database -q
  if [ $? -ne 0 ]; then
    echo "update-mime-database exited with an error while generating the desktop file cache $MIMEFILE"
    exit $SMF_EXIT_ERR_FATAL
  else
    echo "desktop file cache $MIMEFILE generated"
  fi
fi
}

METHOD="$1"

case "$METHOD" in
    'start')
	# Continue with rest of script
	;;
    'refresh')
	;;
    -*)
	echo $USAGE
	exit 2
	;;
    *)
	echo "Invalid method $METHOD"
	exit 2
	;;
esac

${METHOD}_desktop_mime_cache

exit $SMF_EXIT_OK
