#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2023 Marcel Telka
#

%patch% 01-no-pytest-mypy-testing.patch
%patch% 02-no-pre-commit.patch
%patch% 03-no-mypy.patch

%hook-begin%
# This is the latest version with Python 3.9 support
VERSION=5.15.1

%include-2%
# traitlets >= 5.16.0 requires Python >= 3.10
PYTHON_VERSIONS = 3.9
%include-3%
# This project does not support tox so we need to provide test requirements
# manually.
TEST_REQUIREMENTS_EXTRAS += test

# https://github.com/ipython/traitlets/issues/925
PYTEST_ADDOPTS += --deselect tests/config/test_argcomplete.py::TestArgcomplete::test_complete_simple_app
PYTEST_ADDOPTS += --deselect tests/config/test_argcomplete.py::TestArgcomplete::test_complete_custom_completers
PYTEST_ADDOPTS += --deselect tests/config/test_argcomplete.py::TestArgcomplete::test_complete_subcommands_subapp1

# Testing needs to find the tests module in the build directory
COMPONENT_TEST_ENV += PYTHONPATH=$(PROTOPYTHONVENDORDIR):$(COMPONENT_TEST_DIR)
%hook-manifest%
# We need versioned package only, so we cannot have PYVER in the p5m file name
mv "$DISTRIBUTION-PYVER.p5m" "$DISTRIBUTION-39.p5m"
sed -i -e 's/\$(PYVER)/3.9/g' -e 's/\$(PYV)/39/g' "$DISTRIBUTION-39.p5m"
MANIFEST="$DISTRIBUTION-39.p5m"
