.TH ck-launch-session 1 "12 Sep 2016"
.SH "NAME"
ck-launch-session \- ConsoleKit session launcher
.SH "SYNOPSIS"
.PP
\fBck-launch-session\fR \fB\fIcommand\fR\fR
.SH "DESCRIPTION"
.PP
\fBck-launch-session\fR is a utility for starting a command in its own
ConsoleKit session\&.  This would be useful if a user wanted to start their own
session via a \fBstartx\fR script and have it registered with
ConsoleKit, for example\&.
.SH "OPERANDS"
.PP
The following operands are supported:
.TP 10
.I command
Start the specified \fIcommand\fR in its own ConsoleKit
session\&.
.SH "EXAMPLES"
.PP
\fBExample 1: Launch the \fBstartx\fR command in its own ConsoleKit
session\fR
.PP
.PP
.nf
example% \fBck-launch-session \fBstartx\fR\fR
.fi
.SH "FILES"
.PP
The following files are used by this application:
.TP 10
.B /usr/bin/ck-launch-session
Executable for ConsoleKit session launcher\&.
.SH "SEE ALSO"
.PP
\fBck-history\fR(1),
\fBck-list-sessions\fR(1),
\fBck-seat-tool\fR(8),
\fBconsole-kit-daemon\fR(8),
\fBgdm\fR(8),
\fBattributes\fR(7)
