'\" t
.\" Manual page created by The XFree86 Project, under this license:
.\"
.\" Copyright (C) 1994-2003 The XFree86 Project, Inc.  All Rights Reserved.
.\" 
.\" Permission is hereby granted, free of charge, to any person obtaining a 
.\" copy of this software and associated documentation files (the "Software"),
.\" to deal in the Software without restriction, including without limitation 
.\" the rights to use, copy, modify, merge, publish, distribute, sublicense, 
.\" and/or sell copies of the Software, and to permit persons to whom the 
.\" Software is furnished to do so, subject to the following conditions:
.\" 
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL 
.\" THE XFREE86 PROJECT BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
.\" WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF 
.\" OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE 
.\" SOFTWARE.
.\" 
.\" Except as contained in this notice, the name of the XFree86 Project shall 
.\" not be used in advertising or otherwise to promote the sale, use or other 
.\" dealings in this Software without prior written authorization from the 
.\" XFree86 Project.
.\"
.TH GLXGEARS 1 Version\ 6.9.0 X.Org
.SH NAME
glxgears \- GLX version of the infamous "gears" GL demo.
.SH SYNOPSIS
.B "glxgears"
[\-info]
[\-display \fIdisplayname\fP]
.SH DESCRIPTION
.PP
.I glxgears
is a GLX demo that draws three rotating gears, and prints out framerate
information to stdout.
Command line options include:
.TP 8
.B \-info
Print out GL implementation information before running the demo.
.TP 8
.BI "\-display " displayname
Specify the display to query.
.SH ENVIRONMENT
.PP
.TP 8
.B DISPLAY
To get the default host, display number, and screen.
.SH "SEE ALSO"
glxinfo(1)
.SH AUTHOR
Ported to straight GLX by Brian Paul.
.\" Begin Sun update
.\"

.SH ATTRIBUTES
See
.BR attributes (5)
for descriptions of the following attributes:
.sp
.TS
box;
cbp-1 | cbp-1
l | l .
ATTRIBUTE TYPE	ATTRIBUTE VALUE
=
Availability 	pkg:/x11/demo/mesa-demos
Interface Stability 	Volatile 
.TE 
.\" End Sun update
