#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2022 Marcel Telka
#

%patch% 01-test-fix-pyproject-fmt-path.patch
%patch% 02-tox-cov-proto.patch

%hook-begin%
# https://github.com/tox-dev/toml-fmt/issues/13
DOWNLOAD_URL='https://github.com/tox-dev/toml-fmt/archive/refs/tags/pyproject-fmt/$(HUMAN_VERSION).tar.gz'

%include-2%
COMPONENT_SRC = toml-fmt-pyproject-fmt-$(HUMAN_VERSION)
COMPONENT_SUBDIR = pyproject-fmt
%include-3%
# https://www.illumos.org/issues/15767
LD_Z_IGNORE=

# During testing the /usr/bin is added to PATH (due to a bug) and so when we
# try to run pyproject-fmt we always run the installed one, not the currently
# built one in the proto area.
#
# See also https://github.com/fedora-python/tox-current-env/issues/68
TEST_CONFLICTING_PACKAGES.python += library/python/pyproject-fmt

# Random directory name
COMPONENT_TEST_TRANSFORMS += "-e 's|/tmp/.*/garbage[^/]*|\$$(TMPDIR)|'"
