'\" te
.\" Copyright (c) 2009, 2016, Oracle and/or its affiliates. All rights reserved.
.TH openssl 7 "28 Oct 2015" "SunOS 5.12" "Standards, Environments, and Macros"
.SH NAME
openssl \- OpenSSL cryptographic and Secure Sockets Layer toolkit
.SH DESCRIPTION
.sp
.LP
OpenSSL is a cryptography toolkit that implements the Transport Layer Security (TLS v1) network protocols.  This version of OpenSSL no longer supports the Secure Sockets Layer (SSLv2/v3) network protocols.
.sp
.LP
The following features are omitted  from  the  binaries  for issues  including but not limited to patents, trademark, and US export restrictions: IDEA, MDC2, RC3,  RC5, 4758_CCA Engine, AEP Engine, Atalla Engine, CAPI Engine, CHIL Engine, CSWIFT Engine, GMP Engine, GOST Engine, NURON  Engine, PadLock Engine, Sureware Engine, and UBSEC Engine.
.SS "The Dynamic Engine Support"
.sp
.LP
The dynamic engine support has been enabled, which allows an external engine, in the form of a shared library, to be dynamically bound and used by an OpenSSL-based application.
.sp
.LP
Run the following command to see if the dynamic engine is supported:
.sp
.in +2
.nf
$ \fBopenssl engine dynamic\fR
(dynamic) Dynamic engine loading support
.fi
.in -2
.sp

.SS "The PKCS#11 Engine"
.sp
.LP
The PKCS#11 engine has been included with ENGINE name \fBpkcs11\fR. The engine was developed in Sun and is not integrated in the OpenSSL project.
.sp
.LP
The PKCS#11 engine is a dynamic engine, and it is configured to use the Oracle Solaris Cryptographic Framework. See \fBcryptoadm\fR(8) for configuration information.
.sp
.LP
The PKCS#11 engine can support the following set of mechanisms: \fBAES-128-CBC\fR\fR, \fB \fBAES-192-CBC\fR, \fBAES-256-CBC\fR, \fBAES-128-CTR\fR, \fBAES-192-CTR\fR, \fBAES-256-CTR\fR, \fBAES-128-ECB\fR, \fBAES-192-ECB\fR, \fBAES-256-ECB\fR, \fBBF-CBC\fR, \fBDES-CBC\fR, \fBDES-ECB\fR, \fBDES-EDE3\fR, \fBDES-EDE3-CBC\fR, \fBDH\fR, \fBDSA\fR, \fBMD5\fR, \fBRAND\fR, \fBRC4\fR, \fBRSA\fR, \fBSHA1\fR, \fBSHA224\fR, \fBSHA256\fR, \fBSHA384\fR and \fBSHA512\fR.
.sp
.LP
The set of mechanisms available depends on installed Crypto Framework providers. To see what mechanisms can be offloaded to the Cryptographic Framework through the PKCS#11 engine on a given machine, run the following command:
.sp
.in +2
.nf
$ \fB/usr/bin/openssl engine dynamic -pre SO_PATH:/lib/openssl/engines/64/libpk11.so -pre LOAD -t -c\fR
.fi
.in -2
.sp

.sp
.LP
In order to verify the use of the PKCS#11 engine and the use of hardware acceleration with the OpenSSL application, you must specify the EVP option. EVP stands for \fBEnVeloPE\fR API, which is the API applications such as Apache use to access OpenSSL cryptography. Use the EVP option to get the most accurate \fBopenssl speed\fR results.
.sp
.in +2
.nf
$ \fB/usr/bin/openssl speed -evp aes-128-cbc -engine pkcs11\fR
.fi
.in -2
.sp

.sp
.LP
Due to requirements of the PKCS#11 standard regarding \fBfork\fR(2) behavior, some applications that use the OpenSSL EVP interfaces and \fBfork()\fR with active \fBcrypto\fR contexts might experience unexpected behavior.
.SS "Using FIPS Mode"
.sp
.LP
FIPS-140 capable OpenSSL is available in Oracle Solaris.
.sp
.LP
The IPS package mediator feature is used to activate the non-FIPS-140 version or the FIPS-140 version of OpenSSL.
.sp
.LP
By default, the non-FIPS-140 version (\fBdefault\fR implementation) is activated. Use the \fBpkg set-mediator\fR command to switch to the FIPS-140 version of OpenSSL:
.sp
.in +2
.nf
# \fBpkg set-mediator -I fips-140 openssl\fR
.fi
.in -2
.sp

.sp
.LP
To switch back to the default non-FIPS-140 version, use the following command:
.sp
.in +2
.nf
# \fBpkg set-mediator -I default openssl\fR
.fi
.in -2
.sp

.sp
.LP
Reboot is required to enforce the change system-wide.
.sp
.LP
See \fIManaging Encryption and Certificates in Oracle Solaris\fR for more details.
.sp
.LP
When the FIPS-140 version of OpenSSL is activated, an application can run in FIPS-140 mode or non-FIPS-140 mode. An application must explicitly call \fBFIPS_mode_set()\fR in order to activate FIPS-140 mode.
.SS "Building an OpenSSL Application"
.sp
.LP
To build an OpenSSL application, use the following \fBcc\fR command line options:
.sp
.in +2
.nf
cc [ \fIflag\fR... ] \fIfile\fR... -lcrypto -lssl [ \fIlibrary\fR... ]
.fi
.in -2

.SS "Accessing RSA Keys in PKCS#11 Keystores"
.sp
.LP
OpenSSL can access RSA keys in PKCS#11 keystores using the following functions of the ENGINE API: 
.sp
.in +2
.nf
EVP_PKEY *ENGINE_load_private_key(ENGINE *e,
 const char *key_id, UI_METHOD *ui_method,
 void *callback_data)

EVP_PKEY *ENGINE_load_public_key(ENGINE *e,
 const char *key_id, UI_METHOD *ui_method,
 void *callback_data)
.fi
.in -2

.sp
.LP
\fBkey_id\fR, formerly for filenames only, can be now also set to a \fBPKCS#11 URI\fR. The \fBEVP_PKEY\fR structure is newly allocated and caller is responsible to free the structure later. See the \fBpkcs11_parse_uri\fR(7) man page for the PKCS#11 URI attributes supported by Solaris.
.sp

.sp
.LP
The PKCS#11 engine uses the keystore for the slot chosen for public key operations, which is \fBmetaslot\fR on a standard configured machine. The only mandatory keyword is \fBobject\fR which is the key object label. For information on how to use a different, possibly hardware, keystore with \fBmetaslot\fR, see \fBlibpkcs11\fR(3LIB).
.sp
.LP
Due to fork safety issues the application must re-login if the child continues to use the PKCS#11 engine. It is done inside of the engine automatically if fork is detected.  Alternatively, an environment variable \fBOPENSSL_PKCS11_PIN_CACHING_POLICY\fR can be used to allow the PIN to be cached in memory and reused in the child. It can be set to \fBnone\fR which is the default, \fBmemory\fR to store the PIN in memory, and \fBmlocked-memory\fR to keep the PIN in a locked page using \fBmlock\fR(3C). \fBPRIV_PROC_LOCK_MEMORY\fR privilege is required in that case.
.sp
.LP
The PKCS#11 engine uses the public components as a search key to get a PKCS#11 object handle to the private key.
.sp
.LP
To use the RSA keys by reference, high level API functions such as \fBRSA_public_decrypt()\fR, \fBEVP_PKEY_set1_RSA()\fR, or \fBEVP_SignInit()\fR must be used. Low level functions might go around the engine and fail to make use of the feature.
.SS "OpenSSL Thread and Fork Safety"
.sp
.LP
OpenSSL provides the following interface for consumers to set the callback functions
for its own implementation of locking and thread identification:
.in +2
    \fBCRYPTO_set_locking_callback()
    CRYPTO_set_dynlock_create_callback()
    CRYPTO_set_dynlock_lock_callback()
    CRYPTO_set_dynlock_destroy_callback()
    CRYPTO_set_add_lock_callback()
    CRYPTO_THREADID_set_callback()
    CRYPTO_set_id_callback()\fR
.in
.LP
Setting of the callback functions by a library can lead to segmentation fault
if the library is unloaded while other parts of the stack are still using OpenSSL.
.LP
In order to prevent this issue, OpenSSL on Oracle Solaris implements those locking and
thread identification functions internally within OpenSSL.  An application or library may
still call those functions but setting of their own callback function will be ignored.
.sp
.LP
.SS "Additional Documentation"
.sp
.LP
Extensive additional documentation for OpenSSL modules is available in the \fB/usr/share/man/man1openssl\fR, \fB/usr/share/man/man3openssl\fR, \fB/usr/share/man/man5openssl\fR, and \fB/usr/share/man/man7openssl\fR directories.
.sp
.LP
To view the license terms, attribution, and copyright for OpenSSL, run \fBpkg info --license library/security/openssl\fR.
.SH EXAMPLES
.LP
\fBExample 1 \fRGenerating and Printing a Public Key
.sp
.LP
The following example generates and prints a public key stored in an already initialized PKCS#11 keystore. Notice the use of \fB-engine pkcs11\fR and \fB-inform e\fR.

.sp
.in +2
.nf
$ \fBpktool gencert keystore=pkcs11 label=mykey \
   subject="CN=test" keytype=rsa keylen=1024 serial=01\fR
$ \fBopenssl rsa -in "pkcs11:object=mykey?pin-source=builtin-dialog"\
   -pubout -text -engine pkcs11 -inform e\fR
.fi
.in -2
.sp

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(7) for a description of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Availabilitylibrary/security/openssl
_
Interface StabilityPass-through Uncommitted
.TE

.SH SEE ALSO
.sp
.LP
\fBcrle\fR(1), \fBcryptoadm\fR(8), \fBlibpkcs11\fR(3LIB), \fBpkcs11_parse_uri\fR(7), \fBattributes\fR(7), \fBprivileges\fR(7)
.sp
.LP
\fB/usr/share/man/man1openssl/openssl.1openssl\fR, \fB/usr/share/man/man1openssl/CRYPTO_num_locks.3openssl\fR, \fB/usr/share/man/man3openssl/engine.3\fR, \fB/usr/share/man/man3openssl/evp.3\fR
