.TH gnome-font-viewer 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
gnome-font-viewer \- preview fonts
.SH "SYNOPSIS"
.PP
.B "gnome-font-viewer\fR \fB\fIfilename\fR"
.SH "DESCRIPTION"
.PP
Use \fBgnome-font-viewer\fR, the Font Viewer, to preview fonts and
display information about a specified font\&. You can use the Font Viewer to
display the name, style, type, size, version, and copyright of the font\&.
.PP
To browse the fonts installed on your system, open a file manager window
and enter the following URI in the location bar:
.PP
.nf
.B "fonts:///"
.fi
.PP
Double-click on an icon to display a preview of the font\&.
.SH "OPERANDS"
.PP
The following operands are supported:
.TP 16
.I filename
The name of the font file to be viewed\&.
.SH "EXAMPLES"
.PP
.B "Example 1: Viewing the test\&.ttf Font in the Font Viewer"
.PP
.PP
.nf
example% \fBgnome-font-viewer test\&.ttf\fR
.fi
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.TP 9
.B 0
Application
exited successfully
.TP 9
.B >0
Application
exited with failure
.SH "SEE ALSO"
.PP
Latest version of the \fIGNOME Desktop User Guide\fR
for your platform\&.
.PP
.BR nautilus (1),
.BR attributes (7)
.SH "NOTES"
.PP
Written by Glynn Foster, Sun Microsystems Inc\&., 2004, 2007\&.
