In-house patch to use supported sed flags and to remove gzipping of man pages

--- rabbitmq-server-3.6.1/Makefile.orig  2016-03-31 14:49:40.661997085 -0700
+++ rabbitmq-server-3.6.1/Makefile    2016-03-31 14:55:24.094181414 -0700
@@ -82,7 +82,7 @@ ifdef CREDIT_FLOW_TRACING
 RMQ_ERLC_OPTS += -DCREDIT_FLOW_TRACING=true
 endif

-ERTS_VER := $(shell erl -version 2>&1 | sed -E 's/.* version //')
+ERTS_VER := $(shell erl -version 2>&1 | sed -e 's/.* version //')
 USE_SPECS_MIN_ERTS_VER = 5.11
 ifeq ($(call compare_version,$(ERTS_VER),$(USE_SPECS_MIN_ERTS_VER),>=),true)
 RMQ_ERLC_OPTS += -Duse_specs
@@ -391,8 +391,8 @@ install-man: manpages
 	for section in $$sections; do \
 		mkdir -p $(DESTDIR)$(MANDIR)/man$$section; \
 		for manpage in $(DOCS_DIR)/*.$$section; do \
-			gzip < $$manpage \
-			 > $(DESTDIR)$(MANDIR)/man$$section/$$(basename $$manpage).gz; \
+			cp $$manpage \
+			 $(DESTDIR)$(MANDIR)/man$$section/$$(basename $$manpage); \
 		done; \
 	done

