'\" te
.\" Copyright (c) 1999, 2011, Oracle and/or its affiliates. All rights reserved.
.TH zoneinfo 4 "21 Jun 1999" "SunOS 5.11" "File Formats"
.SH NAME
zoneinfo \- timezone information
.SH DESCRIPTION
.sp
.LP
For notes regarding the zoneinfo timezones, see \fB/usr/share/lib/zoneinfo/src/README\fR.
