'\" te
.\" Portions Copyright (c) 2008, 2012, Oracle and/or its affiliates. All rights reserved.
.\" This manual page is derived from documentation obtained from the OpenSC organization (www.opensc-project.org). This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.TH pkcs11_inspect 1 "2012 年 1 月 18 日" "SunOS 5.12" "用户命令"
.SH 名称
pkcs11_inspect \- 打印证书内容
.SH 用法概要
.LP
.nf
\fB/usr/lib/pam_pkcs11/pkcs11_inspect\fR [debug] [config_file=\fIfilename\fR]
.fi

.SH 描述
.sp
.LP
\fBpkcs11_inspect\fR 使用 \fBpam_pkcs11\fR 库基础结构获取及显示证书内容。
.sp
.LP
\fBpkcs11_inspect\fR 使用与 \fBpam_pkcs11\fR(5) PAM 模块相同的配置文件及参数。它装入定义的映射器模块，并使用它们在证书中查看需要的条目，即 \fBms_mapper\fR 查找 \fBms UPN\fR 条目等。
.sp
.LP
映射器模块在证书中找到正确的条目时，它会转换为 \fBUTF-8\fR 并将其打印到 \fBstdout\fR。 
.SH 选项
.sp
.LP
支持以下选项：
.sp
.ne 2
.mk
.na
\fB\fBconfig_file=\fR\fIfileame\fR\fR
.ad
.RS 23n
.rt  
设置配置文件。缺省值是 \fB/etc/security/pam_pkcs11/pam_pkcs11.conf\fR。
.RE

.sp
.ne 2
.mk
.na
\fB\fBdebug\fR\fR
.ad
.RS 23n
.rt  
启用调试输出。
.RE

.sp
.LP
因为它使用与 \fBpam_pkcs11\fR(5) 相同的配置文件，所以所有 \fBpam_pkcs11\fR 选项均可用。其中某些选项在非 PAM 环境中没有意义，因此被忽略。某些映射器选项（\fBmapfile\fR、\fBignorecase\fR）对证书内容不起作用，因此也被忽略。
.SH 退出状态
.sp
.LP
将返回以下退出值：
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
成功完成。 
.sp
\fBpkcs11_inspect\fR 在 \fBstdout\fR 中打印为映射器找到的所有证书内容。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
出现错误。
.RE

.SH 示例
.LP
\fB示例 1 \fR使用 \fBpkcs_inspect\fR
.sp
.LP
以下示例运行 \fBpkcs_inspect\fR 命令而没有任何选项：

.sp
.in +2
.nf
% pkcs11_inspect
.fi
.in -2
.sp

.LP
\fB示例 2 \fR使用具有选项的 \fBpkcs_inspect\fR
.sp
.LP
以下示例运行 \fBpkcs_inspect\fR 命令时具有选项：

.sp
.in +2
.nf
% pkcs11_inspect debug config_file=${HOME}/.pam_pkcs11.conf
.fi
.in -2
.sp

.SH 文件
.sp
.ne 2
.mk
.na
\fB\fB/etc/security/pam_pkcs11/pam_pkcs11.conf\fR\fR
.ad
.sp .6
.RS 4n

.RE

.SH 作者
.sp
.LP
Juan Antonio Martinez，\fBjonsito@teleline.es\fR
.SH 属性
.sp
.LP
有关下列属性的说明，请参见 \fBattributes\fR(5)：
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性类型属性值
_
可用性library/security/pam/module/pam-pkcs11
_
接口稳定性Uncommitted（未确定）
.TE

.SH 另请参见
.sp
.LP
\fBpklogin_finder\fR(1)、\fBattributes\fR(5)、\fBpam_pkcs11\fR(5)
.sp
.LP
\fIPAM-PKCS11 用户手册\fR，http://www.opensc-project.org/pam_pkcs11
