.TH at-spi-registryd 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
at-spi-registryd \- The AT-SPI registry daemon
.SH "DESCRIPTION"
.PP
at-spi-registryd is the AT-SPI registry daemon\&. It provides a mechanism for all
assistive technologies to discover and interact with applications running on
the desktop\&. Usually, at-spi-registryd is started by gnome-session when
accessibility is enabled\&.
.SH "FILES"
.PP
The following files are used by this application:
.TP 28
.B /usr/lib/at-spi-registryd
An application running the AT-SPI registry
.SH "SEE ALSO"
.PP
.BR libatk-1\&.0 (3lib),
.BR attributes (7)
