.\" Copyright (C) 2008  Free Software Foundation, Inc.
.\" See section COPYING for conditions for redistribution
.TH b2m 1 "21jul2008" "GNU Tools" "GNU Tools"
.de BP
.sp
.ti -.2i
\(**
..

.SH NAME
emacs-gtk \- GNU project Emacs (GTK version)
.SH SYNOPSIS
.hy 0
.na
.B emacs-gtk
[
.I command-line switches
] [
.I files ...
]
.ad b
.hy 1
.SH DESCRIPTION
\|\fBemacs-gtk\fP\| is the version of GNU Emacs built with
the GTK X Window System widget toolkit. See the \fBemacs\fR(1)
manpage for additional information on its operation.

.SH "SEE ALSO"
.BR emacs ( 1 )

.SH COPYING
Copyright
.if t \(co
.if n (c)
2008  Free Software Foundation, Inc.
.PP
Permission is granted to make and distribute verbatim copies of this
document provided the copyright notice and this permission notice are
preserved on all copies.
.PP
Permission is granted to copy and distribute modified versions of
this document under the conditions for verbatim copying, provided that
the entire resulting derived work is distributed under the terms of
a permission notice identical to this one.
.PP
Permission is granted to copy and distribute translations of this
document into another language, under the above conditions for
modified versions, except that this permission notice may be stated
in a translation approved by the Free Software Foundation.

.\" arch-tag: 9534977f-af78-42f0-991d-1df6b6c05573
