'\" t
.\"
.\" Modified for Solaris to to add the Solaris stability classification,
.\" and to add a note about source availability.
.\" 
.\" generic libgd man page for the LibGD Project
.TH libmpfr 3 "12 Nov 2010" "GNU MPFR 2.4.2" "Libraries"

.SH NAME
\fBlibmpfr\fP
.PP
.br
\fBLibMPFR\fR - The GNU Multiple Precision Rounding Floating Point Library - 
is an open source, portable library written in C for arbitrary precision
arithmetic on floating-point numbers. It is based on the GNU MP library 
(libGMP).  GNU MPFR aims to extend the class of floating-point numbers provided by the GNU MP Library by a precise semantics.
.br
.SH "SEE ALSO"
Complete documentation in HTML format for LibMPFR is available under
\fI/usr/share/doc/mpfr/html\fR.
Complete documentation in HTML format for LibGMP is available under
\fI/usr/share/doc/gmp/html\fR.
.SH AUTHOR
\fBLibMPFR's\fR main contributors are Guillaume Hanrot, Vincent Lefèvre,
Patrick Pélissier, Philippe Théveny and Paul Zimmermann.  Further details
and a complete list of LibMPFR's Contributors is available at \fIhttp://www.mpfr.org/mpfr-current/mpfr.html#Contributors\fR.  LibMPFR is released
under the \fILGPL V2 License\fR.
.LP

