'\" t
.\" Copyright (c) 2014, Oracle and/or its affiliates. All rights reserved.
.\"
.\" Licensed under the Apache License, Version 2.0 (the "License");
.\" you may not use this file except in compliance with the License.
.\" You may obtain a copy of the License at
.\"
.\"   http://www.apache.org/licenses/LICENSE-2.0
.\"
.\" Unless required by applicable law or agreed to in writing, software
.\" distributed under the License is distributed on an "AS IS" BASIS,
.\" WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
.\" See the License for the specific language governing permissions and
.\" limitations under the License.
.TH hiera 1 
.SH NAME
hiera \- Lightweight Pluggable Hierarchical Database
.SH SYNOPSIS
.B hiera
[options] key [default value] [variable='text'...]
.SH DESCRIPTION
Lightweight Pluggable Hierarchical Database
.sp
The default value will be used if no value is found for the key. Scope
variables will be interpolated into %{variable} placeholders in the hierarchy and in
returned values.
.SH OPTIONS
.TP
.BR "-V, --version"
Version information
.TP
.BR "-d, --debug"
Show debugging information
.TP
.BR "-a, --array"
Return all values as an array
.TP
.BR "-h, --hash"
Return all values as a hash
.TP
.BR "-c, --config "\fICONFIG\fR
Configuration file
.TP
.BR "-j, --json "\fISCOPE\fR
JSON format file to load scope from
.TP
.BR "-y, --yaml "\fISCOPE\fR
YAML format file to load scope from
.TP
.BR "-m, --mcollective "\fIIDENTITY\fR
Use facts from a node (via mcollective) as scope
.TP
.BR "-i, --inventory_service "\fIIDENTITY\fR
Use facts from a node (via Puppet's inventory service) as scope
.SH FILES
.BR /etc/hiera.yaml
Configuration File
