'\" t
.\"
.\" This man page created by Oracle to provide an overview of the Tcl
.\" library.
.\"
.TH libtcl 3 "16 July 2001"
.SH NAME
libtcl \- Tool Command Language application interfaces
.SH SYNOPSIS
.LP
.B cc
.RI "[ " "flag " \|.\|.\|. ] " "file \|.\|.\|."
.RI "[ " "library" " \|.\|.\|. ]"
.B \-ltcl8.5
.sp 1n
.SH DESCRIPTION
The Tcl library is a collection of interfaces for writing Tcl applications in C.
For more detail, see section 3tcl man pages specific to the library interfaces.
Additional information is also available from the Tcl Developer Xchange site:
.IP
.B http://tcl.tk/
.LP
.SH LICENSE
The Tcl software is copyrighted by the Regents of the University of
California, Sun Microsystems, Inc., Scriptics Corporation,
and other parties. 
.SH FILES
.PD 0
.TP 20
/usr/lib/libtcl8.5.so
shared object
.TP
/usr/lib/libtclstub8.5.a 
stubs library
.PD
