.\" $Id$
.TH bdftops 1 "24 October 2002" Ghostscript \" -*- nroff -*-
.SH NAME
bdftops \- Shell script to convert a BDF file to a scalable outline using bdftops.ps
.SH SYNOPSIS
\fBbdftops\fR BDF_filename [AFM_file1_name] gsf_filename fontname UniqueID [XUID] [encodingname]
.SH DESCRIPTION
Ghostscript provides a way to construct a (low-quality) Type 1 font from a bitmap font in the BDF format popular in the Unix world.  The shell script
.BR bdftops
converts a BDF file to a scalable outline using
.BR bdftops.ps.
.PP
The arguments have these meanings:
.PP
.nf
	BDF_filename	Input bitmap file in BDF format 
	AFM_file1_name	AFM files giving metrics 		(Optional)
	gsf_filename	Output file
	fontname		Name of the font
	UniqueID		UniqueID
	XUID			XUID, in the form n1.n2.n3...		(Optional)
	encodingname	"StandardEncoding" (the default),	(Optional)
				"ISOLatin1Encoding", "SymbolEncoding",
				"DingbatsEncoding" 
.fi
.PP
See the \fBFonts.htm\fR document in the Ghostscript distribution for information on converting fonts.
.PP
.SH EXAMPLES
.br
.PP
.nf
	bdftops pzdr.bdf ZapfDingbats.afm pzdr.gsf ZapfDingbats 4100000 1000000.1.41 
.fi
.PP
Then make an entry in Fontmap for the .gsf file (pzdr.gsf in this example).
.SH SEE ALSO
gs(1)
