.\" $Id$
.TH ps2ps2 1 "08 September 2008" Ghostscript \" -*- nroff -*-
.SH NAME
ps2ps2 \- Shell script to convert a PDF or Postscript Level 3 file into a Postscript Level 2 file.
.SH SYNOPSIS
\fBps2ps2\fR [options] input.[ps|eps|pdf] output.ps
.PP
.SH DESCRIPTION
This shell script converts a given PDF or Postscript Level 3 file into a Postscript Level 2 file by invoking Ghostscript and selecting a special "output device" called 
.BR ps2write
.
.PP
See the \fBPs2ps2.htm\fR document in the Ghostscript distribution for information on converting Postscript Level 3 or PDF into Postscript Level 2.
.PP
.SH SEE ALSO
gs(1)
