.\" $Id$
.TH pv.sh 1 "24 October 2002" Ghostscript \" -*- nroff -*-
.SH NAME
pv.sh \- Preview a specified page of a dvi file in a Ghostscript window
.SH SYNOPSIS
\fBpv.sh\fR page_number file_name[.dvi]
.SH DESCRIPTION
This shell script converts a given page to PostScript(TM) and displays it in a Ghostscript window.
.PP
For more information on this and other platform specific shell scripts for Ghostscript see \fBUse.htm\fR in the Ghostscript distribution.
.SH SEE ALSO
gs(1)
