.\" This manual page is derived from documentation obtained from
.\" http://manpages.ubuntu.com/manpages/cosmic/en/man1/pycodestyle.1.html
.TH PYCODESTYLE "1" "November 2016" "pycodestyle XXX" "User Commands"
.SH NAME
pycodestyle \- A tool to check your Python code against some of the style conventions in PEP 8.
.SH SYNOPSIS
.B pycodestyle
[\fIoptions\fR] \fIinput \fR...
.SH OPTIONS
.TP
\fB\-\-version\fR
show program's version number and exit
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR, \fB\-\-verbose\fR
print status messages, or debug with \fB\-vv\fR
.TP
\fB\-q\fR, \fB\-\-quiet\fR
report only file names, or nothing with \fB\-qq\fR
.TP
\fB\-\-exclude\fR=\fIpatterns\fR
exclude files or directories which match these comma separated patterns (default: .svn,CVS,.bzr,.hg,.git,__pycache__,.tox)
.TP
\fB\-\-filename\fR=\fIpatterns\fR
when parsing directories, only check filenames matching these comma separated patterns (default: *.py)
.TP
\fB\-\-select\fR=\fIerrors\fR
select errors and warning (e.g. E,W6)
.TP
\fB\-\-ignore\fR=\fIerrors\fR
skip errors and warnings (e.g. E4,W)
(default: E121,E123,E126,E226,E24,E704,W503)
.TP
\fB\-\-first\fR
show first occurrence of each error
.TP
\fB\-r\fR, \fB\-\-repeat\fR
(obsolete) show all occurrences of the same error
.TP
\fB\-\-show\-source\fR
show source code for each error
.TP
\fB\-\-show\-pep8\fR
show text of PEP 8 for each error (implies \-\-first)
.TP
\fB\-\-statistics\fR
count errors and warnings
.TP
\fB\-\-count\fR
print total number of errors and warnings to standard error and set exit code to 1 if total is not null
.TP
\fB\-\-max\-line\-length\fR=\fIn\fR
set maximum allowed line length (default: 79)
.TP
\fB\-\-hang-closing\fR
hang closing bracket instead of matching indentation of opening bracket's line
.TP
\fB\-\-format\fR=\fIformat\fR
set the error format [default|pylint|<custom>]
.TP
\fB\-\-diff\fR
report only lines changed according to the unified diff received on STDIN
.TP
\fB\-\-benchmark\fR
measure processing speed
.TP
\fB\-\-config\fR=\fIpath\fR
user config file location (default: $HOME/.config/pycodestyle)
.TP
.SH "USAGE EXAMPLES"
.TP
Display how often each error was found:
.sp
% pycodestyle \-\-statistics \-qq example/lib/
.TP
Show source code and more verbose explanation from PEP 8:
.sp
% pycodestyle \-\-show-source \-\-show-pep8 foo.py
.SH AUTHOR
This manual page was written by David Watson <dwatson@debian.org>, Michael Prokop <mika@debian.org> and Ondrej Novy <onovy@debian.org>.
