.TH enchant-lsmod 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
enchant-lsmod \- show languages and dictionaries that enchant supports\&.
.SH "SYNOPSIS"
.PP
\fBenchant-lsmod\fR [-\fBlang \fIlanguage_tag\fR\fR] [-\fBlist-dicts\fR] [-\fBh\fR] [-\fBv\fR]
.SH "DESCRIPTION"
.PP
\fBenchant-lsmod\fR is used to show languages and dictionaries that
.BR enchant (1)
supports\&.
.PP
.SH "OPTIONS"
.PP
The following options are supported:
.TP 24
.BI \-lang " language_tag"
List all supported languages or show whether a specified language is supported\&.
.TP 24
.B \-list-dicts
List all dictionaries that enchant supports\&.
.TP 24
.B \-h
Display the help text\&.
.TP 24
.B \-v
Prints the program\&'s version\&.
.SH "SEE ALSO"
.PP
.BR enchant (1),
.BR libenchant (3lib),
.BR attributes (7)
.SH "NOTES"
.PP
Written by Jeff Cai, Sun Microsystems Inc\&., 2008\&.
