'\" te
.\" Portions Copyright (c) 2008, 2012, Oracle and/or its affiliates. All rights reserved.
.\" This manual page is derived from documentation obtained from the OpenSC organization (www.opensc-project.org). This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.TH pkcs11_inspect 1 "2012 年 1 月 18 日" "SunOS 5.12" "ユーザーコマンド"
.SH 名前
pkcs11_inspect \- 証明書の内容の出力
.SH 形式
.LP
.nf
\fB/usr/lib/pam_pkcs11/pkcs11_inspect\fR [debug] [config_file=\fIfilename\fR]
.fi

.SH 機能説明
.sp
.LP
\fBpkcs11_inspect\fR は、\fBpam_pkcs11\fR ライブラリインフラストラクチャーを使用して、証明書の内容を取得および表示します。
.sp
.LP
\fBpkcs11_inspect\fR は、\fBpam_pkcs11\fR(5) PAM モジュールと同じ構成ファイルおよび引数を使用します。また、定義済みのマッパーモジュール (\fBms_mapper\fR など) を読み込み、それを使用して証明書に必要なエントリ (\fBms UPN\fR エントリなど) があるかどうかを調べます。
.sp
.LP
マッパーモジュールは、証明書内で適切なエントリを見つけると、それを \fBUTF-8\fR に変換して \fBstdout\fR に出力します。 
.SH オプション
.sp
.LP
サポートしているオプションは、次のとおりです。
.sp
.ne 2
.mk
.na
\fB\fBconfig_file=\fR\fIfileame\fR\fR
.ad
.RS 23n
.rt  
構成ファイルを設定します。デフォルト値は \fB/etc/security/pam_pkcs11/pam_pkcs11.conf\fR です。
.RE

.sp
.ne 2
.mk
.na
\fB\fBdebug\fR\fR
.ad
.RS 23n
.rt  
デバッグ出力を有効にします。
.RE

.sp
.LP
\fBpam_pkcs11\fR(5) と同じ構成ファイルが使用されるため、\fBpam_pkcs11\fR のすべてのオプションを使用できます。一部のオプションは PAM 以外の環境では意味がないため、無視されます。一部のマッパーオプション (\fBmapfile\fR、\fBignorecase\fR) も証明書の内容に影響しないため、無視されます。
.SH 終了ステータス
.sp
.LP
次の終了ステータスが返されます。
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.RS 5n
.rt  
正常終了。 
.sp
\fBpkcs11_inspect\fR は、マッパーに関して見つかった証明書の内容のすべてを \fBstdout\fR に出力します。
.RE

.sp
.ne 2
.mk
.na
\fB\fB1\fR\fR
.ad
.RS 5n
.rt  
エラーが発生した。
.RE

.SH 使用例
.LP
\fB例 1 \fR\fBpkcs_inspect\fR を使用する
.sp
.LP
次の例では、オプションを指定せずに \fBpkcs_inspect\fR コマンドを実行しています。

.sp
.in +2
.nf
% pkcs11_inspect
.fi
.in -2
.sp

.LP
\fB例 2 \fRオプションを指定して \fBpkcs_inspect\fR を使用する
.sp
.LP
次の例では、オプションを指定して \fBpkcs_inspect\fR コマンドを実行しています。

.sp
.in +2
.nf
% pkcs11_inspect debug config_file=${HOME}/.pam_pkcs11.conf
.fi
.in -2
.sp

.SH ファイル
.sp
.ne 2
.mk
.na
\fB\fB/etc/security/pam_pkcs11/pam_pkcs11.conf\fR\fR
.ad
.sp .6
.RS 4n

.RE

.SH 著者
.sp
.LP
Juan Antonio Martinez (\fBjonsito@teleline.es\fR)
.SH 属性
.sp
.LP
属性についての詳細は、マニュアルページの \fBattributes\fR(5) を参照してください。
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
属性タイプ属性値
_
使用条件library/security/pam/module/pam-pkcs11
_
インタフェースの安定性不確実
.TE

.SH 関連項目
.sp
.LP
\fBpklogin_finder\fR(1), \fBattributes\fR(5), \fBpam_pkcs11\fR(5)
.sp
.LP
\fIPAM-PKCS11 User Manual\fR, http://www.opensc-project.org/pam_pkcs11
