'\" t
.TH meld 1 "18 Nov 2010" "SunOS 5.11" "User Commands"
.SH NAME
meld \- graphical diff and merge tool
.SH SYNOPSIS
.LP
.nf
\fBmeld\fR [\fB--version\fR] [\fB-h\fR] [\fB--help\fR]
\fBmeld\fR [\fB-aceru\fR] \fIfile\fR
\fBmeld\fR [\fB-aceru\fR] \fIdir\fR
\fBmeld\fR [\fB-aceru\fR] [\fB--diff\fR] \fIdir\fR \fIdir\fR [\fIdir\fR]
\fBmeld\fR [\fB-aceru\fR] [\fB--diff\fR] \fIfile\fR \fIfile\fR [\fIfile\fR]
\fBmeld\fR [\fB...\fR] [\fB-L LABEL,...\fR] [\fB--label=LABEL,...\fR] \fIfile\fR \fIfile\fR [\fIfile\fR]
.fi

.SH DESCRIPTION
.LP
Meld is a graphical diff and merge tool that allows a user to visually compare two or three files simultaneously and edit the files in place. Differences are updated in real-time and highlighted using color coding. Users can also compare two or three directories at a time and launch file comparisons. In addition, users can browse working copies of the code from popular version control systems including CVS, Subversion, Bazaar-ng and Mercurial.

More extensive help information for Meld is included in the graphical interface.

.SH OPTIONS
.sp
.ne 2
.mk
.na
\fB\fB--version\fR\fR
.ad
.RS 15n
.rt  
displays the current version
.RE

.sp
.ne 2
.mk
.na
\fB\fB-h, --help\fR\fR
.ad
.RS 15n
.rt  
displays this help information
.RE

.sp
.ne 2
.mk
.na
\fB\fB-L LABEL, --label=LABEL\fR\fR
.ad
.RS 15n
.rt  

sets the tab label string for a file 
.RE

.sp
.ne 2
.mk
.na
\fB\fB-a, --auto-compare\fR\fR
.ad
.RS 15n
.rt  

automatically compare all differing files on startup
.RE

.sp
.ne 2
.mk
.na
\fB\fB-c, --context\fR\fR
.ad
.RS 15n
.rt  

for compatibility with diff command (ignored)
.RE

.sp
.ne 2
.mk
.na
\fB\fB-e, --ed\fR\fR
.ad
.RS 15n
.rt  

for compatibility with diff command (ignored)
.RE

.sp
.ne 2
.mk
.na
\fB\fB-r, --recursive\fR\fR
.ad
.RS 15n
.rt  

for compatibility with diff command (ignored)
.RE

.sp
.ne 2
.mk
.na
\fB\fB-u, --unified\fR\fR
.ad
.RS 15n
.rt  

for compatibility with diff command (ignored)
.RE

.sp
.ne 2
.mk
.na
\fB\fB-diff\fR\fR
.ad
.RS 15n
.rt  

creates a diff tab for up to three supplied files or directories
.RE

.SH EXIT STATUS
.LP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB\fB0\fR \fR
.ad
.RS 7n
.rt
Successful completion.
.RE

.sp
.ne 2
.mk
.na
\fB\fB>0\fR \fR
.ad
.RS 7n
.rt 
An error occurred.
.RE
.PP
.SH SEE ALSO
.LP 
diff(1), diff3(1)
