/*
 * Copyright (c) 2011, Oracle and/or its affiliates. All rights reserved.
 *
 * U.S. Government Rights - Commercial software. Government users are subject to
 * the Sun Microsystems, Inc. standard license agreement and applicable
 * provisions of the FAR and its supplements.
 *
 *
 * This distribution may include materials developed by third parties. Sun, Sun
 * Microsystems, the Sun logo and Solaris are trademarks or registered
 * trademarks of Sun Microsystems, Inc. in the U.S. and other countries.
 *
 */


/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf,v 1.1.1.1 2003/03/26 18:12:30 pcarroll Exp $
 */

#ifndef ME1LOADGROUP_H
#define ME1LOADGROUP_H

/* function declarations */
void init_demo_module_4(void);
Netsnmp_Node_Handler get_me4SystemLoadAvg15min;
Netsnmp_Node_Handler get_me4SystemLoadAvg1min;
Netsnmp_Node_Handler get_me4SystemLoadAvg5min;

#define OK 0
#define ERROR 1

int demo_4_post_read_config(int a, int b, void *c, void *d);
void refreshLoadAvg(unsigned int clientreg, void *clientarg);
void check_loadavg1_state();
void check_loadavg5_state();
void check_loadavg15_state();
char* conv_alarm_state(int state);
void read_load_thresholds(const char *token, char *cptr);

#endif /* ME1LOADGROUP_H */
