#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright (c) 2006, 2017, Oracle and/or its affiliates. All rights reserved.

FMRI=svc:/system/dbus:default

. /lib/svc/share/smf_include.sh

if [ ! -x /usr/lib/dbus-daemon ]; then
	echo "/usr/lib/dbus-daemon not found or not executable"
	exit $SMF_EXIT_ERR_FATAL
fi

# Generate machine-id regardless of zones
if [ ! -f /var/lib/dbus/machine-id ]; then
	/usr/bin/dbus-uuidgen --ensure
fi

case "$1" in
'start')
	# temporary hacks
	if [ ! -d /var/run/dbus ]; then
		mkdir -m 0755 /var/run/dbus
	fi
	if [ -f /var/run/dbus/pid ]; then
		rm -f /var/run/dbus/pid
	fi

	(ulimit -S -n 8192 ; /usr/lib/dbus-daemon --system)
	err=$?
	if [ $err -ne 0 ]; then
		echo "dbus failed to start: error $err"
		exit $SMF_EXIT_ERR_FATAL
	fi

	;;
*)
        echo "Usage: $0 { start }"
	exit $SMF_EXIT_ERR_FATAL 
        ;;
esac

exit $SMF_EXIT_OK
