'\" t
.\"
.\" Copyright (C) 2000-2007 - Laurent Destailleur - eldy@users.sourceforge.net
.\"
.TH awstats 1 "22 Jan 2009" "SunOS 5.11" "User Commands"
.SH NAME
awstats \- Log File Analyzer for Advanced Statistics

.SH DESCRIPTION
.LP
AWStats is a free powerful and featureful tool that generates advanced web, streaming, ftp or mail server statistics, graphically. This log analyzer works as a CGI or from command line and shows you all possible information your log contains, in few graphical web pages.

.SH FILES
The following files specify the installation locations for AWStats:
.PP
.TP
/usr/lib/awstats/tools
AWStats tools
.PP
.TP
/usr/lib/awstats/tools/webmin/awstats-2.0.wbm
A Webmin module for AWStats
.PP
.TP
/usr/lib/awstats/tools/xslt/awstats.xsd
AWStats XML database schema descriptor
.PP
.TP
/usr/lib/awstats/tools/xslt/*
Demo to manipulate AWStats XML database
.PP
.TP
/usr/share/doc/awstats
AWStats documentation location. An index file, /usr/share/doc/awstats/index.html, is provided. To setup and use AWStats, it is recommended to read these documents.
.PP
.TP
/usr/share/awstats/cgi-bin/awstats.pl
The main AWStats program (CLI/CGI)
.PP
.TP
/usr/share/awstats/cgi-bin/awredir.pl
A tool to track exit clicks
.PP
.TP
/usr/share/awstats/cgi-bin/awstats.model.conf
An model configuration file. Copy this file into awstats.www.mydomain.conf and edit this new config file to setup AWStats.

The config file must be in /etc/awstats, /usr/local/etc/awstats or /etc or same directory than awstats.pl. Refer to the documentation for more details.
.PP
.TP
/usr/share/awstats/cgi-bin/lang
Directory with languages files
.PP
.TP
/usr/share/awstats/cgi-bin/lib
Directory with awstats reference info
.PP
.TP
/usr/share/awstats/cgi-bin/plugins
Directory with optional plugins
.PP
.TP
/usr/share/awstats/icon
Directory with icons
.PP
.TP
/usr/share/awstats/classes
Java applet for graphapplet plugin
.PP
.TP
/usr/share/awstats/css
Samples of CSS files
.PP
.TP
/usr/share/awstats/js
Javascript sources for "Misc" feature
.PP

.SH ATTRIBUTES
See
.BR attributes (5)
for descriptions of the following attributes:
.sp
.TS
box;
cbp-1 | cbp-1
l | l .
ATTRIBUTE TYPE	ATTRIBUTE VALUE
=
Availability	web/analytics/awstats
=
Interface Stability	Uncommitted
.TE 
.PP
