'\" t
.\"     Title: rabbitmq-server
.\"    Author: The RabbitMQ Team <info@rabbitmq.com>
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 05/10/2013
.\"    Manual: RabbitMQ Server
.\"    Source: RabbitMQ Server
.\"  Language: English
.\"
.TH "RABBITMQ\-SERVER" "1" "05/10/2013" "RabbitMQ Server" "RabbitMQ Server"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rabbitmq-server \- start RabbitMQ AMQP server
.SH "SYNOPSIS"
.HP \w'\fBrabbitmq\-server\fR\ 'u
\fBrabbitmq\-server\fR [\-detached]
.SH "DESCRIPTION"
.PP
RabbitMQ is an implementation of AMQP, the emerging standard for high performance enterprise messaging\&. The RabbitMQ server is a robust and scalable implementation of an AMQP broker\&.
.PP
Running rabbitmq\-server in the foreground displays a banner message, and reports on progress in the startup sequence, concluding with the message "broker running", indicating that the RabbitMQ broker has been started successfully\&. To shut down the server, just terminate the process or use rabbitmqctl(1)\&.
.SH "ENVIRONMENT"
.PP
RABBITMQ_MNESIA_BASE
.RS 4
Defaults to
/var/lib/rabbitmq/mnesia\&. Set this to the directory where Mnesia database files should be placed\&.
.RE
.PP
RABBITMQ_LOG_BASE
.RS 4
Defaults to
/var/log/rabbitmq\&. Log files generated by the server will be placed in this directory\&.
.RE
.PP
RABBITMQ_NODENAME
.RS 4
Defaults to rabbit\&. This can be useful if you want to run more than one node per machine \-
\fBRABBITMQ_NODENAME\fR
should be unique per erlang\-node\-and\-machine combination\&. See the
\fBclustering on a single machine guide\fR\&\s-2\u[1]\d\s+2
for details\&.
.RE
.PP
RABBITMQ_NODE_IP_ADDRESS
.RS 4
By default RabbitMQ will bind to all interfaces, on IPv4 and IPv6 if available\&. Set this if you only want to bind to one network interface or address family\&.
.RE
.PP
RABBITMQ_NODE_PORT
.RS 4
Defaults to 5672\&.
.RE
.SH "OPTIONS"
.PP
\-detached
.RS 4
Start the server process in the background\&. Note that this will cause the pid not to be written to the pid file\&.
.RE
.SH "SEE ALSO"
.PP

\fBrabbitmq-env.conf\fR(5)
\fBrabbitmqctl\fR(1)
.SH "EXAMPLES"
.PP
\fBrabbitmq\-server \-detached\fR
.RS 4
Runs RabbitMQ AMQP server in the background\&.
.RE
.SH "AUTHOR"
.PP
\fBThe RabbitMQ Team <\fR\fB\fBinfo@rabbitmq\&.com\fR\fR\fB>\fR
.SH "NOTES"
.IP " 1." 4
clustering on a single machine guide
.RS 4
\%http://www.rabbitmq.com/clustering.html#single-machine
.RE
