--- slib/Makefile_orig	Sat Feb  2 18:55:34 2008
+++ slib/Makefile	Tue Mar 29 14:19:44 2011
@@ -178,12 +178,7 @@
 	mkdir -p $(DESTDIR)$(libslibdir)
 	-cp  $(ifiles) $(sfiles) $(bfiles) $(mkfiles) clrnamdb.scm $(DESTDIR)$(libslibdir)
 	mkdir -p $(DESTDIR)$(bindir)
-	echo '#! /bin/sh'			 > $(DESTDIR)$(bindir)slib
-	echo SCHEME_LIBRARY_PATH=$(DESTDIR)$(libslibdir)  >> $(DESTDIR)$(bindir)slib
-	echo S48_VICINITY=$(DESTDIR)$(S48LIB)	>> $(DESTDIR)$(bindir)slib
-	echo VERSION=$(VERSION)			>> $(DESTDIR)$(bindir)slib
-	echo export SCHEME_LIBRARY_PATH S48_VICINITY >> $(DESTDIR)$(bindir)slib
-	cat slib.sh				>> $(DESTDIR)$(bindir)slib
+	cat slib.sh				> $(DESTDIR)$(bindir)slib
 	chmod +x $(DESTDIR)$(bindir)slib
 
 uninstall:
