'\" te
.\" Copyright (C) 1998-2003, Carnegie Mellon Univeristy.  All Rights Reserved.
.\" Portions Copyright (C) 2003, Sun Microsystems, Inc. All Rights Reserved
.TH sasl_set_mutex 3sasl "22 Oct 2003" SASL "SASL man pages"
.SH NAME
sasl_set_mutex \- set the mutex lock functions used by the SASL library

.SH SYNOPSIS
.nf
cc [ flag ... ] file ... -lsasl   [ library ... ]
.B #include <sasl/sasl.h>

.BI "void sasl_set_mutex(sasl_mutex_alloc_t *" a ", "
.BI "                    sasl_mutex_lock_t *" l ", "
.BI "                    sasl_mutex_unlock_t *" u ", "
.BI "                    sasl_mutex_free_t *" f "); "
.fi

.SH DESCRIPTION
Use the
.B sasl_set_mutex()
interface to set the mutex lock routines that the SASL library and plug-ins will use.

.SH PARAMETERS
.I a
A pointer to the mutex lock allocation function

.I l
A pointer to the mutex lock function

.I u
A pointer to the mutex unlock function

.I f
A pointer to the mutex free or destroy function

.SH "RETURN VALUES"
sasl_set_mutex() has no return values.

