'\" te
.\" Copyright (C) 1998-2003, Carnegie Mellon Univeristy.  All Rights Reserved.
.\" Portions Copyright (C) 2003, Sun Microsystems, Inc. All Rights Reserved
.TH sasl_set_alloc 3sasl "22 Oct 2003" SASL "SASL man pages"
.SH NAME
sasl_set_alloc \- set the memory allocation functions used by the SASL library

.SH SYNOPSIS
.nf
cc [ flag ... ] file ... -lsasl   [ library ... ]
.B #include <sasl/sasl.h>

.BI "void sasl_set_alloc(sasl_malloc_t *" m ", "
.BI "                    sasl_calloc_t *" c ", "
.BI "                    sasl_realloc_t *" r ", "
.BI "                    sasl_free_t *" f "); "
.fi

.SH DESCRIPTION
Use the 
.B sasl_set_alloc()
interface to set the memory allocation routines that the SASL library and plug-ins will use.

.SH PARAMETERS
.I m
A pointer to a malloc() function

.I c
A pointer to a calloc() function

.I r
A pointer to a realloc() function

.I f
A pointer to a free() function

.SH "RETURN VALUES"
sasl_set_alloc() has no return values.

