'\" te
.\" Copyright (C) 1998-2003, Carnegie Mellon Univeristy.  All Rights Reserved.
.\" Portions Copyright (C) 2003, Sun Microsystems, Inc. All Rights Reserved
.TH sasl_utf8verify 3sasl "1 Oct 2003" SASL "SASL man pages"
.SH NAME
sasl_utf8verify \- encode base64 string

.SH SYNOPSIS
.nf
cc [ flag ... ] file ... -lsasl   [ library ... ]
.B #include <sasl/saslutil.h>

.BI "int sasl_utf8verify(const char *" str ", "
.BI "                    unsigned " len "); "
.fi

.SH DESCRIPTION
Use the 
.B sasl_utf8verify()
interface to verify that a string is valid UTF-8 and does not contain NULL, a carriage return, or a linefeed. If len == 0, strlen(str) will be used.

.SH PARAMETERS
.I str
A string

.I len
The length of the string

.SH "RETURN VALUES"
sasl_utf8verify() returns an integer that corresponds to a SASL error code.

.SH ERRORS
.TP 0.8i
.B SASL_OK
The call to sasl_utf8verify() was successful.
.TP 0.8i
.B SASL_BADPROT
There was invalid UTF-8, or an error was found.

