'\" te
.\" Copyright (c) 2008, 2017, Oracle and/or its affiliates\&. All rights reserved\&.
.TH quaggaadm 8 "02 mar 2017" "" ""
.SH "NAME"
quaggaadm \- quagga routing daemon administration tool
.SH "SYNOPSIS"
.PP
\fBquaggaadm\fR [-\fBe\fR|-\fBd\fR] \fIzebra\fR|\fIripd\fR|\fIripngd\fR|\fIospfd\fR|\fIospf6d\fR|\fIbgpd\fR|\fIisisd\fR
.SH "DESCRIPTION"
.PP
The \fBquaggaadm\fR command is provided as a simple wrapper to facilitate connection
to the quagga daemons respective vty terminal telnet interfaces. \fBquaggaadm\fR simply telnets
the appropriate vty port for the specified daemon on localhost, and from there the
user can update configuration for that daemon. Note that if the vty is disabled
for the given daemon, \fBquaggaadm\fR will prompt the user to request enable. Note
that to complete this operation, the user will require solaris.smf.manage.routing
and solaris.smf.modify.routing authorizations.
.SH "OPTIONS"
.sp
.LP
The following command-line options are supported by \fBquaggaadm\fR:
.sp
.ne 2
.mk
.na
\fB\fB\-e\fR\fR
.ad
.RS 6n
.rt
Automatically enable the vty for the specified daemon.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-d\fR\fR
.ad
.RS 6n
.rt
Automatically disable the vty for the specified daemon. No attempt to connect will be made.
.RE

.SH "EXIT STATUS"
.PP
The following exit values are returned:
.sp
.ne 2
.mk
.na
\fB\fB0\fR\fR
.ad
.sp .6
.in +4
Successful completion.
.sp
.sp 1
.in -4
.sp
.ne 2
.mk
.na
\fB\fB!=0\fR\fR
.ad
.sp .6
.in +4
An error occurred while obtaining or modifying the system configuration.
.sp
.sp 1
.in -4
.SH "SEE ALSO"
.PP
\fBquagga\fR(8), \fBattributes\fR(7), \fBrouteadm\fR(8)
