'\" te
.\"
.\" Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
.\"
.TH acpixtract 1 "24 Apr 2009" "SunOS 5.11" "User Commands"
.SH NAME
acpixtract - extract the ACPI tables
.SH SYNOPSIS
.LP
.nf
\fBacpixtract\fB [\fB-a\fR \fIsource\fR] [\fB-l\fR \fIsource\fR] 
    [\fB-s\fR \fIsource\fR \fIsignature\fR]
.fi

.SH DESCRIPTION
.sp
.LP
This utility will extract the ACPI tables from a raw source and presents them in data file form.

.SH OPTIONS
.sp
.LP
The following options are supported:
.sp
.ne 2
.mk
.na
\fB\fB-a\fR [\fIsource\fR]\fR
.ad
.sp .6
.RS 4n
Extract all of the ACPI tables from the specified source.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-l\fR [\fIsource\fR]\fR
.ad
.sp .6
.RS 4n
List all of the tables present in the specified source and provide a short summary.  This will not extract the information in the source.
.RE

.sp
.ne 2
.mk
.na
\fB\fB-s\fR [\fIsignature\fR]\fR [\fIsource\fR]\fR
.ad
.sp .6
.RS 4n
Extract only the tables matching the specified signature from the specified source.
.RE

.SH SEE ALSO
.sp
.LP
\fBacpidump\fR(1), \fBmadt\fR(1)
.RE

.SH RESOURCES
.sp
.LP
http://www.lesswatts.org/projects/acpi/utilities.php

.SH EXAMPLES
.sp
.LP
1. Extract the binary ACPI tables from acpidump output

    $ acpixtract -a acpidump.out

