.TH gnome-std-options 7 "7 Apr 2017" "SunOS 5.11" "Headers, Tables, and Macros"
.SH "NAME"
gnome-std-options \- standard options available for most GNOME applications
.SH "DESCRIPTION"
.PP
GNOME standard options which are available for most GNOME based
applications\&.  Some of these options are only available if the program
makes use of various GNOME interfaces such as GTK+,
\fBlibgnome\fR, or GNOME session\&.  Use the -\fB-help\fR option to see which
arguments are supported by any given program\&.
.SH "OPTIONS"
.PP
The following options are supported:
.TP 4
\fB\-?\fR, -\fB-help\fR
Display detailed usage message\&.
.TP 4
.B \-\-help-all
Display all help options\&.
.TP 4
.B \-\-usage
Display a brief usage message\&.
.PP
The following GTK+ options are supported:
.TP 4
.B \-\-help-gtk
Display GTK+ help options\&.
.TP 4
\fB\-\-class=\fIclass\fR\fR
Set the class of a GTK+ program, for use by the window manager\&.
.TP 4
\fB\-\-name=\fIname\fR\fR
Set the name of a GTK+ program, for use by the window manager\&.
.TP 4
\fB\-\-display=\fIdisplay\fR\fR
Specify an X Display to use, where \fIdisplay\fR
is in the following format:
.sp
\fIhostname\fR:\fIdisplaynumber\fR\&.\fIscreennumber\fR
.TP 4
.B \-\-g-fatal-warnings
Make all GTK+ warnings fatal\&. This will cause the application to be killed
when a warning is issued, rather than reporting this warning to
 \fBsdterr\fR\&.
.TP 4
\fB\-\-gdk-debug=\fIflags\fR\fR
Specify a list of GDK debug flags to set, in addition to those specified in the
GDK_DEBUG environment variable\&. This option is only available if GTK+ has been
configured with the -\fB-enable-debug=yes\fR option\&.  Valid
\fIflags\fR values are as follows:
.sp
.in +2
\(bu
.mk
.in +3
.rt
all
.sp
.in -3
\(bu
.mk
.in +3
.rt
dnd
.sp
.in -3
\(bu
.mk
.in +3
.rt
events
.sp
.in -3
\(bu
.mk
.in +3
.rt
misc
.sp
.in -3
\(bu
.mk
.in +3
.rt
xim
.sp
.in -3
.in -2
.sp
For more information, please refer to the GTK+ source code\&.
.TP 4
\fB\-\-gdk-no-debug=\fIflags\fR\fR
Specify a list of GDK debug flags to unset\&. This option is only available if
GTK+ has been configured with the -\fB-enable-debug=yes\fR option\&.
Valid \fIflags\fR values are the same as for the
-\fB-gdk-debug\fR option\&. For more information, please refer to
the GTK+ source code\&.
.TP 4
\fB\-\-gtk-debug=\fIflags\fR\fR
Specify a list of GTK+ options to set, in addition to those specified in the
GTK_DEBUG environment variable\&. This option is only available if GTK+ has
been configured with the -\fB-enable-debug=yes\fR option\&.  Valid
\fIflags\fR values are as follows:
.sp
.in +2
\(bu
.mk
.in +3
.rt
all
.sp
.in -3
\(bu
.mk
.in +3
.rt
geometry
.sp
.in -3
\(bu
.mk
.in +3
.rt
icontheme
.sp
.in -3
\(bu
.mk
.in +3
.rt
keybindings
.sp
.in -3
\(bu
.mk
.in +3
.rt
misc
.sp
.in -3
\(bu
.mk
.in +3
.rt
modules
.sp
.in -3
\(bu
.mk
.in +3
.rt
multihead
.sp
.in -3
\(bu
.mk
.in +3
.rt
plugsocket
.sp
.in -3
\(bu
.mk
.in +3
.rt
printing
.sp
.in -3
\(bu
.mk
.in +3
.rt
text
.sp
.in -3
\(bu
.mk
.in +3
.rt
tree
.sp
.in -3
\(bu
.mk
.in +3
.rt
updates
.sp
.in -3
.in -2
.sp
For more information, please refer to the GTK+ source code\&.
.TP 4
\fB\-\-gtk-no-debug=\fIflags\fR\fR
Specify a list of GTK+ options to unset\&. This option is only available if
GTK+ has been configured with -\fB-enable-debug=yes\fR option\&.
Valid \fIflags\fR values are the same as for the
-\fB-gtk-debug\fR option\&. For more information, please refer
to the GTK+ source code\&.
.TP 4
\fB\-\-gtk-module=\fImodule\fR\fR
Specify a list of GTK+ modules to load, in addition to those specifed in the
GTK_MODULES environment variable\&.
.TP 4
.B \-\-screen=\fIscreen\fR
Specify an X Screen to use\&. This is only useful if more than one
physical monitor is available\&. The default screen is 0\&.
\fIscreen\fR is an integer value in the range
0 to {NumberOfScreens - 1}\&.
.TP 4
.B \-\-sync
Specify that requests to the X Server should be sent synchronously\&.
By default, such requests are sent asynchronously\&. This option is
generally used when debugging an application, and should not be
used in normal execution\&.
.PP
The following GNOME options are supported\&:
.TP 4
.B \-\-help-gnome
Display GNOME options\&.
.TP 4
.B \-\-version
Print the version information for the command\&. You can also use
-\fBv\fR to specify this option\&.
.PP
The following GNOME session options are supported\&.
.TP 4
.B \-\-help-gnome-session
Display session management help options\&.
.TP 4
.B \-\-sm-client-id=\fIid\fR
Specify a session management ID\&.
.TP 4
.B \-\-sm-config-prefix=\fIprefix\fR
Specify the prefix of a saved configuration\&.
.TP 4
.B \-\-sm-disable
Disable the connection to the session manager\&.
.PP
Common application options that are supported\&.
.TP 4
.B \-\-geometry=\fIgeometry\fR
Specify the X geometry location for the application being launched, where
\fIgeometry\fR is in the following format:
.sp
\fIwidth\fRx\fIheight\fR+\fIxoff\fR+\fIyoff\fR
.SH "EXAMPLES"
.PP
.B "Example 1: Getting gnome-calculator usage"
.PP
.PP
.nf
example% \fBgnome-calculator -usage\fR
.fi
.PP
\fBExample 2: Launching ghex2 on host "Labrynth" with display
0 and screen 0\fR
.PP
.PP
.nf
example% \fBghex2 --display=Labrynth:0\&.0\fR
.fi
.SH "ENVIRONMENT VARIABLES"
.PP
See \fBenviron\fR(7) for descriptions of the following environment
variables:
.TP 24
.B "DISPLAY"
X Display on which the application should display\&.
.TP 24
.B "G_DEBUG"
This variable can be set to a list of debug options\&.
Set to fatal_warnings to make programs abort at the first call to
g_warning() or g_critical()\&.
Set to fatal_criticals to abort at the first call to g_critical()\&.
Set to gc-friendly to cause newly allocated memory that isn\&'t directly
initialized, as well as memory being freed to be reset to 0\&.
Set to resident-modules to cause all modules loaded by GModule to be
made resident\&.  Set to bind-now-modules to cause all modules loaded
by GModule to bind their symbols at load time, even if the code uses
%G_MODULE_BIND_LAZY\&.
.TP 24
.B "GDK_DEBUG"
If GTK+ has been configured with the -\fB-enable-debug=yes\fR
option, this variable can be set to a list of debug options that should
be set for GDK\&.  Refer to the -\fB-gdk-option\fR option for more
information\&.
.TP 24
.B "GTK_DEBUG"
If GTK+ has been configured with the -\fB-enable-debug=yes\fR
option, this variable can be set to a list of debug options that should
be set for GTK\&.  Refer to the -\fB-gtk-debug\fR option for for
more information\&.
.TP 24
.B "GTK_MODULES"
A list of GTK+ modules to load\&.
.TP 24
.B "GTK_PATH"
A list of directories to search when GTK+ is looking for dynamically
loaded objects such as the modules specified by GTK_MODULES,
theme engines, input method modules, file system backends, and
print backends\&.
.SH "SEE ALSO"
.PP
.BR broadwayd (1),
.BR gtk-launch (1),
.BR gnome-session (1),
.BR libglib-2\&.0 (3lib),
.BR libgtk-3 (3lib),
.BR attributes (7),
.BR environ (7),
.BR gnome-interfaces (7),
.BR X (7)
.PP
GTK+ source code
.PP
Latest version of the \fIGNOME Desktop User Guide\fR for your platform\&.
.SH "NOTES"
.PP
Written by Matt Keenan, Sun Microsystems Inc\&., 2003, 2006, 2007\&.
