'\" t
.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\"
.\" Copyright (c) 2007, 2012, Oracle and/or its affiliates. All rights reserved.
.\"
.\" ipmievd man page
.\"
.TH "ipmievd" "8" "07 November 2011"
.SH "NAME"
ipmievd \- IPMI event daemon for sending events to syslog
.SH "SYNOPSIS"
ipmievd [\fB\-c\fR|\fB\-h\fR|\fB\-d \fIN\fP\fR|\fB\-v\fR|\fB\-V\fR]
\fB\-I\fR \fIbmc\fP \fIsel\fP [<\fIoption\fP>]

ipmievd [\fB\-c\fR|\fB\-h\fR|\fB\-v\fR|\fB\-V\fR]
\fB\-I\fR \fIlan\fP \fB\-H\fR <\fIhostname\fP>
        [\fB\-p\fR <\fIport\fP>]
        [\fB\-U\fR <\fIusername\fP>]
        [\fB\-A\fR <\fIauthtype\fP>]
        [\fB\-L\fR <\fIprivlvl\fP>]
        [\fB\-a\fR|\fB\-E\fR|\fB\-P\fR|\fB\-f\fR <\fIpassword\fP>]
        [\fB\-o\fR <\fIoemtype\fP>]
        [\fB\-O\fR <\fIsel oem\fP>]
        \fIsel\fP [<\fIoption\fP>]

ipmievd [\fB\-c\fR|\fB\-h\fR|\fB\-v\fR|\fB\-V\fR]
\fB\-I\fR \fIlanplus\fP \fB\-H\fR <\fIhostname\fP>
        [\fB\-p\fR <\fIport\fP>]
        [\fB\-U\fR <\fIusername\fP>]
        [\fB\-L\fR <\fIprivlvl\fP>]
        [\fB\-a\fR|\fB\-E\fR|\fB\-P\fR|\fB\-f\fR <\fIpassword\fP>]
        [\fB\-o\fR <\fIoemtype\fP>]
        [\fB\-O\fR <\fIsel oem\fP>]
        [\fB\-C\fR <\fIciphersuite\fP>]
        \fIsel\fR [<\fIoption\fP>]
.SH "DESCRIPTION"
\fBipmievd\fP is a daemon that listens for events from the
Baseboard Management Controller (BMC) which are being sent to the 
System Event Log (SEL), and logs those messages to
syslog. The daemon actively polls the contents of the SEL for 
new events.
When an event is received, it is logged to
syslog using the
\fILOG_LOCAL4\fP facility.  On Solaris, it has been made to use
\fILOG_DAEMON\fP instead, so that no changes to /etc/syslog.conf are necessary.
.LP
\fBipmievd\fP is based on the \fBipmitool\fR utility and it shares the same 
Intelligent Platform Management Interface (IPMI)
support and session setup options.  The
\fBipmitool\fR man page provides more information on supported IPMI
interfaces.
.SH "OPTIONS"
.TP 
\fB\-a\fR
Prompt for the remote server password.
.TP
\fB\-A\fR <\fIauthtype\fP>
Specify an authentication type to use during IPMIv1.5 \fIlan\fP
session activation.  Supported types are NONE, PASSWORD, MD2, MD5, or OEM.
.TP 
.B \-c
Present output in comma separated variable (CSV) format.
.TP
\fB\-C\fR <\fIciphersuite\fP>
The remote server authentication, integrity, and encryption algorithms
to use for IPMIv2 \fIlanplus\fP connections.  See table 22\-19 in the
IPMIv2 specification.  The default is 3 which specifies RAKP\-HMAC\-SHA1
authentication, HMAC\-SHA1\-96 integrity, and AES\-CBC\-128 encryption algorightms.
.TP
\fB\-E\fR
The remote server password is specified by the environment
variable \fIIPMI_PASSWORD\fP.
.TP
.BI \-f " password_file"
Specify a file containing the remote server password. If this
option is absent, or if password_file is empty, the password
will default to NULL.
.IP
If the 
.B \-f 
option is not present, ipmitool will prompt the
user for a password. If no password is entered at the prompt,
the remote server password will default to NULL.
.IP
For IPMI v1.5, the maximum password length is 16 characters.
Passwords longer than 16 characters will be truncated.
.IP
For IPMI v2.0, the maximum password length is 20 characters.
Passwords longer than 20 characters will be truncated.
The longer password length is supported by the 
.B lanplus 
interface.
.TP 
.B \-h
Get basic usage help from the command line.
.TP 
.BI \-H " hostname"
Remote server address, which can be an IP address or hostname.  This 
option is required for the LAN interface connection.
.TP 
.BI \-I " interface"
Selects IPMI interface to use. Possible interfaces are:

.TS
tab(+);
l l .
bmc+IPMI v2.0 BMC interface [default]
lan+IPMI v1.5 LAN Interface
lanplus+IPMI v2.0 RMCP+ LAN Interface
.TE
.TP 
\fB\-L\fR <\fIprivlvl\fP>
Force session privilege level.  Can be CALLBACK, USER,
OPERATOR, ADMIN. Default is ADMIN.
.TP
\fB\-m\fR <\fIlocal_address\fP>
Set the local IPMB address.  The default is 0x20 and there
should be no need to change it for normal operation.
.TP
\fB\-o\fR <\fIoemtype\fP>
Select OEM type to support.  This usually involves minor hacks
in place in the code to work around quirks in various BMCs from
various manufacturers.  Use \fI\-o list\fP to see a list of
current supported OEM types.
.TP
\fB\-O\fR <\fIsel oem\fP>
Open selected file and read OEM SEL event descriptions to be used
during SEL listings.  See examples in contrib dir for file format.
.TP
.BI \-p " port"
Remote server UDP port to connect to (default is 623).
.TP 
\fB\-P\fR <\fIpassword\fP>
Remote server password is specified on the command line.
If supported it will be obscured in the process list.
\fBNote!\fR Specifying the password as a command line
option is not recommended.
.TP
.BI \-S " sdrcache"
Use local file for remote Sensor Data Repository (SDR) cache. 
Using a local SDR cache can drastically increase performance
for commands that require knowledge of the entire SDR to perform
their function.
.TP 
\fB\-t\fR <\fItarget_address\fP>
Bridge IPMI requests to the remote target address.
.TP
\.BI \-U " username"
Remote server username; default is NULL user.
.TP 
\fB\-d \fIN\fP\fR
Use device number N to specify the /dev/ipmiN (or
/dev/ipmi/N or /dev/ipmidev/N) device to use for in-band
BMC communication.  Used to target a specific BMC on a
multi-node, multi-BMC system through the ipmi device
driver interface.  Default is 0.
.TP
.B \-v
Increase verbose output level.  This option can be specified
multiple times to increase the level of debug output.  If given
three times, you will get hexdumps of all incoming and
outgoing packets.
.TP 
.B \-V
Display version information.
.SH "COMMANDS"
.TP 
\fIhelp\fP
This can be used to get command\-line help.  It can also be
placed at the end of commands to get option usage help.

> ipmievd help
.br 
Commands:
    sel      Poll SEL for notification of events
.TP 
\fIsel\fP
This command starts 
.B ipmievd 
with the SEL Polling event watching
mechanism.  This will poll the SEL periodically to determine if
new events have been logged.  This command should work with all
BMCs and is capable of using the LAN interface as well to monitor
a remote system and log its events to a local syslog.
.RS
.TP 
\fBdaemon\fP
Launch process as a daemon and reparent to init process.
All messages will be sent to syslog.  This is the default action.
.TP 
\fBnodaemon\fP
Do \fInot\fP become a daemon; instead, log all messages to stderr.
.TP
\fBpidfile\fR=\fIfilename\fR
Save process ID to this file when in daemon mode.  Defaults to
/var/run/ipmievd.pid.
.TP 
\fBtimeout\fR=\fIseconds\fR
Time between checks for SEL polling method.  Default is 10 seconds.
.SH "EXIT STATUS"
Upon successful completion, 
.B ipmievd 
returns 0.  On failure, 1 is returned.
.SH "EXAMPLE"
Local non\-daemon process checking remote SEL every 30
seconds:

> ipmievd \-I lan \-H 1.2.3.4 \-f passfile sel nodaemon timeout=30
.br 
Reading Sensors...
.br 
Waiting for Events...
.SH "FILES"
\fB/kernel/drv/amd64//bmc\fR
.in +30n
.sp
x86 \fBELF\fR kernel module for the bmc driver.
.sp
.in -30n
\fB/platform/sun4v/kernel/drv/sparcv9/bmc\fR
.in +30n
.sp
sparc \fBELF\fR kernel module for the bmc driver.
.in -30n
\fB/dev/bmc\fR
.in +30n
.sp
Character device node used to communicate with the bmc driver.
.in -30n
.SH "SEE ALSO"
attributes(5),
ipmitool(1M), 
smf(5), 
svcadm(1M), 
svccfg(1M), 
svcs(1)
.TP 
IPMItool Homepage
http://ipmitool.sourceforge.net
.TP 
Intelligent Platform Management Interface Specification
http://www.intel.com/design/servers/ipmi/spec.htm
.TP 
OpenIPMI Homepage
http://openipmi.sourceforge.net
.SH "NOTES"
The
.B ipmievd 
daemon is managed by the service management
facility, smf(5), under the service identifier:
svc:/network/ipmievd:default.
.LP
Administrative actions on this service, such as enabling
or disabling, can be performed using svcadm(1M). Use 
svccfg(1M) to make configuration changes and
svcs(1) to view configuration information and service status.
