#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2022 Marcel Telka
#

%patch% 01-assertEquals.patch

%hook-begin%
# This is the latest version with Python 3.9 support
VERSION=0.5.0

%hook-no-license%
(
	cat "$SOURCE_DIR/COPYING"
	printf '\n--- Apache-2.0 ------------------------------------------------------------\n\n'
	cat "$SOURCE_DIR/Apache-2.0"
	printf '\n--- BSD -------------------------------------------------------------------\n\n'
	cat "$SOURCE_DIR/BSD"
) > "$DISTRIBUTION.license"
%include-2%
# Force unittest test style because the automatically detected pytest does not
# work properly.
# See https://bugs.launchpad.net/testscenarios/+bug/1930149
# and https://github.com/testing-cabal/testscenarios/issues/5
TEST_STYLE = unittest

# testscenarios >= 0.6 requires Python >= 3.10
PYTHON_VERSIONS = 3.9
%include-3%
# https://bugs.launchpad.net/testscenarios/+bug/1930149/comments/3
COMPONENT_TEST_ARGS += testscenarios.tests.test_suite
%hook-manifest%
# We need versioned package only, so we cannot have PYVER in the p5m file name
mv "$DISTRIBUTION-PYVER.p5m" "$DISTRIBUTION-39.p5m"
sed -i -e 's/\$(PYVER)/3.9/g' -e 's/\$(PYV)/39/g' "$DISTRIBUTION-39.p5m"
MANIFEST="$DISTRIBUTION-39.p5m"
