'\" t
.\"
.\" CDDL HEADER START
.\"
.\" The contents of this file are subject to the terms of the
.\" Common Development and Distribution License (the "License").
.\" You may not use this file except in compliance with the License.
.\"
.\" You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
.\" or http://www.opensolaris.org/os/licensing.
.\" See the License for the specific language governing permissions
.\" and limitations under the License.
.\"
.\" When distributing Covered Code, include this CDDL HEADER in each
.\" file and include the License file at usr/src/OPENSOLARIS.LICENSE.
.\" If applicable, add the following below this CDDL HEADER, with the
.\" fields enclosed by brackets "[]" replaced with your own identifying
.\" information: Portions Copyright [yyyy] [name of copyright owner]
.\"
.\" CDDL HEADER END
.\"
.\" This man page created by Oracle to provide a reference to the documents 
.\" for JUnit provided with the JUnit distribution.
.\"
.TH junit 3 "20 Aug 2008"
.SH NAME
junit \- Java Unit testing framework
.SH SYNOPSIS
add junit.jar to the CLASSPATH
.SH DESCRIPTION
junit is a simple framework to write repeatable tests. It
is an instance of the xUnit architecture for unit testing 
frameworks. For additional information on using junit, 
browse the complete documentation at:
.IP
.B file:/usr/share/doc/junit/README.html
.LP
.SH LICENSE
Common Public License 
.SH FILES
/usr/share/lib/java/junit.jar
.IP
JUnit framework jar file, bundled with the hamcrest-core-1.1 dependency.
.LP

/usr/share/doc/junit/doc/building-junit.txt
.IP
Steps to build JUnit
.LP

/usr/share/doc/junit/doc/cookbook/cookbook.htm
.IP
A cookbook for implementing tests with JUnit.
.LP

/usr/share/lib/java/javadoc/junit/index.html
.IP
API documentation generated with javadoc. 
.LP

/usr/share/doc/junit/samples
.IP
sample test cases
.LP
.PD
