--- illumos-kvm-c24f295/Makefile.~1~	2015-09-17 23:24:14.419153315 +0300
+++ illumos-kvm-c24f295/Makefile	2015-09-17 23:26:10.563761662 +0300
@@ -2,14 +2,13 @@
 # Copyright 2015 Joyent, Inc.
 #
 
-KERNEL_SOURCE =	$(PWD)/../../illumos
+KERNEL_SOURCE =	$(PWD)/../../../illumos-gate/illumos-gate
 MDB_SOURCE =	$(KERNEL_SOURCE)/usr/src/cmd/mdb
-PROTO_AREA =	$(PWD)/../../../proto
-STRAP_AREA =	$(PWD)/../../../proto.strap
+PROTO_AREA =	$(PWD)/../../../illumos-gate/illumos-gate/proto/root_i386
 
-CC =		$(STRAP_AREA)/usr/bin/gcc
+CC =		/opt/gcc/4.4.4/bin/gcc
 LD =		/usr/bin/ld
-CTFBINDIR =	$(KERNEL_SOURCE)/usr/src/tools/proto/*/opt/onbld/bin/i386
+CTFBINDIR =	/opt/onbld/bin/i386
 CTFCONVERT =	$(CTFBINDIR)/ctfconvert
 CTFMERGE =	$(CTFBINDIR)/ctfmerge
 CSTYLE =	$(KERNEL_SOURCE)/usr/src/tools/scripts/cstyle
