'\" t
.\"
.\" Copyright 2011 Oracle Inc.  All rights reserved.
.\" Use is subject to license terms.
.\"
.\" ident	"@(#)pywbem.3	1.2	10/03/16 SMI"
.\"
.\" This man page created by Sun to provide a reference to the info pages
.\" for glib provided with the glib distribution.
.\"
.TH pywbem  "7 April 2009"
.SH NAME
pywbem \
.SH SYNOPSIS
\fI\fB

\fBimport pywbem\fP

.SH DESCRIPTION
Pywbem is a Python library for making CIM operations over HTTP using the WBEM CIM-XML protocol. It is based on the idea that a good WBEM client should be easy to use and not necessarily require a large amount of programming knowlege. Pywbem is suitable for a large range of tasks from simply poking around to writing web and GUI applications.

Pywbem also provides a Python provider interface, and is the fastest and easiest way to write providers.

.IP
info pywbem
.LP
For a more detailed description of the library contents see:
.IP
.B http://pywbem.wiki.sourceforge.net/
.LP
and its use, see:
.IP
.B http://pywbem.sourceforge.net/docs/tutorial.shtml
.LP
.SH LICENSE
GNU Lesser General Public License (LGPLv2)
.SH "SEE ALSO"
http://pywbem.sourceforge.net/docs/apidocs.shtml
