'\" te
.\" Copyright (c) 2012, Oracle and/or its affiliates. All rights reserved.
.TH proftpd.conf 4 "12 Jul 2012" "SunOS 5.11" "File Formats"
.SH NAME
proftpd.conf \- configuration file for the proftpd FTP server
.SH SYNOPSIS
.LP
.nf
\fB/etc/proftpd.conf\fR
.fi

.SH DESCRIPTION
.sp
.LP
The file \fB/etc/proftpd.conf\fR contains configuration for the \fBproftpd\fR(8) FTP server. The configuration documentation is located in \fBfile:///usr/share/doc/proftpd/Configuration.html\fR.
.sp
.LP

.SH SEE ALSO
.sp
.LP
\fBproftpd\fR(8)
