.\" libtidy man page for the Tidy Sourceforge project
.TH libtidy 3 "1 Feb 2007" "HTML Tidy 1.0.0" "Libraries"
.SH NAME
\fBlibtidy\fR - validate, correct, and pretty-print HTML files
.SH LIBRARY
The Tidy HTML Parser Library (libtidy, -ltidy)
.PP
.br
.SH DESCRIPTION
.PP
\fB#include <tidy.h>\fP
.br
\fB#include <buffio.h>\fP
.PP
.br
The
\fBtidy\fP
library provides parsing facilities for validating HTML, similar to
those found in
\fBlint\fP(1).
These functions are available in the
\fBlibtidy\fP
library.
Programs should be linked with
\fB\-ltidy\fP.
.SH "SEE ALSO"
\fBtidy\fP(1)
.PP
.br
Complete documentation in HTML format is available under
\fB/usr/share/doc/tidy/html\fP.
.SH AUTHOR
\fBTidy\fR was written by Dave Raggett <\fIdsr@w3.org\fR>, and is now maintained and developed by the Tidy team at \fIhttp://tidy.sourceforge.net/\fR.  It is released under the \fIMIT Licence\fR.
.LP
Generated automatically with HTML Tidy released on 1 September 2005.

