#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2022 Marcel Telka
#

%patch% 00-tox.toml.patch
%patch% 01-tox-no-diff-cover.patch
%patch% 02-tox-cov-proto.patch
%patch% 03-tox-pytest-indirectly.patch

%hook-begin%
# This is the latest version with Python 3.9 support
VERSION=3.19.1

%include-2%
# filelock >= 3.20.0 requires Python >= 3.10
PYTHON_VERSIONS = 3.9
%include-3%
# Normalize pointers
COMPONENT_TEST_TRANSFORMS += "-e 's/0x[0-9a-f]\{12\}/\$$(POINTER)/g'"

# Random directory name
COMPONENT_TEST_TRANSFORMS += "-e 's|/tmp/.*/garbage[^/]*|\$$(TMPDIR)|'"
%hook-manifest%
# We need versioned package only, so we cannot have PYVER in the p5m file name
mv "$DISTRIBUTION-PYVER.p5m" "$DISTRIBUTION-39.p5m"
sed -i -e 's/\$(PYVER)/3.9/g' -e 's/\$(PYV)/39/g' "$DISTRIBUTION-39.p5m"
MANIFEST="$DISTRIBUTION-39.p5m"
