#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2022 Marcel Telka
#

%patch% 01-test-no-devpi_process.patch
%patch% 02-tox-pytest-indirectly.patch
%patch% 03-tox-cov-proto.patch
%patch% 04-test-tox-path.patch
%patch% 05-tox-current-env.patch
%patch% 06-no-diff-cover.patch

%hook-begin%
# This is the latest version with Python 3.9 support
VERSION=4.30.3

%include-2%
# tox >= 4.31.0 requires Python >= 3.10
PYTHON_VERSIONS = 3.9
%include-3%
# This test fails with tox-current-env
PYTEST_ADDOPTS += --deselect tests/tox_env/python/test_python_api.py::test_build_wheel_in_non_base_pkg_env

# Random directory name
COMPONENT_TEST_TRANSFORMS += "-e 's|/tmp/.*/garbage[^/]*|\$$(TMPDIR)|'"
%hook-manifest%
# We need versioned package only, so we cannot have PYVER in the p5m file name
mv "$DISTRIBUTION-PYVER.p5m" "$DISTRIBUTION-39.p5m"
sed -i -e 's/\$(PYVER)/3.9/g' -e 's/\$(PYV)/39/g' "$DISTRIBUTION-39.p5m"
MANIFEST="$DISTRIBUTION-39.p5m"
