/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").
 * You may not use this file except in compliance with the License.
 *
 * You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 * or http://www.opensolaris.org/os/licensing.
 * See the License for the specific language governing permissions
 * and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at usr/src/OPENSOLARIS.LICENSE.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2010, 2012, Oracle and/or its affiliates. All rights reserved.
 */

package com.oracle.solaris.vp.panels.browser.client.swing;

public class PanelDialog extends javax.swing.JPanel {

    /** Creates new form PanelDialog */
    public PanelDialog() {
	setOpaque(false);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                nameLabel = new javax.swing.JLabel();
                resourcesLabel = new javax.swing.JLabel();
                classLabel = new javax.swing.JLabel();
                resourcesScroll = new javax.swing.JScrollPane();
                resourcesValue = new javax.swing.JList();
                classValue = new javax.swing.JTextField();
                nameValue = new javax.swing.JLabel();

                nameLabel.setText(com.oracle.solaris.vp.util.misc.finder.Finder.getString("browser.panel.label.name"));

                resourcesLabel.setText(com.oracle.solaris.vp.util.misc.finder.Finder.getString("browser.panel.label.resources"));

                classLabel.setText(com.oracle.solaris.vp.util.misc.finder.Finder.getString("browser.panel.label.class"));

                resourcesScroll.setViewportView(resourcesValue);

                classValue.setEditable(false);
                classValue.setText("jTextField1");
                classValue.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                classValueActionPerformed(evt);
                        }
                });

                nameValue.setText("jLabel1");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameLabel)
                                        .addComponent(classLabel)
                                        .addComponent(resourcesLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(classValue, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nameValue))
                                                .addContainerGap(253, Short.MAX_VALUE))
                                        .addComponent(resourcesScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameValue)
                                        .addComponent(nameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(classValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(classLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(resourcesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(resourcesLabel)))
                );
        }// </editor-fold>//GEN-END:initComponents

    private void classValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classValueActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_classValueActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel classLabel;
        javax.swing.JTextField classValue;
        private javax.swing.JLabel nameLabel;
        javax.swing.JLabel nameValue;
        private javax.swing.JLabel resourcesLabel;
        private javax.swing.JScrollPane resourcesScroll;
        javax.swing.JList resourcesValue;
        // End of variables declaration//GEN-END:variables

}
