#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2023 Marcel Telka
#

%include-3%
# This project does not support tox so we need to provide test requirements
# manually.
# See https://github.com/justinmayer/smartypants.py/blob/main/.github/workflows/ci.yml
TEST_REQUIRED_PACKAGES.python += library/python/docutils
TEST_REQUIRED_PACKAGES.python += library/python/pygments
%hook-manifest%
# both licenses apply, but license-detector is unable to detect that
sed -i -e 's/^\(COMPONENT_LICENSE =.*\) OR \(.*\)$/\1 AND \2/' Makefile
git add Makefile
