#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2024 Marcel Telka
#

%patch% 01-no-coverage.patch
%patch% 02-optional-deps.patch

%hook-begin%
# This is the latest version with Python 3.9 support
VERSION=25.3.0

%include-2%
# cattrs >= 26.1.0 requires Python >= 3.10
PYTHON_VERSIONS = 3.9
%include-3%
# This project does not support tox so we need to provide test requirements
# manually.
TEST_REQUIREMENTS_PEP735 += test

# We have no msgspec packaged yet
PYTEST_ADDOPTS += --ignore tests/preconf/test_msgspec_cpython.py
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_literal_dicts_msgspec
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_msgspec_efficient_enum
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_msgspec_json_converter
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_msgspec_json_unstruct_collection_overrides
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_msgspec_json_unions
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_msgspec_native_enums

# We have no cbor2 packaged yet
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_cbor2_efficient_enum
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_cbor2_native_enums

# We have no orjson packaged yet
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_literal_dicts_orjson
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_orjson_efficient_enum
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_orjson_native_enums

# We have no ujson packaged yet
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_ujson_native_enums
PYTEST_ADDOPTS += --deselect tests/test_preconf.py::test_ujson_efficient_enum

# Random directory name
COMPONENT_TEST_TRANSFORMS += "-e 's|/tmp/.*/garbage[^/]*|\$$(TMPDIR)|'"
%hook-manifest%
# We need versioned package only, so we cannot have PYVER in the p5m file name
mv "$DISTRIBUTION-PYVER.p5m" "$DISTRIBUTION-39.p5m"
sed -i -e 's/\$(PYVER)/3.9/g' -e 's/\$(PYV)/39/g' "$DISTRIBUTION-39.p5m"
MANIFEST="$DISTRIBUTION-39.p5m"
