'\" te
.\" Copyright (c) 2006, 2016, Oracle and/or its affiliates. All rights reserved.
.TH check-hostname 8 "8 Mar 2016" "SunOS 5.12" "System Administration Commands"
.SH NAME
check-hostname \- check if sendmail can determine the system's fully-qualified host name
.SH SYNOPSIS
.LP
.nf
\fB /usr/sbin/check-hostname\fR 
.fi

.SH DESCRIPTION
.sp
.LP
The \fBcheck-hostname\fR script is a migration aid for \fBsendmail\fR(8). This script tries to determine the local host's fully-qualified host name (FQHN) in a manner similar to \fBsendmail\fR(8). If \fBcheck-hostname\fR is able to determine the \fBFQHN\fR of the local host, it reports success. Otherwise, \fBcheck-hostname\fR reports how to reconfigure the system so that the \fBFQHN\fR can be properly determined.
.SH FILES
.sp
.ne 2
.mk
.na
\fB\fB/etc/hosts\fR\fR
.ad
.RS 22n
.rt  
Host name database
.RE

.sp
.ne 2
.mk
.na
\fB\fB/etc/nsswitch.conf\fR\fR
.ad
.RS 22n
.rt  
Name service switch configuration file
.RE

.sp
.ne 2
.mk
.na
\fB\fB/etc/resolv.conf\fR\fR
.ad
.RS 22n
.rt  
Configuration file for name server routines
.RE

.SH ATTRIBUTES
.sp
.LP
See \fBattributes\fR(7) for descriptions of the following attributes:
.sp

.sp
.TS
tab() box;
cw(2.75i) |cw(2.75i) 
lw(2.75i) |lw(2.75i) 
.
ATTRIBUTE TYPEATTRIBUTE VALUE
_
Availabilityservice/network/smtp/sendmail
_
Interface StabilityCommitted
.TE

.SH SEE ALSO
.sp
.LP
\fBhosts\fR(5), \fBattributes\fR(7), \fBdomainname\fR(8), \fBsendmail\fR(8)
