#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

#
# Copyright 2023 Marcel Telka
#

%include-3%
# See https://github.com/gitpython-developers/gitdb/issues/70
COMPONENT_PRE_TEST_ACTION += ( \
	$(RM) -r $(COMPONENT_TEST_DIR)/.git-test-tree ; \
	$(GIT) clone https://github.com/gitpython-developers/gitdb.git $(COMPONENT_TEST_DIR)/.git-test-tree ; \
	cd $(COMPONENT_TEST_DIR)/.git-test-tree ; \
	$(GIT) reset --hard $(HUMAN_VERSION) ; \
) ;
COMPONENT_TEST_ENV += GITDB_TEST_GIT_REPO_BASE=$(COMPONENT_TEST_DIR)/.git-test-tree/.git
