.TH eog 1 "7 Apr 2017" "SunOS 5.11" "User Commands"
.SH "NAME"
eog \- Eye of GNOME image viewer
.SH "SYNOPSIS"
.PP
\fBeog\fR [\fB\-\-disable-image-collection\fR] [\fB\-\-fullscreen\fR] [\fB\-\-slide-show\fR] [\fB\fIgnome-std-options\fR\fR] [\fB\fIfilename\fR\fR\&...]
.SH "DESCRIPTION"
.PP
The \fBeog\fR application is an image viewer for GNOME\&.  The specified image
files  are each displayed in a separate eog window\&.
.PP
.SH "OPTIONS"
.PP
The following options are supported:
.TP 32
\fB\-f\fR, \fB\-\-fullscreen\fR
Open in fullscreen mode\&.
.TP 32
\fB\-g\fR, \fB\-\-disable-gallery\fR
Disable image gallery\&.
.TP 32
\fB\-n\fR, \fB\-\-new-instance\fR
Open image in a new instance of eog\&.
.TP 32
\fB\-s\fR, \fB\-\-slide-show\fR
Open in slide show mode\&.
.TP 32
\fB\-w\fR, \fB\-\-single-window\fR
Open in a single window\&. If multiple windows are open the first one is used\&.
.TP 32
.I gnome-std-options
Standard options available for use with most GNOME applications\&.  See
.BR gnome-std-options (7)
for more information\&.
.SH "OPERANDS"
.PP
The following operands are supported:
.TP 16
.I filename
The name of one or more image files to be viewed\&.
.SH "EXAMPLES"
.PP
.B "Example 1: Launching the GNOME image viewer"
.PP
.PP
.nf
example% \fBeog \fR
.fi
.PP
.B "Example 2: Opening the image file test\&.png in GNOME image viewer"
.PP
.PP
.nf
example% \fBeog test\&.png\fR
.fi
.SH "EXIT STATUS"
.PP
The following exit values are returned:
.TP 9
.B 0
Application
exited successfully
.TP 9
.B >0
Application
exited with failure
.SH "SEE ALSO"
.PP
\fIEye of GNOME Manual\fR
.PP
Latest version of the \fIGNOME Desktop User Guide\fR for your platform\&.
.PP
.BR attributes (7),
.BR gnome-std-options (7)
.SH "NOTES"
.PP
Written by Brian Cameron, Sun Microsystems Inc\&., 2003, 2006, 2007\&.
